// Storage encoding of durable run records.
//
// This schema is internal to this module's store implementations; it is
// not part of the durable public API. Wire enum values are decoupled from
// the Go constants by an explicit conversion layer in internal/storagepb.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: durable/storage/v1/storage.proto

package storagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Phase int32

const (
	Phase_PHASE_UNSPECIFIED Phase = 0
	Phase_PHASE_FORWARD     Phase = 1
	Phase_PHASE_UNWIND      Phase = 2
	Phase_PHASE_DONE        Phase = 3
)

// Enum value maps for Phase.
var (
	Phase_name = map[int32]string{
		0: "PHASE_UNSPECIFIED",
		1: "PHASE_FORWARD",
		2: "PHASE_UNWIND",
		3: "PHASE_DONE",
	}
	Phase_value = map[string]int32{
		"PHASE_UNSPECIFIED": 0,
		"PHASE_FORWARD":     1,
		"PHASE_UNWIND":      2,
		"PHASE_DONE":        3,
	}
)

func (x Phase) Enum() *Phase {
	p := new(Phase)
	*p = x
	return p
}

func (x Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_durable_storage_v1_storage_proto_enumTypes[0].Descriptor()
}

func (Phase) Type() protoreflect.EnumType {
	return &file_durable_storage_v1_storage_proto_enumTypes[0]
}

func (x Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Phase.Descriptor instead.
func (Phase) EnumDescriptor() ([]byte, []int) {
	return file_durable_storage_v1_storage_proto_rawDescGZIP(), []int{0}
}

type Outcome int32

const (
	Outcome_OUTCOME_UNSPECIFIED Outcome = 0
	Outcome_OUTCOME_SUCCESS     Outcome = 1
	Outcome_OUTCOME_FAILURE     Outcome = 2
)

// Enum value maps for Outcome.
var (
	Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "OUTCOME_SUCCESS",
		2: "OUTCOME_FAILURE",
	}
	Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED": 0,
		"OUTCOME_SUCCESS":     1,
		"OUTCOME_FAILURE":     2,
	}
)

func (x Outcome) Enum() *Outcome {
	p := new(Outcome)
	*p = x
	return p
}

func (x Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_durable_storage_v1_storage_proto_enumTypes[1].Descriptor()
}

func (Outcome) Type() protoreflect.EnumType {
	return &file_durable_storage_v1_storage_proto_enumTypes[1]
}

func (x Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Outcome.Descriptor instead.
func (Outcome) EnumDescriptor() ([]byte, []int) {
	return file_durable_storage_v1_storage_proto_rawDescGZIP(), []int{1}
}

type OpStatus int32

const (
	// UNSPECIFIED doubles as "operation never started".
	OpStatus_OP_STATUS_UNSPECIFIED OpStatus = 0
	OpStatus_OP_STATUS_UNRESOLVED  OpStatus = 1
	OpStatus_OP_STATUS_SUCCEEDED   OpStatus = 2
	OpStatus_OP_STATUS_FAILED      OpStatus = 3
)

// Enum value maps for OpStatus.
var (
	OpStatus_name = map[int32]string{
		0: "OP_STATUS_UNSPECIFIED",
		1: "OP_STATUS_UNRESOLVED",
		2: "OP_STATUS_SUCCEEDED",
		3: "OP_STATUS_FAILED",
	}
	OpStatus_value = map[string]int32{
		"OP_STATUS_UNSPECIFIED": 0,
		"OP_STATUS_UNRESOLVED":  1,
		"OP_STATUS_SUCCEEDED":   2,
		"OP_STATUS_FAILED":      3,
	}
)

func (x OpStatus) Enum() *OpStatus {
	p := new(OpStatus)
	*p = x
	return p
}

func (x OpStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_durable_storage_v1_storage_proto_enumTypes[2].Descriptor()
}

func (OpStatus) Type() protoreflect.EnumType {
	return &file_durable_storage_v1_storage_proto_enumTypes[2]
}

func (x OpStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpStatus.Descriptor instead.
func (OpStatus) EnumDescriptor() ([]byte, []int) {
	return file_durable_storage_v1_storage_proto_rawDescGZIP(), []int{2}
}

type FailureKind int32

const (
	// UNSPECIFIED decodes as the Go default, system.
	FailureKind_FAILURE_KIND_UNSPECIFIED FailureKind = 0
	FailureKind_FAILURE_KIND_SYSTEM      FailureKind = 1
	FailureKind_FAILURE_KIND_USER        FailureKind = 2
	FailureKind_FAILURE_KIND_CANCELED    FailureKind = 3
)

// Enum value maps for FailureKind.
var (
	FailureKind_name = map[int32]string{
		0: "FAILURE_KIND_UNSPECIFIED",
		1: "FAILURE_KIND_SYSTEM",
		2: "FAILURE_KIND_USER",
		3: "FAILURE_KIND_CANCELED",
	}
	FailureKind_value = map[string]int32{
		"FAILURE_KIND_UNSPECIFIED": 0,
		"FAILURE_KIND_SYSTEM":      1,
		"FAILURE_KIND_USER":        2,
		"FAILURE_KIND_CANCELED":    3,
	}
)

func (x FailureKind) Enum() *FailureKind {
	p := new(FailureKind)
	*p = x
	return p
}

func (x FailureKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureKind) Descriptor() protoreflect.EnumDescriptor {
	return file_durable_storage_v1_storage_proto_enumTypes[3].Descriptor()
}

func (FailureKind) Type() protoreflect.EnumType {
	return &file_durable_storage_v1_storage_proto_enumTypes[3]
}

func (x FailureKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureKind.Descriptor instead.
func (FailureKind) EnumDescriptor() ([]byte, []int) {
	return file_durable_storage_v1_storage_proto_rawDescGZIP(), []int{3}
}

type StepRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ForwardStatus   OpStatus               `protobuf:"varint,1,opt,name=forward_status,json=forwardStatus,proto3,enum=durable.storage.v1.OpStatus" json:"forward_status,omitempty"`
	ForwardAttempts uint64                 `protobuf:"varint,2,opt,name=forward_attempts,json=forwardAttempts,proto3" json:"forward_attempts,omitempty"`
	State           []byte                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	UnwindStatus    OpStatus               `protobuf:"varint,4,opt,name=unwind_status,json=unwindStatus,proto3,enum=durable.storage.v1.OpStatus" json:"unwind_status,omitempty"`
	UnwindAttempts  uint64                 `protobuf:"varint,5,opt,name=unwind_attempts,json=unwindAttempts,proto3" json:"unwind_attempts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StepRecord) Reset() {
	*x = StepRecord{}
	mi := &file_durable_storage_v1_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepRecord) ProtoMessage() {}

func (x *StepRecord) ProtoReflect() protoreflect.Message {
	mi := &file_durable_storage_v1_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepRecord.ProtoReflect.Descriptor instead.
func (*StepRecord) Descriptor() ([]byte, []int) {
	return file_durable_storage_v1_storage_proto_rawDescGZIP(), []int{0}
}

func (x *StepRecord) GetForwardStatus() OpStatus {
	if x != nil {
		return x.ForwardStatus
	}
	return OpStatus_OP_STATUS_UNSPECIFIED
}

func (x *StepRecord) GetForwardAttempts() uint64 {
	if x != nil {
		return x.ForwardAttempts
	}
	return 0
}

func (x *StepRecord) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *StepRecord) GetUnwindStatus() OpStatus {
	if x != nil {
		return x.UnwindStatus
	}
	return OpStatus_OP_STATUS_UNSPECIFIED
}

func (x *StepRecord) GetUnwindAttempts() uint64 {
	if x != nil {
		return x.UnwindAttempts
	}
	return 0
}

type FailureRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepId        string                 `protobuf:"bytes,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Phase         Phase                  `protobuf:"varint,2,opt,name=phase,proto3,enum=durable.storage.v1.Phase" json:"phase,omitempty"`
	Attempt       uint64                 `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=at,proto3" json:"at,omitempty"`
	Kind          FailureKind            `protobuf:"varint,6,opt,name=kind,proto3,enum=durable.storage.v1.FailureKind" json:"kind,omitempty"`
	Reason        string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailureRecord) Reset() {
	*x = FailureRecord{}
	mi := &file_durable_storage_v1_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailureRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailureRecord) ProtoMessage() {}

func (x *FailureRecord) ProtoReflect() protoreflect.Message {
	mi := &file_durable_storage_v1_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailureRecord.ProtoReflect.Descriptor instead.
func (*FailureRecord) Descriptor() ([]byte, []int) {
	return file_durable_storage_v1_storage_proto_rawDescGZIP(), []int{1}
}

func (x *FailureRecord) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *FailureRecord) GetPhase() Phase {
	if x != nil {
		return x.Phase
	}
	return Phase_PHASE_UNSPECIFIED
}

func (x *FailureRecord) GetAttempt() uint64 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *FailureRecord) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FailureRecord) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *FailureRecord) GetKind() FailureKind {
	if x != nil {
		return x.Kind
	}
	return FailureKind_FAILURE_KIND_UNSPECIFIED
}

func (x *FailureRecord) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cause         string                 `protobuf:"bytes,1,opt,name=cause,proto3" json:"cause,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_durable_storage_v1_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_durable_storage_v1_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_durable_storage_v1_storage_proto_rawDescGZIP(), []int{2}
}

func (x *CancelRequest) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *CancelRequest) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

// RunRecord mirrors durable.RunRecord. Absent timestamps decode as the Go
// zero time; outcome presence marks a terminal run.
type RunRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RunId          string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	PipelineId     string                 `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	ResourceId     string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Input          []byte                 `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	Phase          Phase                  `protobuf:"varint,5,opt,name=phase,proto3,enum=durable.storage.v1.Phase" json:"phase,omitempty"`
	Steps          map[string]*StepRecord `protobuf:"bytes,6,rep,name=steps,proto3" json:"steps,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RootFailure    *FailureRecord         `protobuf:"bytes,7,opt,name=root_failure,json=rootFailure,proto3" json:"root_failure,omitempty"`
	UnwindFailures []*FailureRecord       `protobuf:"bytes,8,rep,name=unwind_failures,json=unwindFailures,proto3" json:"unwind_failures,omitempty"`
	Output         []byte                 `protobuf:"bytes,9,opt,name=output,proto3" json:"output,omitempty"`
	Outcome        *Outcome               `protobuf:"varint,10,opt,name=outcome,proto3,enum=durable.storage.v1.Outcome,oneof" json:"outcome,omitempty"`
	NextAttemptAt  *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=next_attempt_at,json=nextAttemptAt,proto3" json:"next_attempt_at,omitempty"`
	LastError      string                 `protobuf:"bytes,12,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	LastReason     string                 `protobuf:"bytes,13,opt,name=last_reason,json=lastReason,proto3" json:"last_reason,omitempty"`
	LastErrorAt    *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=last_error_at,json=lastErrorAt,proto3" json:"last_error_at,omitempty"`
	Cancel         *CancelRequest         `protobuf:"bytes,15,opt,name=cancel,proto3" json:"cancel,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RunRecord) Reset() {
	*x = RunRecord{}
	mi := &file_durable_storage_v1_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRecord) ProtoMessage() {}

func (x *RunRecord) ProtoReflect() protoreflect.Message {
	mi := &file_durable_storage_v1_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRecord.ProtoReflect.Descriptor instead.
func (*RunRecord) Descriptor() ([]byte, []int) {
	return file_durable_storage_v1_storage_proto_rawDescGZIP(), []int{3}
}

func (x *RunRecord) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunRecord) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *RunRecord) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *RunRecord) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *RunRecord) GetPhase() Phase {
	if x != nil {
		return x.Phase
	}
	return Phase_PHASE_UNSPECIFIED
}

func (x *RunRecord) GetSteps() map[string]*StepRecord {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *RunRecord) GetRootFailure() *FailureRecord {
	if x != nil {
		return x.RootFailure
	}
	return nil
}

func (x *RunRecord) GetUnwindFailures() []*FailureRecord {
	if x != nil {
		return x.UnwindFailures
	}
	return nil
}

func (x *RunRecord) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *RunRecord) GetOutcome() Outcome {
	if x != nil && x.Outcome != nil {
		return *x.Outcome
	}
	return Outcome_OUTCOME_UNSPECIFIED
}

func (x *RunRecord) GetNextAttemptAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextAttemptAt
	}
	return nil
}

func (x *RunRecord) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *RunRecord) GetLastReason() string {
	if x != nil {
		return x.LastReason
	}
	return ""
}

func (x *RunRecord) GetLastErrorAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastErrorAt
	}
	return nil
}

func (x *RunRecord) GetCancel() *CancelRequest {
	if x != nil {
		return x.Cancel
	}
	return nil
}

func (x *RunRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RunRecord) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_durable_storage_v1_storage_proto protoreflect.FileDescriptor

const file_durable_storage_v1_storage_proto_rawDesc = "" +
	"\n" +
	" durable/storage/v1/storage.proto\x12\x12durable.storage.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfe\x01\n" +
	"\n" +
	"StepRecord\x12C\n" +
	"\x0eforward_status\x18\x01 \x01(\x0e2\x1c.durable.storage.v1.OpStatusR\rforwardStatus\x12)\n" +
	"\x10forward_attempts\x18\x02 \x01(\x04R\x0fforwardAttempts\x12\x14\n" +
	"\x05state\x18\x03 \x01(\fR\x05state\x12A\n" +
	"\runwind_status\x18\x04 \x01(\x0e2\x1c.durable.storage.v1.OpStatusR\funwindStatus\x12'\n" +
	"\x0funwind_attempts\x18\x05 \x01(\x04R\x0eunwindAttempts\"\x86\x02\n" +
	"\rFailureRecord\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\tR\x06stepId\x12/\n" +
	"\x05phase\x18\x02 \x01(\x0e2\x19.durable.storage.v1.PhaseR\x05phase\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x04R\aattempt\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12*\n" +
	"\x02at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x123\n" +
	"\x04kind\x18\x06 \x01(\x0e2\x1f.durable.storage.v1.FailureKindR\x04kind\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\"Q\n" +
	"\rCancelRequest\x12\x14\n" +
	"\x05cause\x18\x01 \x01(\tR\x05cause\x12*\n" +
	"\x02at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\"\xac\a\n" +
	"\tRunRecord\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\x12\x14\n" +
	"\x05input\x18\x04 \x01(\fR\x05input\x12/\n" +
	"\x05phase\x18\x05 \x01(\x0e2\x19.durable.storage.v1.PhaseR\x05phase\x12>\n" +
	"\x05steps\x18\x06 \x03(\v2(.durable.storage.v1.RunRecord.StepsEntryR\x05steps\x12D\n" +
	"\froot_failure\x18\a \x01(\v2!.durable.storage.v1.FailureRecordR\vrootFailure\x12J\n" +
	"\x0funwind_failures\x18\b \x03(\v2!.durable.storage.v1.FailureRecordR\x0eunwindFailures\x12\x16\n" +
	"\x06output\x18\t \x01(\fR\x06output\x12:\n" +
	"\aoutcome\x18\n" +
	" \x01(\x0e2\x1b.durable.storage.v1.OutcomeH\x00R\aoutcome\x88\x01\x01\x12B\n" +
	"\x0fnext_attempt_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\rnextAttemptAt\x12\x1d\n" +
	"\n" +
	"last_error\x18\f \x01(\tR\tlastError\x12\x1f\n" +
	"\vlast_reason\x18\r \x01(\tR\n" +
	"lastReason\x12>\n" +
	"\rlast_error_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\vlastErrorAt\x129\n" +
	"\x06cancel\x18\x0f \x01(\v2!.durable.storage.v1.CancelRequestR\x06cancel\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1aX\n" +
	"\n" +
	"StepsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.durable.storage.v1.StepRecordR\x05value:\x028\x01B\n" +
	"\n" +
	"\b_outcome*S\n" +
	"\x05Phase\x12\x15\n" +
	"\x11PHASE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rPHASE_FORWARD\x10\x01\x12\x10\n" +
	"\fPHASE_UNWIND\x10\x02\x12\x0e\n" +
	"\n" +
	"PHASE_DONE\x10\x03*L\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fOUTCOME_SUCCESS\x10\x01\x12\x13\n" +
	"\x0fOUTCOME_FAILURE\x10\x02*n\n" +
	"\bOpStatus\x12\x19\n" +
	"\x15OP_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14OP_STATUS_UNRESOLVED\x10\x01\x12\x17\n" +
	"\x13OP_STATUS_SUCCEEDED\x10\x02\x12\x14\n" +
	"\x10OP_STATUS_FAILED\x10\x03*v\n" +
	"\vFailureKind\x12\x1c\n" +
	"\x18FAILURE_KIND_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13FAILURE_KIND_SYSTEM\x10\x01\x12\x15\n" +
	"\x11FAILURE_KIND_USER\x10\x02\x12\x19\n" +
	"\x15FAILURE_KIND_CANCELED\x10\x03B8Z6github.com/dangra/durable/internal/storagepb;storagepbb\x06proto3"

var (
	file_durable_storage_v1_storage_proto_rawDescOnce sync.Once
	file_durable_storage_v1_storage_proto_rawDescData []byte
)

func file_durable_storage_v1_storage_proto_rawDescGZIP() []byte {
	file_durable_storage_v1_storage_proto_rawDescOnce.Do(func() {
		file_durable_storage_v1_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_durable_storage_v1_storage_proto_rawDesc), len(file_durable_storage_v1_storage_proto_rawDesc)))
	})
	return file_durable_storage_v1_storage_proto_rawDescData
}

var file_durable_storage_v1_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_durable_storage_v1_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_durable_storage_v1_storage_proto_goTypes = []any{
	(Phase)(0),                    // 0: durable.storage.v1.Phase
	(Outcome)(0),                  // 1: durable.storage.v1.Outcome
	(OpStatus)(0),                 // 2: durable.storage.v1.OpStatus
	(FailureKind)(0),              // 3: durable.storage.v1.FailureKind
	(*StepRecord)(nil),            // 4: durable.storage.v1.StepRecord
	(*FailureRecord)(nil),         // 5: durable.storage.v1.FailureRecord
	(*CancelRequest)(nil),         // 6: durable.storage.v1.CancelRequest
	(*RunRecord)(nil),             // 7: durable.storage.v1.RunRecord
	nil,                           // 8: durable.storage.v1.RunRecord.StepsEntry
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_durable_storage_v1_storage_proto_depIdxs = []int32{
	2,  // 0: durable.storage.v1.StepRecord.forward_status:type_name -> durable.storage.v1.OpStatus
	2,  // 1: durable.storage.v1.StepRecord.unwind_status:type_name -> durable.storage.v1.OpStatus
	0,  // 2: durable.storage.v1.FailureRecord.phase:type_name -> durable.storage.v1.Phase
	9,  // 3: durable.storage.v1.FailureRecord.at:type_name -> google.protobuf.Timestamp
	3,  // 4: durable.storage.v1.FailureRecord.kind:type_name -> durable.storage.v1.FailureKind
	9,  // 5: durable.storage.v1.CancelRequest.at:type_name -> google.protobuf.Timestamp
	0,  // 6: durable.storage.v1.RunRecord.phase:type_name -> durable.storage.v1.Phase
	8,  // 7: durable.storage.v1.RunRecord.steps:type_name -> durable.storage.v1.RunRecord.StepsEntry
	5,  // 8: durable.storage.v1.RunRecord.root_failure:type_name -> durable.storage.v1.FailureRecord
	5,  // 9: durable.storage.v1.RunRecord.unwind_failures:type_name -> durable.storage.v1.FailureRecord
	1,  // 10: durable.storage.v1.RunRecord.outcome:type_name -> durable.storage.v1.Outcome
	9,  // 11: durable.storage.v1.RunRecord.next_attempt_at:type_name -> google.protobuf.Timestamp
	9,  // 12: durable.storage.v1.RunRecord.last_error_at:type_name -> google.protobuf.Timestamp
	6,  // 13: durable.storage.v1.RunRecord.cancel:type_name -> durable.storage.v1.CancelRequest
	9,  // 14: durable.storage.v1.RunRecord.created_at:type_name -> google.protobuf.Timestamp
	9,  // 15: durable.storage.v1.RunRecord.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 16: durable.storage.v1.RunRecord.StepsEntry.value:type_name -> durable.storage.v1.StepRecord
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_durable_storage_v1_storage_proto_init() }
func file_durable_storage_v1_storage_proto_init() {
	if File_durable_storage_v1_storage_proto != nil {
		return
	}
	file_durable_storage_v1_storage_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_durable_storage_v1_storage_proto_rawDesc), len(file_durable_storage_v1_storage_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_durable_storage_v1_storage_proto_goTypes,
		DependencyIndexes: file_durable_storage_v1_storage_proto_depIdxs,
		EnumInfos:         file_durable_storage_v1_storage_proto_enumTypes,
		MessageInfos:      file_durable_storage_v1_storage_proto_msgTypes,
	}.Build()
	File_durable_storage_v1_storage_proto = out.File
	file_durable_storage_v1_storage_proto_goTypes = nil
	file_durable_storage_v1_storage_proto_depIdxs = nil
}
