// Protobuf extensions declaring durable Pipelines and Steps.
//
// See spec/05-codegen.md.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: durable/v1/options.proto

package durablepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StepOptions declares a protobuf message as a durable Step.
type StepOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Durable Step identity, e.g. "reserve-capacity/v1". Required.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Whether successful forward execution may later participate in unwind.
	Unwind bool `protobuf:"varint,2,opt,name=unwind,proto3" json:"unwind,omitempty"`
	// Whether the Step is retired: structurally present, but no new forward
	// operation may begin for it.
	Retired       bool `protobuf:"varint,3,opt,name=retired,proto3" json:"retired,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepOptions) Reset() {
	*x = StepOptions{}
	mi := &file_durable_v1_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepOptions) ProtoMessage() {}

func (x *StepOptions) ProtoReflect() protoreflect.Message {
	mi := &file_durable_v1_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepOptions.ProtoReflect.Descriptor instead.
func (*StepOptions) Descriptor() ([]byte, []int) {
	return file_durable_v1_options_proto_rawDescGZIP(), []int{0}
}

func (x *StepOptions) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StepOptions) GetUnwind() bool {
	if x != nil {
		return x.Unwind
	}
	return false
}

func (x *StepOptions) GetRetired() bool {
	if x != nil {
		return x.Retired
	}
	return false
}

// PipelineOptions declares a protobuf marker message as a durable Pipeline.
type PipelineOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Durable Pipeline identity, e.g. "provision-machine". Required.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Fully-qualified Input message type, e.g. ".machines.v1.ProvisionMachineInput".
	Input string `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	// Fully-qualified Output message type.
	Output string `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	// Ordered Step topology as fully-qualified Step message types.
	Steps []string `protobuf:"bytes,4,rep,name=steps,proto3" json:"steps,omitempty"`
	// Optional named exclusion group. Pipelines sharing a group mutually
	// exclude per ResourceID: at most one nonterminal Run may exist across
	// the whole group for a resource. Without a group, a pipeline excludes
	// only with itself (the default per-pipeline slot).
	ExclusionGroup string `protobuf:"bytes,5,opt,name=exclusion_group,json=exclusionGroup,proto3" json:"exclusion_group,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PipelineOptions) Reset() {
	*x = PipelineOptions{}
	mi := &file_durable_v1_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineOptions) ProtoMessage() {}

func (x *PipelineOptions) ProtoReflect() protoreflect.Message {
	mi := &file_durable_v1_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineOptions.ProtoReflect.Descriptor instead.
func (*PipelineOptions) Descriptor() ([]byte, []int) {
	return file_durable_v1_options_proto_rawDescGZIP(), []int{1}
}

func (x *PipelineOptions) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PipelineOptions) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *PipelineOptions) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *PipelineOptions) GetSteps() []string {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *PipelineOptions) GetExclusionGroup() string {
	if x != nil {
		return x.ExclusionGroup
	}
	return ""
}

var file_durable_v1_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*StepOptions)(nil),
		Field:         51841,
		Name:          "durable.v1.step",
		Tag:           "bytes,51841,opt,name=step",
		Filename:      "durable/v1/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*PipelineOptions)(nil),
		Field:         51842,
		Name:          "durable.v1.pipeline",
		Tag:           "bytes,51842,opt,name=pipeline",
		Filename:      "durable/v1/options.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// NOTE: these numbers are in the 50000-99999 range reserved for
	// organization-internal use. Before publishing, replace them with
	// globally allocated extension numbers from the protobuf global
	// extension registry.
	//
	// optional durable.v1.StepOptions step = 51841;
	E_Step = &file_durable_v1_options_proto_extTypes[0]
	// optional durable.v1.PipelineOptions pipeline = 51842;
	E_Pipeline = &file_durable_v1_options_proto_extTypes[1]
)

var File_durable_v1_options_proto protoreflect.FileDescriptor

const file_durable_v1_options_proto_rawDesc = "" +
	"\n" +
	"\x18durable/v1/options.proto\x12\n" +
	"durable.v1\x1a google/protobuf/descriptor.proto\"O\n" +
	"\vStepOptions\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06unwind\x18\x02 \x01(\bR\x06unwind\x12\x18\n" +
	"\aretired\x18\x03 \x01(\bR\aretired\"\x8e\x01\n" +
	"\x0fPipelineOptions\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05input\x18\x02 \x01(\tR\x05input\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x14\n" +
	"\x05steps\x18\x04 \x03(\tR\x05steps\x12'\n" +
	"\x0fexclusion_group\x18\x05 \x01(\tR\x0eexclusionGroup:N\n" +
	"\x04step\x12\x1f.google.protobuf.MessageOptions\x18\x81\x95\x03 \x01(\v2\x17.durable.v1.StepOptionsR\x04step:Z\n" +
	"\bpipeline\x12\x1f.google.protobuf.MessageOptions\x18\x82\x95\x03 \x01(\v2\x1b.durable.v1.PipelineOptionsR\bpipelineB/Z-github.com/dangra/durable/durablepb;durablepbb\x06proto3"

var (
	file_durable_v1_options_proto_rawDescOnce sync.Once
	file_durable_v1_options_proto_rawDescData []byte
)

func file_durable_v1_options_proto_rawDescGZIP() []byte {
	file_durable_v1_options_proto_rawDescOnce.Do(func() {
		file_durable_v1_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_durable_v1_options_proto_rawDesc), len(file_durable_v1_options_proto_rawDesc)))
	})
	return file_durable_v1_options_proto_rawDescData
}

var file_durable_v1_options_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_durable_v1_options_proto_goTypes = []any{
	(*StepOptions)(nil),                 // 0: durable.v1.StepOptions
	(*PipelineOptions)(nil),             // 1: durable.v1.PipelineOptions
	(*descriptorpb.MessageOptions)(nil), // 2: google.protobuf.MessageOptions
}
var file_durable_v1_options_proto_depIdxs = []int32{
	2, // 0: durable.v1.step:extendee -> google.protobuf.MessageOptions
	2, // 1: durable.v1.pipeline:extendee -> google.protobuf.MessageOptions
	0, // 2: durable.v1.step:type_name -> durable.v1.StepOptions
	1, // 3: durable.v1.pipeline:type_name -> durable.v1.PipelineOptions
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_durable_v1_options_proto_init() }
func file_durable_v1_options_proto_init() {
	if File_durable_v1_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_durable_v1_options_proto_rawDesc), len(file_durable_v1_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_durable_v1_options_proto_goTypes,
		DependencyIndexes: file_durable_v1_options_proto_depIdxs,
		MessageInfos:      file_durable_v1_options_proto_msgTypes,
		ExtensionInfos:    file_durable_v1_options_proto_extTypes,
	}.Build()
	File_durable_v1_options_proto = out.File
	file_durable_v1_options_proto_goTypes = nil
	file_durable_v1_options_proto_depIdxs = nil
}
