// Code generated by protoc-gen-durable. DO NOT EDIT.
//
// source: machines/v1/machines.proto
// pipeline: provision-machine
// pipeline: decommission-machine

package machinespb

import (
	context "context"
	durable "github.com/dangra/durable"
	proto "google.golang.org/protobuf/proto"
	sync "sync"
)

// ValidateStep is the reference to the stateless step "validate/v1".
// It is not accepted by State lookup.
var ValidateStep = durable.NewStepRef("validate/v1")

// SelectHostStep is the typed reference to the state-producing step "select-host/v1".
var SelectHostStep = durable.NewStateStepRef("select-host/v1", func() *SelectHost { return &SelectHost{} })

// ReserveCapacityStep is the typed reference to the state-producing step "reserve-capacity/v1".
var ReserveCapacityStep = durable.NewStateStepRef("reserve-capacity/v1", func() *ReserveCapacity { return &ReserveCapacity{} })

// CreateMachineStep is the typed reference to the state-producing step "create-machine/v1".
var CreateMachineStep = durable.NewStateStepRef("create-machine/v1", func() *CreateMachine { return &CreateMachine{} })

// ValidateInvocation is passed to ValidateHandler methods.
type ValidateInvocation struct {
	core *durable.Invocation
}

func (inv ValidateInvocation) PipelineID() durable.PipelineID { return inv.core.PipelineID() }
func (inv ValidateInvocation) ResourceID() durable.ResourceID { return inv.core.ResourceID() }
func (inv ValidateInvocation) RunID() durable.RunID           { return inv.core.RunID() }
func (inv ValidateInvocation) StepID() durable.StepID         { return inv.core.StepID() }
func (inv ValidateInvocation) Attempt() uint64                { return inv.core.Attempt() }
func (inv ValidateInvocation) Phase() durable.Phase           { return inv.core.Phase() }

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (inv ValidateInvocation) Input() *ProvisionMachineInput {
	msg, _ := inv.core.InputMessage().(*ProvisionMachineInput)
	return msg
}

// State returns the committed state of the referenced step for this run.
// ok is false when no committed state exists.
func (inv ValidateInvocation) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(inv.core, step)
}

// ValidateHandler implements step "validate/v1".
type ValidateHandler interface {
	Run(context.Context, ValidateInvocation) error
}

// ValidateFunc adapts a function to ValidateHandler, in the style of
// http.HandlerFunc.
type ValidateFunc func(ctx context.Context, inv ValidateInvocation) error

func (f ValidateFunc) Run(ctx context.Context, inv ValidateInvocation) error { return f(ctx, inv) }

// SelectHostInvocation is passed to SelectHostHandler methods.
type SelectHostInvocation struct {
	core *durable.Invocation
}

func (inv SelectHostInvocation) PipelineID() durable.PipelineID { return inv.core.PipelineID() }
func (inv SelectHostInvocation) ResourceID() durable.ResourceID { return inv.core.ResourceID() }
func (inv SelectHostInvocation) RunID() durable.RunID           { return inv.core.RunID() }
func (inv SelectHostInvocation) StepID() durable.StepID         { return inv.core.StepID() }
func (inv SelectHostInvocation) Attempt() uint64                { return inv.core.Attempt() }
func (inv SelectHostInvocation) Phase() durable.Phase           { return inv.core.Phase() }

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (inv SelectHostInvocation) Input() *ProvisionMachineInput {
	msg, _ := inv.core.InputMessage().(*ProvisionMachineInput)
	return msg
}

// State returns the committed state of the referenced step for this run.
// ok is false when no committed state exists.
func (inv SelectHostInvocation) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(inv.core, step)
}

// SelectHostHandler implements step "select-host/v1".
type SelectHostHandler interface {
	Run(context.Context, SelectHostInvocation) (*SelectHost, error)
}

// SelectHostFunc adapts a function to SelectHostHandler, in the style of
// http.HandlerFunc.
type SelectHostFunc func(ctx context.Context, inv SelectHostInvocation) (*SelectHost, error)

func (f SelectHostFunc) Run(ctx context.Context, inv SelectHostInvocation) (*SelectHost, error) {
	return f(ctx, inv)
}

// ReserveCapacityInvocation is passed to ReserveCapacityHandler methods.
type ReserveCapacityInvocation struct {
	core *durable.Invocation
}

func (inv ReserveCapacityInvocation) PipelineID() durable.PipelineID { return inv.core.PipelineID() }
func (inv ReserveCapacityInvocation) ResourceID() durable.ResourceID { return inv.core.ResourceID() }
func (inv ReserveCapacityInvocation) RunID() durable.RunID           { return inv.core.RunID() }
func (inv ReserveCapacityInvocation) StepID() durable.StepID         { return inv.core.StepID() }
func (inv ReserveCapacityInvocation) Attempt() uint64                { return inv.core.Attempt() }
func (inv ReserveCapacityInvocation) Phase() durable.Phase           { return inv.core.Phase() }

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (inv ReserveCapacityInvocation) Input() *ProvisionMachineInput {
	msg, _ := inv.core.InputMessage().(*ProvisionMachineInput)
	return msg
}

// State returns the committed state of the referenced step for this run.
// ok is false when no committed state exists.
func (inv ReserveCapacityInvocation) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(inv.core, step)
}

// ReserveCapacityHandler implements step "reserve-capacity/v1".
type ReserveCapacityHandler interface {
	Run(context.Context, ReserveCapacityInvocation) (*ReserveCapacity, error)

	Unwind(context.Context, ReserveCapacityInvocation, durable.Failure) error
}

// ReserveCapacityFuncs adapts a pair of functions to ReserveCapacityHandler.
type ReserveCapacityFuncs struct {
	RunFunc    func(ctx context.Context, inv ReserveCapacityInvocation) (*ReserveCapacity, error)
	UnwindFunc func(context.Context, ReserveCapacityInvocation, durable.Failure) error
}

func (f ReserveCapacityFuncs) Run(ctx context.Context, inv ReserveCapacityInvocation) (*ReserveCapacity, error) {
	return f.RunFunc(ctx, inv)
}

func (f ReserveCapacityFuncs) Unwind(ctx context.Context, inv ReserveCapacityInvocation, failure durable.Failure) error {
	return f.UnwindFunc(ctx, inv, failure)
}

// CreateMachineInvocation is passed to CreateMachineHandler methods.
type CreateMachineInvocation struct {
	core *durable.Invocation
}

func (inv CreateMachineInvocation) PipelineID() durable.PipelineID { return inv.core.PipelineID() }
func (inv CreateMachineInvocation) ResourceID() durable.ResourceID { return inv.core.ResourceID() }
func (inv CreateMachineInvocation) RunID() durable.RunID           { return inv.core.RunID() }
func (inv CreateMachineInvocation) StepID() durable.StepID         { return inv.core.StepID() }
func (inv CreateMachineInvocation) Attempt() uint64                { return inv.core.Attempt() }
func (inv CreateMachineInvocation) Phase() durable.Phase           { return inv.core.Phase() }

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (inv CreateMachineInvocation) Input() *ProvisionMachineInput {
	msg, _ := inv.core.InputMessage().(*ProvisionMachineInput)
	return msg
}

// State returns the committed state of the referenced step for this run.
// ok is false when no committed state exists.
func (inv CreateMachineInvocation) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(inv.core, step)
}

// CreateMachineHandler implements step "create-machine/v1".
type CreateMachineHandler interface {
	Run(context.Context, CreateMachineInvocation) (*CreateMachine, error)
}

// CreateMachineFunc adapts a function to CreateMachineHandler, in the style of
// http.HandlerFunc.
type CreateMachineFunc func(ctx context.Context, inv CreateMachineInvocation) (*CreateMachine, error)

func (f CreateMachineFunc) Run(ctx context.Context, inv CreateMachineInvocation) (*CreateMachine, error) {
	return f(ctx, inv)
}

// ProvisionMachineReducer produces the pipeline output from the immutable input
// and committed step states. It must be pure: deterministic, side-effect
// free, synchronous, and non-failing.
type ProvisionMachineReducer func(*ProvisionMachine) *ProvisionMachineOutput

var provisionMachineViews sync.Map

func (x *ProvisionMachine) durableView() *durable.ReduceView {
	v, ok := provisionMachineViews.Load(x)
	if !ok {
		panic("machinespb: ProvisionMachine is only usable as a reducer view during reduction")
	}
	return v.(*durable.ReduceView)
}

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (x *ProvisionMachine) Input() *ProvisionMachineInput {
	msg, _ := x.durableView().InputMessage().(*ProvisionMachineInput)
	return msg
}

// State returns the committed state of the referenced step for the run
// being reduced. ok is false when no committed state exists.
func (x *ProvisionMachine) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(x.durableView(), step)
}

// ProvisionMachineDefinition is the unbound pipeline definition.
type ProvisionMachineDefinition struct {
	def *durable.Definition
}

// NewProvisionMachine assembles the "provision-machine" pipeline definition
// from its step handlers and reducer.
func NewProvisionMachine(
	validate ValidateHandler,
	selectHost SelectHostHandler,
	reserveCapacity ReserveCapacityHandler,
	createMachine CreateMachineHandler,
	reduce ProvisionMachineReducer,
) *ProvisionMachineDefinition {
	return &ProvisionMachineDefinition{def: durable.NewDefinition(durable.DefinitionConfig{
		ID:             "provision-machine",
		ExclusionGroup: "machine-lifecycle",
		NewInput:       func() proto.Message { return &ProvisionMachineInput{} },
		Reduce: func(view *durable.ReduceView) proto.Message {
			x := &ProvisionMachine{}
			provisionMachineViews.Store(x, view)
			defer provisionMachineViews.Delete(x)
			return reduce(x)
		},
		Steps: []durable.StepConfig{
			{
				ID: "validate/v1",
				Run: func(ctx context.Context, core *durable.Invocation) (proto.Message, error) {
					return nil, validate.Run(ctx, ValidateInvocation{core: core})
				},
			},
			{
				ID:       "select-host/v1",
				HasState: true,
				Run: func(ctx context.Context, core *durable.Invocation) (proto.Message, error) {
					state, err := selectHost.Run(ctx, SelectHostInvocation{core: core})
					if state == nil {
						return nil, err
					}
					return state, err
				},
			},
			{
				ID:       "reserve-capacity/v1",
				Unwind:   true,
				HasState: true,
				Run: func(ctx context.Context, core *durable.Invocation) (proto.Message, error) {
					state, err := reserveCapacity.Run(ctx, ReserveCapacityInvocation{core: core})
					if state == nil {
						return nil, err
					}
					return state, err
				},
				UnwindFunc: func(ctx context.Context, core *durable.Invocation, failure durable.Failure) error {
					return reserveCapacity.Unwind(ctx, ReserveCapacityInvocation{core: core}, failure)
				},
			},
			{
				ID:       "create-machine/v1",
				HasState: true,
				Run: func(ctx context.Context, core *durable.Invocation) (proto.Message, error) {
					state, err := createMachine.Run(ctx, CreateMachineInvocation{core: core})
					if state == nil {
						return nil, err
					}
					return state, err
				},
			},
		},
	})}
}

// Bind registers the definition with an engine. It is allowed only before
// Engine.Start.
func (d *ProvisionMachineDefinition) Bind(e *durable.Engine) (*ProvisionMachinePipeline, error) {
	p, err := d.def.Bind(e)
	if err != nil {
		return nil, err
	}
	return &ProvisionMachinePipeline{pipeline: p}, nil
}

// ProvisionMachinePipeline is the definition bound to an engine.
type ProvisionMachinePipeline struct {
	pipeline *durable.Pipeline
}

// Schedule creates a run for the resource slot or returns the active one.
func (p *ProvisionMachinePipeline) Schedule(ctx context.Context, resource durable.ResourceID, input *ProvisionMachineInput, opts ...durable.ScheduleOption) (ProvisionMachineRun, bool, error) {
	run, created, err := p.pipeline.Schedule(ctx, resource, input, opts...)
	if err != nil {
		return ProvisionMachineRun{}, created, err
	}
	return ProvisionMachineRun{run: run}, created, nil
}

// Run returns a handle to an existing run of this pipeline.
func (p *ProvisionMachinePipeline) Run(ctx context.Context, id durable.RunID) (ProvisionMachineRun, error) {
	run, err := p.pipeline.Run(ctx, id)
	if err != nil {
		return ProvisionMachineRun{}, err
	}
	return ProvisionMachineRun{run: run}, nil
}

// Active returns handles for this pipeline's nonterminal runs.
func (p *ProvisionMachinePipeline) Active(ctx context.Context) ([]ProvisionMachineRun, error) {
	runs, err := p.pipeline.Active(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]ProvisionMachineRun, 0, len(runs))
	for _, run := range runs {
		out = append(out, ProvisionMachineRun{run: run})
	}
	return out, nil
}

// Runs returns handles for all runs of this pipeline against a resource,
// oldest first.
func (p *ProvisionMachinePipeline) Runs(ctx context.Context, resource durable.ResourceID) ([]ProvisionMachineRun, error) {
	runs, err := p.pipeline.Runs(ctx, resource)
	if err != nil {
		return nil, err
	}
	out := make([]ProvisionMachineRun, 0, len(runs))
	for _, run := range runs {
		out = append(out, ProvisionMachineRun{run: run})
	}
	return out, nil
}

// ProvisionMachineRun is a typed handle to one run of the pipeline.
type ProvisionMachineRun struct {
	run durable.Run
}

func (r ProvisionMachineRun) ID() durable.RunID { return r.run.ID() }

func (r ProvisionMachineRun) Status(ctx context.Context) (durable.Status, error) {
	return r.run.Status(ctx)
}

// Cancel durably requests cancellation: the run stops selecting new
// forward work and unwinds successfully executed steps.
func (r ProvisionMachineRun) Cancel(ctx context.Context, cause string) error {
	return r.run.Cancel(ctx, cause)
}

// Wait blocks until the run is terminal. A successful result carries the
// pipeline output; a failed run has none.
func (r ProvisionMachineRun) Wait(ctx context.Context) (ProvisionMachineResult, error) {
	res, err := r.run.Wait(ctx)
	if err != nil {
		return ProvisionMachineResult{}, err
	}
	out := ProvisionMachineResult{Result: res}
	if res.Succeeded() {
		b, err := r.run.OutputBytes(ctx)
		if err != nil {
			return ProvisionMachineResult{}, err
		}
		msg := &ProvisionMachineOutput{}
		if err := proto.Unmarshal(b, msg); err != nil {
			return ProvisionMachineResult{}, err
		}
		out.output = msg
	}
	return out, nil
}

// ProvisionMachineResult is the typed terminal result of a run.
type ProvisionMachineResult struct {
	durable.Result
	output *ProvisionMachineOutput
}

// Output returns the pipeline output. It is non-nil exactly when the run
// succeeded.
func (r ProvisionMachineResult) Output() *ProvisionMachineOutput { return r.output }

// ReleaseMachineStep is the reference to the stateless step "release-machine/v1".
// It is not accepted by State lookup.
var ReleaseMachineStep = durable.NewStepRef("release-machine/v1")

// ReleaseMachineInvocation is passed to ReleaseMachineHandler methods.
type ReleaseMachineInvocation struct {
	core *durable.Invocation
}

func (inv ReleaseMachineInvocation) PipelineID() durable.PipelineID { return inv.core.PipelineID() }
func (inv ReleaseMachineInvocation) ResourceID() durable.ResourceID { return inv.core.ResourceID() }
func (inv ReleaseMachineInvocation) RunID() durable.RunID           { return inv.core.RunID() }
func (inv ReleaseMachineInvocation) StepID() durable.StepID         { return inv.core.StepID() }
func (inv ReleaseMachineInvocation) Attempt() uint64                { return inv.core.Attempt() }
func (inv ReleaseMachineInvocation) Phase() durable.Phase           { return inv.core.Phase() }

// State returns the committed state of the referenced step for this run.
// ok is false when no committed state exists.
func (inv ReleaseMachineInvocation) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(inv.core, step)
}

// ReleaseMachineHandler implements step "release-machine/v1".
type ReleaseMachineHandler interface {
	Run(context.Context, ReleaseMachineInvocation) error
}

// ReleaseMachineFunc adapts a function to ReleaseMachineHandler, in the style of
// http.HandlerFunc.
type ReleaseMachineFunc func(ctx context.Context, inv ReleaseMachineInvocation) error

func (f ReleaseMachineFunc) Run(ctx context.Context, inv ReleaseMachineInvocation) error {
	return f(ctx, inv)
}

var decommissionMachineViews sync.Map

func (x *DecommissionMachine) durableView() *durable.ReduceView {
	v, ok := decommissionMachineViews.Load(x)
	if !ok {
		panic("machinespb: DecommissionMachine is only usable as a reducer view during reduction")
	}
	return v.(*durable.ReduceView)
}

// State returns the committed state of the referenced step for the run
// being reduced. ok is false when no committed state exists.
func (x *DecommissionMachine) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(x.durableView(), step)
}

// DecommissionMachineDefinition is the unbound pipeline definition.
type DecommissionMachineDefinition struct {
	def *durable.Definition
}

// NewDecommissionMachine assembles the "decommission-machine" pipeline definition
// from its step handlers.
func NewDecommissionMachine(
	releaseMachine ReleaseMachineHandler,
) *DecommissionMachineDefinition {
	return &DecommissionMachineDefinition{def: durable.NewDefinition(durable.DefinitionConfig{
		ID:             "decommission-machine",
		ExclusionGroup: "machine-lifecycle",
		Steps: []durable.StepConfig{
			{
				ID: "release-machine/v1",
				Run: func(ctx context.Context, core *durable.Invocation) (proto.Message, error) {
					return nil, releaseMachine.Run(ctx, ReleaseMachineInvocation{core: core})
				},
			},
		},
	})}
}

// Bind registers the definition with an engine. It is allowed only before
// Engine.Start.
func (d *DecommissionMachineDefinition) Bind(e *durable.Engine) (*DecommissionMachinePipeline, error) {
	p, err := d.def.Bind(e)
	if err != nil {
		return nil, err
	}
	return &DecommissionMachinePipeline{pipeline: p}, nil
}

// DecommissionMachinePipeline is the definition bound to an engine.
type DecommissionMachinePipeline struct {
	pipeline *durable.Pipeline
}

// Schedule creates a run for the resource slot or returns the active one.
func (p *DecommissionMachinePipeline) Schedule(ctx context.Context, resource durable.ResourceID, opts ...durable.ScheduleOption) (durable.Run, bool, error) {
	run, created, err := p.pipeline.Schedule(ctx, resource, nil, opts...)
	return run, created, err
}

// Run returns a handle to an existing run of this pipeline.
func (p *DecommissionMachinePipeline) Run(ctx context.Context, id durable.RunID) (durable.Run, error) {
	run, err := p.pipeline.Run(ctx, id)
	return run, err
}

// Active returns handles for this pipeline's nonterminal runs.
func (p *DecommissionMachinePipeline) Active(ctx context.Context) ([]durable.Run, error) {
	runs, err := p.pipeline.Active(ctx)
	return runs, err
}

// Runs returns handles for all runs of this pipeline against a resource,
// oldest first.
func (p *DecommissionMachinePipeline) Runs(ctx context.Context, resource durable.ResourceID) ([]durable.Run, error) {
	runs, err := p.pipeline.Runs(ctx, resource)
	return runs, err
}
