// The provision-machine example pipeline from the durable specification.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: machines/v1/machines.proto

package machinespb

import (
	_ "github.com/dangra/durable/durablepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProvisionMachineInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	MemoryMb      uint64                 `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Cpus          uint32                 `protobuf:"varint,3,opt,name=cpus,proto3" json:"cpus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionMachineInput) Reset() {
	*x = ProvisionMachineInput{}
	mi := &file_machines_v1_machines_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionMachineInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionMachineInput) ProtoMessage() {}

func (x *ProvisionMachineInput) ProtoReflect() protoreflect.Message {
	mi := &file_machines_v1_machines_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionMachineInput.ProtoReflect.Descriptor instead.
func (*ProvisionMachineInput) Descriptor() ([]byte, []int) {
	return file_machines_v1_machines_proto_rawDescGZIP(), []int{0}
}

func (x *ProvisionMachineInput) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ProvisionMachineInput) GetMemoryMb() uint64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *ProvisionMachineInput) GetCpus() uint32 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

type ProvisionMachineOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionMachineOutput) Reset() {
	*x = ProvisionMachineOutput{}
	mi := &file_machines_v1_machines_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionMachineOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionMachineOutput) ProtoMessage() {}

func (x *ProvisionMachineOutput) ProtoReflect() protoreflect.Message {
	mi := &file_machines_v1_machines_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionMachineOutput.ProtoReflect.Descriptor instead.
func (*ProvisionMachineOutput) Descriptor() ([]byte, []int) {
	return file_machines_v1_machines_proto_rawDescGZIP(), []int{1}
}

func (x *ProvisionMachineOutput) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *ProvisionMachineOutput) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type ProvisionMachine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionMachine) Reset() {
	*x = ProvisionMachine{}
	mi := &file_machines_v1_machines_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionMachine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionMachine) ProtoMessage() {}

func (x *ProvisionMachine) ProtoReflect() protoreflect.Message {
	mi := &file_machines_v1_machines_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionMachine.ProtoReflect.Descriptor instead.
func (*ProvisionMachine) Descriptor() ([]byte, []int) {
	return file_machines_v1_machines_proto_rawDescGZIP(), []int{2}
}

// DecommissionMachine shares the machine-lifecycle mutex with
// ProvisionMachine: at most one of the two may have a nonterminal run per
// machine.
type DecommissionMachine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecommissionMachine) Reset() {
	*x = DecommissionMachine{}
	mi := &file_machines_v1_machines_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecommissionMachine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecommissionMachine) ProtoMessage() {}

func (x *DecommissionMachine) ProtoReflect() protoreflect.Message {
	mi := &file_machines_v1_machines_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecommissionMachine.ProtoReflect.Descriptor instead.
func (*DecommissionMachine) Descriptor() ([]byte, []int) {
	return file_machines_v1_machines_proto_rawDescGZIP(), []int{3}
}

type ProvisionMachine_Validate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionMachine_Validate) Reset() {
	*x = ProvisionMachine_Validate{}
	mi := &file_machines_v1_machines_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionMachine_Validate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionMachine_Validate) ProtoMessage() {}

func (x *ProvisionMachine_Validate) ProtoReflect() protoreflect.Message {
	mi := &file_machines_v1_machines_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionMachine_Validate.ProtoReflect.Descriptor instead.
func (*ProvisionMachine_Validate) Descriptor() ([]byte, []int) {
	return file_machines_v1_machines_proto_rawDescGZIP(), []int{2, 0}
}

type ProvisionMachine_SelectHost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionMachine_SelectHost) Reset() {
	*x = ProvisionMachine_SelectHost{}
	mi := &file_machines_v1_machines_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionMachine_SelectHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionMachine_SelectHost) ProtoMessage() {}

func (x *ProvisionMachine_SelectHost) ProtoReflect() protoreflect.Message {
	mi := &file_machines_v1_machines_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionMachine_SelectHost.ProtoReflect.Descriptor instead.
func (*ProvisionMachine_SelectHost) Descriptor() ([]byte, []int) {
	return file_machines_v1_machines_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ProvisionMachine_SelectHost) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type ProvisionMachine_ReserveCapacity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionMachine_ReserveCapacity) Reset() {
	*x = ProvisionMachine_ReserveCapacity{}
	mi := &file_machines_v1_machines_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionMachine_ReserveCapacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionMachine_ReserveCapacity) ProtoMessage() {}

func (x *ProvisionMachine_ReserveCapacity) ProtoReflect() protoreflect.Message {
	mi := &file_machines_v1_machines_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionMachine_ReserveCapacity.ProtoReflect.Descriptor instead.
func (*ProvisionMachine_ReserveCapacity) Descriptor() ([]byte, []int) {
	return file_machines_v1_machines_proto_rawDescGZIP(), []int{2, 2}
}

func (x *ProvisionMachine_ReserveCapacity) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type ProvisionMachine_CreateMachine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionMachine_CreateMachine) Reset() {
	*x = ProvisionMachine_CreateMachine{}
	mi := &file_machines_v1_machines_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionMachine_CreateMachine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionMachine_CreateMachine) ProtoMessage() {}

func (x *ProvisionMachine_CreateMachine) ProtoReflect() protoreflect.Message {
	mi := &file_machines_v1_machines_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionMachine_CreateMachine.ProtoReflect.Descriptor instead.
func (*ProvisionMachine_CreateMachine) Descriptor() ([]byte, []int) {
	return file_machines_v1_machines_proto_rawDescGZIP(), []int{2, 3}
}

func (x *ProvisionMachine_CreateMachine) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

type DecommissionMachine_ReleaseMachine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecommissionMachine_ReleaseMachine) Reset() {
	*x = DecommissionMachine_ReleaseMachine{}
	mi := &file_machines_v1_machines_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecommissionMachine_ReleaseMachine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecommissionMachine_ReleaseMachine) ProtoMessage() {}

func (x *DecommissionMachine_ReleaseMachine) ProtoReflect() protoreflect.Message {
	mi := &file_machines_v1_machines_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecommissionMachine_ReleaseMachine.ProtoReflect.Descriptor instead.
func (*DecommissionMachine_ReleaseMachine) Descriptor() ([]byte, []int) {
	return file_machines_v1_machines_proto_rawDescGZIP(), []int{3, 0}
}

var File_machines_v1_machines_proto protoreflect.FileDescriptor

const file_machines_v1_machines_proto_rawDesc = "" +
	"\n" +
	"\x1amachines/v1/machines.proto\x12\vmachines.v1\x1a\x18durable/v1/options.proto\"`\n" +
	"\x15ProvisionMachineInput\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\x04R\bmemoryMb\x12\x12\n" +
	"\x04cpus\x18\x03 \x01(\rR\x04cpus\"P\n" +
	"\x16ProvisionMachineOutput\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\"\x96\x03\n" +
	"\x10ProvisionMachine\x1a\x1d\n" +
	"\bValidate:\x11\x8a\xa8\x19\r\n" +
	"\vvalidate/v1\x1a;\n" +
	"\n" +
	"SelectHost\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId:\x14\x8a\xa8\x19\x10\n" +
	"\x0eselect-host/v1\x1ah\n" +
	"\x0fReserveCapacity\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId:.\x8a\xa8\x19*\n" +
	"\x13reserve-capacity/v1\x10\x01\"\x11host-capacity-api\x1aG\n" +
	"\rCreateMachine\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId:\x17\x8a\xa8\x19\x13\n" +
	"\x11create-machine/v1:s\x92\xa8\x19o\n" +
	"\x11provision-machine\x12\".machines.v1.ProvisionMachineInput\x1a#.machines.v1.ProvisionMachineOutput:\x11machine-lifecycle\"p\n" +
	"\x13DecommissionMachine\x1a*\n" +
	"\x0eReleaseMachine:\x18\x8a\xa8\x19\x14\n" +
	"\x12release-machine/v1:-\x92\xa8\x19)\n" +
	"\x14decommission-machine:\x11machine-lifecycleBCZAgithub.com/dangra/durable/examples/machines/machinespb;machinespbb\x06proto3"

var (
	file_machines_v1_machines_proto_rawDescOnce sync.Once
	file_machines_v1_machines_proto_rawDescData []byte
)

func file_machines_v1_machines_proto_rawDescGZIP() []byte {
	file_machines_v1_machines_proto_rawDescOnce.Do(func() {
		file_machines_v1_machines_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_machines_v1_machines_proto_rawDesc), len(file_machines_v1_machines_proto_rawDesc)))
	})
	return file_machines_v1_machines_proto_rawDescData
}

var file_machines_v1_machines_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_machines_v1_machines_proto_goTypes = []any{
	(*ProvisionMachineInput)(nil),              // 0: machines.v1.ProvisionMachineInput
	(*ProvisionMachineOutput)(nil),             // 1: machines.v1.ProvisionMachineOutput
	(*ProvisionMachine)(nil),                   // 2: machines.v1.ProvisionMachine
	(*DecommissionMachine)(nil),                // 3: machines.v1.DecommissionMachine
	(*ProvisionMachine_Validate)(nil),          // 4: machines.v1.ProvisionMachine.Validate
	(*ProvisionMachine_SelectHost)(nil),        // 5: machines.v1.ProvisionMachine.SelectHost
	(*ProvisionMachine_ReserveCapacity)(nil),   // 6: machines.v1.ProvisionMachine.ReserveCapacity
	(*ProvisionMachine_CreateMachine)(nil),     // 7: machines.v1.ProvisionMachine.CreateMachine
	(*DecommissionMachine_ReleaseMachine)(nil), // 8: machines.v1.DecommissionMachine.ReleaseMachine
}
var file_machines_v1_machines_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_machines_v1_machines_proto_init() }
func file_machines_v1_machines_proto_init() {
	if File_machines_v1_machines_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_machines_v1_machines_proto_rawDesc), len(file_machines_v1_machines_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_machines_v1_machines_proto_goTypes,
		DependencyIndexes: file_machines_v1_machines_proto_depIdxs,
		MessageInfos:      file_machines_v1_machines_proto_msgTypes,
	}.Build()
	File_machines_v1_machines_proto = out.File
	file_machines_v1_machines_proto_goTypes = nil
	file_machines_v1_machines_proto_depIdxs = nil
}
