// Code generated by protoc-gen-durable. DO NOT EDIT.
//
// source: machines/v1/machines.proto
// pipeline: provision-machine
// pipeline: decommission-machine

package machinespb

import (
	context "context"
	durable "github.com/dangra/durable"
	engine "github.com/dangra/durable/engine"
	pipelinedef "github.com/dangra/durable/pipelinedef"
	proto "google.golang.org/protobuf/proto"
	sync "sync"
)

// ValidateStep is the reference to the stateless step "validate/v1".
// It is not accepted by State lookup.
var ValidateStep = pipelinedef.StepRef("validate/v1")

// SelectHostStep is the typed reference to the state-producing step "select-host/v1".
var SelectHostStep = pipelinedef.StateStepRef("select-host/v1", func() *SelectHost { return &SelectHost{} })

// ReserveCapacityStep is the typed reference to the state-producing step "reserve-capacity/v1".
var ReserveCapacityStep = pipelinedef.StateStepRef("reserve-capacity/v1", func() *ReserveCapacity { return &ReserveCapacity{} })

// CreateMachineStep is the typed reference to the state-producing step "create-machine/v1".
var CreateMachineStep = pipelinedef.StateStepRef("create-machine/v1", func() *CreateMachine { return &CreateMachine{} })

// ProvisionMachineInvocation is the invocation every ProvisionMachineHandlers method receives:
// durable.Invocation with the pipeline's Input typed.
type ProvisionMachineInvocation = durable.TypedInvocation[*ProvisionMachineInput]

// NewProvisionMachineInvocation wraps core for calling a ProvisionMachineHandlers method directly,
// outside an engine: hand it durabletest.NewInvocation to unit-test a
// handler. The engine wraps its own invocations; application code never
// needs this at runtime.
func NewProvisionMachineInvocation(core durable.Invocation) ProvisionMachineInvocation {
	return durable.Typed[*ProvisionMachineInput](core)
}

// ProvisionMachineHandlers implements the "provision-machine" pipeline: one method per
// step, named after the step, plus Unwind<Step> for each step that
// unwinds. A type implements every step or does not compile; a step
// added to the pipeline is a method the next build demands.
type ProvisionMachineHandlers interface {
	// Validate runs step "validate/v1".
	Validate(ctx context.Context, inv ProvisionMachineInvocation) error
	// SelectHost runs step "select-host/v1".
	SelectHost(ctx context.Context, inv ProvisionMachineInvocation) (*SelectHost, error)
	// ReserveCapacity runs step "reserve-capacity/v1".
	ReserveCapacity(ctx context.Context, inv ProvisionMachineInvocation) (*ReserveCapacity, error)
	// UnwindReserveCapacity compensates step "reserve-capacity/v1" once it
	// succeeded and the run unwinds.
	UnwindReserveCapacity(ctx context.Context, inv ProvisionMachineInvocation) error
	// CreateMachine runs step "create-machine/v1".
	CreateMachine(ctx context.Context, inv ProvisionMachineInvocation) (*CreateMachine, error)
	// Reduce produces the pipeline output from the immutable input and
	// committed step states on success. It must be pure: deterministic,
	// side-effect free, synchronous, and non-failing.
	Reduce(*ProvisionMachine) *ProvisionMachineOutput
}

// ReduceProvisionMachine folds view through h.Reduce: the marker the reducer
// receives reads its Input, States, and failures from view for the
// duration of the call.
func ReduceProvisionMachine(h ProvisionMachineHandlers, view durable.ReduceView) *ProvisionMachineOutput {
	x := &ProvisionMachine{}
	provisionMachineViews.Store(x, view)
	defer provisionMachineViews.Delete(x)
	return h.Reduce(x)
}

var provisionMachineViews sync.Map

func (x *ProvisionMachine) durableView() durable.ReduceView {
	v, ok := provisionMachineViews.Load(x)
	if !ok {
		panic("machinespb: ProvisionMachine is only usable as a reducer view during reduction")
	}
	return v.(durable.ReduceView)
}

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (x *ProvisionMachine) Input() *ProvisionMachineInput {
	msg, _ := x.durableView().InputMessage().(*ProvisionMachineInput)
	return msg
}

// State returns the committed state of the referenced step for the run
// being reduced. ok is false when no committed state exists.
func (x *ProvisionMachine) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(x.durableView(), step)
}

// Failure is the run's failure when a failed run is being reduced, nil
// when a successful one is.
func (x *ProvisionMachine) Failure() *durable.Failure { return x.durableView().Failure() }

// UnwindFailure reports the permanent failure of the referenced step's
// unwind, if its compensation failed; ok is false when the step was not
// unwound or its unwind succeeded. Pair it with State to describe what a
// failed run left behind.
func (x *ProvisionMachine) UnwindFailure(step durable.StepIdentifier) (durable.Failure, bool) {
	return x.durableView().UnwindFailure(step.ID())
}

// ProvisionMachineDefinition is the unbound pipeline definition.
type ProvisionMachineDefinition struct {
	def *pipelinedef.Definition
}

// NewProvisionMachine assembles the "provision-machine" pipeline definition
// from its handlers.
func NewProvisionMachine(h ProvisionMachineHandlers) *ProvisionMachineDefinition {
	return &ProvisionMachineDefinition{def: pipelinedef.New(pipelinedef.Config{
		ID:       "provision-machine",
		Mutexes:  []string{"machine-lifecycle"},
		NewInput: func() proto.Message { return &ProvisionMachineInput{} },
		Reduce: func(view durable.ReduceView) proto.Message {
			return ReduceProvisionMachine(h, view)
		},
		Steps: []pipelinedef.Step{
			{
				ID: "validate/v1",
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					return nil, h.Validate(ctx, durable.Typed[*ProvisionMachineInput](core))
				},
			},
			{
				ID:       "select-host/v1",
				HasState: true,
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					state, err := h.SelectHost(ctx, durable.Typed[*ProvisionMachineInput](core))
					if state == nil {
						return nil, err
					}
					return state, err
				},
			},
			{
				ID:               "reserve-capacity/v1",
				Unwind:           true,
				ConcurrencyClass: "host-capacity-api",
				HasState:         true,
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					state, err := h.ReserveCapacity(ctx, durable.Typed[*ProvisionMachineInput](core))
					if state == nil {
						return nil, err
					}
					return state, err
				},
				UnwindFunc: func(ctx context.Context, core durable.Invocation) error {
					return h.UnwindReserveCapacity(ctx, durable.Typed[*ProvisionMachineInput](core))
				},
			},
			{
				ID:       "create-machine/v1",
				HasState: true,
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					state, err := h.CreateMachine(ctx, durable.Typed[*ProvisionMachineInput](core))
					if state == nil {
						return nil, err
					}
					return state, err
				},
			},
		},
	})}
}

// Bind registers the definition with an engine. It is allowed only before
// Engine.Start.
func (d *ProvisionMachineDefinition) Bind(e *engine.Engine) (*ProvisionMachinePipeline, error) {
	p, err := e.Bind(d.def)
	if err != nil {
		return nil, err
	}
	return &ProvisionMachinePipeline{pipeline: p}, nil
}

// ProvisionMachinePipeline is the definition bound to an engine.
type ProvisionMachinePipeline struct {
	pipeline *engine.Pipeline
}

// Schedule creates a run for the resource slot or returns the active one.
func (p *ProvisionMachinePipeline) Schedule(ctx context.Context, resource durable.ResourceID, input *ProvisionMachineInput, opts ...durable.ScheduleOption) (ProvisionMachineRun, bool, error) {
	run, created, err := p.pipeline.Schedule(ctx, resource, input, opts...)
	if err != nil {
		return ProvisionMachineRun{}, created, err
	}
	return ProvisionMachineRun{run: run}, created, nil
}

// GetRun returns a handle to an existing run of this pipeline.
func (p *ProvisionMachinePipeline) GetRun(ctx context.Context, id durable.RunID) (ProvisionMachineRun, error) {
	run, err := p.pipeline.GetRun(ctx, id)
	if err != nil {
		return ProvisionMachineRun{}, err
	}
	return ProvisionMachineRun{run: run}, nil
}

// GetActiveRun returns a handle to this pipeline's nonterminal run for a
// resource, if one exists — a read-only observation for wait/inspect
// flows; claiming the slot atomically remains Schedule's job.
func (p *ProvisionMachinePipeline) GetActiveRun(ctx context.Context, resource durable.ResourceID) (ProvisionMachineRun, bool, error) {
	run, ok, err := p.pipeline.GetActiveRun(ctx, resource)
	if err != nil || !ok {
		return ProvisionMachineRun{}, ok, err
	}
	return ProvisionMachineRun{run: run}, true, nil
}

// ProvisionMachineRun is a typed handle to one run of the pipeline.
type ProvisionMachineRun struct {
	run engine.Run
}

func (r ProvisionMachineRun) ID() durable.RunID { return r.run.ID() }

func (r ProvisionMachineRun) Status(ctx context.Context) (engine.Status, error) {
	return r.run.Status(ctx)
}

// Cancel durably requests cancellation: the run stops selecting new
// forward work and unwinds successfully executed steps.
func (r ProvisionMachineRun) Cancel(ctx context.Context, cause string) error {
	return r.run.Cancel(ctx, cause)
}

// Input returns a defensive caller-owned copy of the run's immutable
// pipeline input. The input is released when the run reaches its
// terminal outcome; Input on a terminal run returns durable.ErrRunTerminal.
func (r ProvisionMachineRun) Input(ctx context.Context) (*ProvisionMachineInput, error) {
	b, err := r.run.InputBytes(ctx)
	if err != nil {
		return nil, err
	}
	msg := &ProvisionMachineInput{}
	if err := proto.Unmarshal(b, msg); err != nil {
		return nil, err
	}
	return msg, nil
}

// Wait blocks until the run is terminal. A successful result carries the
// pipeline output and a failed one the failure output, each when the
// pipeline declares it.
func (r ProvisionMachineRun) Wait(ctx context.Context) (ProvisionMachineResult, error) {
	res, err := r.run.Wait(ctx)
	if err != nil {
		return ProvisionMachineResult{}, err
	}
	out := ProvisionMachineResult{Result: res}
	if res.Succeeded() {
		b, err := r.run.OutputBytes(ctx)
		if err != nil {
			return ProvisionMachineResult{}, err
		}
		msg := &ProvisionMachineOutput{}
		if err := proto.Unmarshal(b, msg); err != nil {
			return ProvisionMachineResult{}, err
		}
		out.output = msg
	}
	return out, nil
}

// ProvisionMachineResult is the typed terminal result of a run.
type ProvisionMachineResult struct {
	engine.Result
	output *ProvisionMachineOutput
}

// Output returns the pipeline output. It is non-nil exactly when the run
// succeeded.
func (r ProvisionMachineResult) Output() *ProvisionMachineOutput { return r.output }

// ReleaseMachineStep is the reference to the stateless step "release-machine/v1".
// It is not accepted by State lookup.
var ReleaseMachineStep = pipelinedef.StepRef("release-machine/v1")

// DecommissionMachineInvocation is the invocation every DecommissionMachineHandlers method receives:
// durable.Invocation with the pipeline's Input typed.
type DecommissionMachineInvocation = durable.TypedInvocation[durable.NoInput]

// NewDecommissionMachineInvocation wraps core for calling a DecommissionMachineHandlers method directly,
// outside an engine: hand it durabletest.NewInvocation to unit-test a
// handler. The engine wraps its own invocations; application code never
// needs this at runtime.
func NewDecommissionMachineInvocation(core durable.Invocation) DecommissionMachineInvocation {
	return durable.Typed[durable.NoInput](core)
}

// DecommissionMachineHandlers implements the "decommission-machine" pipeline: one method per
// step, named after the step, plus Unwind<Step> for each step that
// unwinds. A type implements every step or does not compile; a step
// added to the pipeline is a method the next build demands.
type DecommissionMachineHandlers interface {
	// ReleaseMachine runs step "release-machine/v1".
	ReleaseMachine(ctx context.Context, inv DecommissionMachineInvocation) error
}

var decommissionMachineViews sync.Map

func (x *DecommissionMachine) durableView() durable.ReduceView {
	v, ok := decommissionMachineViews.Load(x)
	if !ok {
		panic("machinespb: DecommissionMachine is only usable as a reducer view during reduction")
	}
	return v.(durable.ReduceView)
}

// State returns the committed state of the referenced step for the run
// being reduced. ok is false when no committed state exists.
func (x *DecommissionMachine) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(x.durableView(), step)
}

// Failure is the run's failure when a failed run is being reduced, nil
// when a successful one is.
func (x *DecommissionMachine) Failure() *durable.Failure { return x.durableView().Failure() }

// UnwindFailure reports the permanent failure of the referenced step's
// unwind, if its compensation failed; ok is false when the step was not
// unwound or its unwind succeeded. Pair it with State to describe what a
// failed run left behind.
func (x *DecommissionMachine) UnwindFailure(step durable.StepIdentifier) (durable.Failure, bool) {
	return x.durableView().UnwindFailure(step.ID())
}

// DecommissionMachineDefinition is the unbound pipeline definition.
type DecommissionMachineDefinition struct {
	def *pipelinedef.Definition
}

// NewDecommissionMachine assembles the "decommission-machine" pipeline definition
// from its handlers.
func NewDecommissionMachine(h DecommissionMachineHandlers) *DecommissionMachineDefinition {
	return &DecommissionMachineDefinition{def: pipelinedef.New(pipelinedef.Config{
		ID:      "decommission-machine",
		Mutexes: []string{"machine-lifecycle"},
		Steps: []pipelinedef.Step{
			{
				ID: "release-machine/v1",
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					return nil, h.ReleaseMachine(ctx, durable.Typed[durable.NoInput](core))
				},
			},
		},
	})}
}

// Bind registers the definition with an engine. It is allowed only before
// Engine.Start.
func (d *DecommissionMachineDefinition) Bind(e *engine.Engine) (*DecommissionMachinePipeline, error) {
	p, err := e.Bind(d.def)
	if err != nil {
		return nil, err
	}
	return &DecommissionMachinePipeline{pipeline: p}, nil
}

// DecommissionMachinePipeline is the definition bound to an engine.
type DecommissionMachinePipeline struct {
	pipeline *engine.Pipeline
}

// Schedule creates a run for the resource slot or returns the active one.
func (p *DecommissionMachinePipeline) Schedule(ctx context.Context, resource durable.ResourceID, opts ...durable.ScheduleOption) (engine.Run, bool, error) {
	run, created, err := p.pipeline.Schedule(ctx, resource, nil, opts...)
	return run, created, err
}

// GetRun returns a handle to an existing run of this pipeline.
func (p *DecommissionMachinePipeline) GetRun(ctx context.Context, id durable.RunID) (engine.Run, error) {
	run, err := p.pipeline.GetRun(ctx, id)
	return run, err
}

// GetActiveRun returns a handle to this pipeline's nonterminal run for a
// resource, if one exists — a read-only observation for wait/inspect
// flows; claiming the slot atomically remains Schedule's job.
func (p *DecommissionMachinePipeline) GetActiveRun(ctx context.Context, resource durable.ResourceID) (engine.Run, bool, error) {
	run, ok, err := p.pipeline.GetActiveRun(ctx, resource)
	return run, ok, err
}
