// Code generated by protoc-gen-durable. DO NOT EDIT.
//
// source: legacy/v1/legacy.proto
// pipeline: deploy-service

package legacypb

import (
	context "context"
	durable "github.com/dangra/durable"
	engine "github.com/dangra/durable/engine"
	proto "google.golang.org/protobuf/proto"
	sync "sync"
)

// ProvisionEnvStep is the typed reference to the state-producing step "provision-env/v1".
var ProvisionEnvStep = durable.NewStateStepRef("provision-env/v1", func() *ProvisionEnv { return &ProvisionEnv{} })

// RunMigrationsStep is the typed reference to the state-producing step "run-migrations/v1".
var RunMigrationsStep = durable.NewStateStepRef("run-migrations/v1", func() *RunMigrations { return &RunMigrations{} })

// ShiftTrafficStep is the typed reference to the state-producing step "shift-traffic/v1".
var ShiftTrafficStep = durable.NewStateStepRef("shift-traffic/v1", func() *ShiftTraffic { return &ShiftTraffic{} })

// ProvisionEnvInvocation is passed to ProvisionEnvHandler methods.
type ProvisionEnvInvocation struct {
	core durable.Invocation
}

func (inv ProvisionEnvInvocation) PipelineID() durable.PipelineID { return inv.core.PipelineID() }
func (inv ProvisionEnvInvocation) ResourceID() durable.ResourceID { return inv.core.ResourceID() }
func (inv ProvisionEnvInvocation) RunID() durable.RunID           { return inv.core.RunID() }
func (inv ProvisionEnvInvocation) StepID() durable.StepID         { return inv.core.StepID() }
func (inv ProvisionEnvInvocation) Attempt() uint64                { return inv.core.Attempt() }
func (inv ProvisionEnvInvocation) Phase() durable.Phase           { return inv.core.Phase() }

// CancelRequested reports whether a cancellation request was pending when
// this attempt was reserved.
func (inv ProvisionEnvInvocation) CancelRequested() bool { return inv.core.CancelRequested() }

// AwaitedRunID reports the run an earlier attempt of this operation parked
// on via durable.AwaitRun, once that park resolved. Multi-target parks
// are read through Awaited.
func (inv ProvisionEnvInvocation) AwaitedRunID() (durable.RunID, bool) {
	return inv.core.AwaitedRunID()
}

// Awaited reports the park an earlier attempt of this operation made, once
// it resolved; ok is false on a first execution.
func (inv ProvisionEnvInvocation) Awaited() (durable.Wake, bool) { return inv.core.Awaited() }

// Annotations returns a caller-owned copy of the run's immutable
// acceptance-time annotations (trace contexts, tenant tags).
func (inv ProvisionEnvInvocation) Annotations() map[string]string { return inv.core.Annotations() }

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (inv ProvisionEnvInvocation) Input() *DeployServiceInput {
	msg, _ := inv.core.InputMessage().(*DeployServiceInput)
	return msg
}

// State returns the committed state of the referenced step for this run.
// ok is false when no committed state exists.
func (inv ProvisionEnvInvocation) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(inv.core, step)
}

// ProvisionEnvHandler implements step "provision-env/v1".
type ProvisionEnvHandler interface {
	Run(context.Context, ProvisionEnvInvocation) (*ProvisionEnv, error)

	Unwind(context.Context, ProvisionEnvInvocation, durable.Failure) error
}

// ProvisionEnvFuncs adapts a pair of functions to ProvisionEnvHandler.
type ProvisionEnvFuncs struct {
	RunFunc    func(ctx context.Context, inv ProvisionEnvInvocation) (*ProvisionEnv, error)
	UnwindFunc func(context.Context, ProvisionEnvInvocation, durable.Failure) error
}

func (f ProvisionEnvFuncs) Run(ctx context.Context, inv ProvisionEnvInvocation) (*ProvisionEnv, error) {
	return f.RunFunc(ctx, inv)
}

func (f ProvisionEnvFuncs) Unwind(ctx context.Context, inv ProvisionEnvInvocation, failure durable.Failure) error {
	return f.UnwindFunc(ctx, inv, failure)
}

// RunMigrationsInvocation is passed to RunMigrationsHandler methods.
type RunMigrationsInvocation struct {
	core durable.Invocation
}

func (inv RunMigrationsInvocation) PipelineID() durable.PipelineID { return inv.core.PipelineID() }
func (inv RunMigrationsInvocation) ResourceID() durable.ResourceID { return inv.core.ResourceID() }
func (inv RunMigrationsInvocation) RunID() durable.RunID           { return inv.core.RunID() }
func (inv RunMigrationsInvocation) StepID() durable.StepID         { return inv.core.StepID() }
func (inv RunMigrationsInvocation) Attempt() uint64                { return inv.core.Attempt() }
func (inv RunMigrationsInvocation) Phase() durable.Phase           { return inv.core.Phase() }

// CancelRequested reports whether a cancellation request was pending when
// this attempt was reserved.
func (inv RunMigrationsInvocation) CancelRequested() bool { return inv.core.CancelRequested() }

// AwaitedRunID reports the run an earlier attempt of this operation parked
// on via durable.AwaitRun, once that park resolved. Multi-target parks
// are read through Awaited.
func (inv RunMigrationsInvocation) AwaitedRunID() (durable.RunID, bool) {
	return inv.core.AwaitedRunID()
}

// Awaited reports the park an earlier attempt of this operation made, once
// it resolved; ok is false on a first execution.
func (inv RunMigrationsInvocation) Awaited() (durable.Wake, bool) { return inv.core.Awaited() }

// Annotations returns a caller-owned copy of the run's immutable
// acceptance-time annotations (trace contexts, tenant tags).
func (inv RunMigrationsInvocation) Annotations() map[string]string { return inv.core.Annotations() }

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (inv RunMigrationsInvocation) Input() *DeployServiceInput {
	msg, _ := inv.core.InputMessage().(*DeployServiceInput)
	return msg
}

// State returns the committed state of the referenced step for this run.
// ok is false when no committed state exists.
func (inv RunMigrationsInvocation) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(inv.core, step)
}

// RunMigrationsHandler implements step "run-migrations/v1".
type RunMigrationsHandler interface {
	Run(context.Context, RunMigrationsInvocation) (*RunMigrations, error)

	Unwind(context.Context, RunMigrationsInvocation, durable.Failure) error
}

// RunMigrationsFuncs adapts a pair of functions to RunMigrationsHandler.
type RunMigrationsFuncs struct {
	RunFunc    func(ctx context.Context, inv RunMigrationsInvocation) (*RunMigrations, error)
	UnwindFunc func(context.Context, RunMigrationsInvocation, durable.Failure) error
}

func (f RunMigrationsFuncs) Run(ctx context.Context, inv RunMigrationsInvocation) (*RunMigrations, error) {
	return f.RunFunc(ctx, inv)
}

func (f RunMigrationsFuncs) Unwind(ctx context.Context, inv RunMigrationsInvocation, failure durable.Failure) error {
	return f.UnwindFunc(ctx, inv, failure)
}

// ShiftTrafficInvocation is passed to ShiftTrafficHandler methods.
type ShiftTrafficInvocation struct {
	core durable.Invocation
}

func (inv ShiftTrafficInvocation) PipelineID() durable.PipelineID { return inv.core.PipelineID() }
func (inv ShiftTrafficInvocation) ResourceID() durable.ResourceID { return inv.core.ResourceID() }
func (inv ShiftTrafficInvocation) RunID() durable.RunID           { return inv.core.RunID() }
func (inv ShiftTrafficInvocation) StepID() durable.StepID         { return inv.core.StepID() }
func (inv ShiftTrafficInvocation) Attempt() uint64                { return inv.core.Attempt() }
func (inv ShiftTrafficInvocation) Phase() durable.Phase           { return inv.core.Phase() }

// CancelRequested reports whether a cancellation request was pending when
// this attempt was reserved.
func (inv ShiftTrafficInvocation) CancelRequested() bool { return inv.core.CancelRequested() }

// AwaitedRunID reports the run an earlier attempt of this operation parked
// on via durable.AwaitRun, once that park resolved. Multi-target parks
// are read through Awaited.
func (inv ShiftTrafficInvocation) AwaitedRunID() (durable.RunID, bool) {
	return inv.core.AwaitedRunID()
}

// Awaited reports the park an earlier attempt of this operation made, once
// it resolved; ok is false on a first execution.
func (inv ShiftTrafficInvocation) Awaited() (durable.Wake, bool) { return inv.core.Awaited() }

// Annotations returns a caller-owned copy of the run's immutable
// acceptance-time annotations (trace contexts, tenant tags).
func (inv ShiftTrafficInvocation) Annotations() map[string]string { return inv.core.Annotations() }

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (inv ShiftTrafficInvocation) Input() *DeployServiceInput {
	msg, _ := inv.core.InputMessage().(*DeployServiceInput)
	return msg
}

// State returns the committed state of the referenced step for this run.
// ok is false when no committed state exists.
func (inv ShiftTrafficInvocation) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(inv.core, step)
}

// ShiftTrafficHandler implements step "shift-traffic/v1".
type ShiftTrafficHandler interface {
	Run(context.Context, ShiftTrafficInvocation) (*ShiftTraffic, error)
}

// ShiftTrafficFunc adapts a function to ShiftTrafficHandler, in the style of
// http.HandlerFunc.
type ShiftTrafficFunc func(ctx context.Context, inv ShiftTrafficInvocation) (*ShiftTraffic, error)

func (f ShiftTrafficFunc) Run(ctx context.Context, inv ShiftTrafficInvocation) (*ShiftTraffic, error) {
	return f(ctx, inv)
}

// DeployServiceReducer produces the pipeline output from the immutable input
// and committed step states. It must be pure: deterministic, side-effect
// free, synchronous, and non-failing.
type DeployServiceReducer func(*DeployService) *DeployServiceOutput

var deployServiceViews sync.Map

func (x *DeployService) durableView() durable.ReduceView {
	v, ok := deployServiceViews.Load(x)
	if !ok {
		panic("legacypb: DeployService is only usable as a reducer view during reduction")
	}
	return v.(durable.ReduceView)
}

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (x *DeployService) Input() *DeployServiceInput {
	msg, _ := x.durableView().InputMessage().(*DeployServiceInput)
	return msg
}

// State returns the committed state of the referenced step for the run
// being reduced. ok is false when no committed state exists.
func (x *DeployService) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(x.durableView(), step)
}

// DeployServiceDefinition is the unbound pipeline definition.
type DeployServiceDefinition struct {
	def *engine.Definition
}

// NewDeployService assembles the "deploy-service" pipeline definition
// from its step handlers and reducer.
func NewDeployService(
	provisionEnv ProvisionEnvHandler,
	runMigrations RunMigrationsHandler,
	shiftTraffic ShiftTrafficHandler,
	reduce DeployServiceReducer,
) *DeployServiceDefinition {
	return &DeployServiceDefinition{def: engine.NewDefinition(engine.DefinitionConfig{
		ID:       "deploy-service",
		NewInput: func() proto.Message { return &DeployServiceInput{} },
		Reduce: func(view durable.ReduceView) proto.Message {
			x := &DeployService{}
			deployServiceViews.Store(x, view)
			defer deployServiceViews.Delete(x)
			return reduce(x)
		},
		Steps: []engine.StepConfig{
			{
				ID:       "provision-env/v1",
				Unwind:   true,
				HasState: true,
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					state, err := provisionEnv.Run(ctx, ProvisionEnvInvocation{core: core})
					if state == nil {
						return nil, err
					}
					return state, err
				},
				UnwindFunc: func(ctx context.Context, core durable.Invocation, failure durable.Failure) error {
					return provisionEnv.Unwind(ctx, ProvisionEnvInvocation{core: core}, failure)
				},
			},
			{
				ID:       "run-migrations/v1",
				Unwind:   true,
				HasState: true,
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					state, err := runMigrations.Run(ctx, RunMigrationsInvocation{core: core})
					if state == nil {
						return nil, err
					}
					return state, err
				},
				UnwindFunc: func(ctx context.Context, core durable.Invocation, failure durable.Failure) error {
					return runMigrations.Unwind(ctx, RunMigrationsInvocation{core: core}, failure)
				},
			},
			{
				ID:       "shift-traffic/v1",
				HasState: true,
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					state, err := shiftTraffic.Run(ctx, ShiftTrafficInvocation{core: core})
					if state == nil {
						return nil, err
					}
					return state, err
				},
			},
		},
	})}
}

// Bind registers the definition with an engine. It is allowed only before
// Engine.Start.
func (d *DeployServiceDefinition) Bind(e *engine.Engine) (*DeployServicePipeline, error) {
	p, err := d.def.Bind(e)
	if err != nil {
		return nil, err
	}
	return &DeployServicePipeline{pipeline: p}, nil
}

// DeployServicePipeline is the definition bound to an engine.
type DeployServicePipeline struct {
	pipeline *engine.Pipeline
}

// Schedule creates a run for the resource slot or returns the active one.
func (p *DeployServicePipeline) Schedule(ctx context.Context, resource durable.ResourceID, input *DeployServiceInput, opts ...engine.ScheduleOption) (DeployServiceRun, bool, error) {
	run, created, err := p.pipeline.Schedule(ctx, resource, input, opts...)
	if err != nil {
		return DeployServiceRun{}, created, err
	}
	return DeployServiceRun{run: run}, created, nil
}

// Run returns a handle to an existing run of this pipeline.
func (p *DeployServicePipeline) Run(ctx context.Context, id durable.RunID) (DeployServiceRun, error) {
	run, err := p.pipeline.Run(ctx, id)
	if err != nil {
		return DeployServiceRun{}, err
	}
	return DeployServiceRun{run: run}, nil
}

// ActiveRun returns a handle to this pipeline's nonterminal run for a
// resource, if one exists — a read-only observation for wait/inspect
// flows; claiming the slot atomically remains Schedule's job.
func (p *DeployServicePipeline) ActiveRun(ctx context.Context, resource durable.ResourceID) (DeployServiceRun, bool, error) {
	run, ok, err := p.pipeline.ActiveRun(ctx, resource)
	if err != nil || !ok {
		return DeployServiceRun{}, ok, err
	}
	return DeployServiceRun{run: run}, true, nil
}

// Active returns handles for this pipeline's nonterminal runs.
func (p *DeployServicePipeline) Active(ctx context.Context) ([]DeployServiceRun, error) {
	runs, err := p.pipeline.Active(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]DeployServiceRun, 0, len(runs))
	for _, run := range runs {
		out = append(out, DeployServiceRun{run: run})
	}
	return out, nil
}

// Runs returns handles for all runs of this pipeline against a resource,
// oldest first.
func (p *DeployServicePipeline) Runs(ctx context.Context, resource durable.ResourceID) ([]DeployServiceRun, error) {
	runs, err := p.pipeline.Runs(ctx, resource)
	if err != nil {
		return nil, err
	}
	out := make([]DeployServiceRun, 0, len(runs))
	for _, run := range runs {
		out = append(out, DeployServiceRun{run: run})
	}
	return out, nil
}

// DeployServiceRun is a typed handle to one run of the pipeline.
type DeployServiceRun struct {
	run engine.Run
}

func (r DeployServiceRun) ID() durable.RunID { return r.run.ID() }

func (r DeployServiceRun) Status(ctx context.Context) (engine.Status, error) {
	return r.run.Status(ctx)
}

// Cancel durably requests cancellation: the run stops selecting new
// forward work and unwinds successfully executed steps.
func (r DeployServiceRun) Cancel(ctx context.Context, cause string) error {
	return r.run.Cancel(ctx, cause)
}

// Input returns a defensive caller-owned copy of the run's immutable
// pipeline input.
func (r DeployServiceRun) Input(ctx context.Context) (*DeployServiceInput, error) {
	b, err := r.run.InputBytes(ctx)
	if err != nil {
		return nil, err
	}
	msg := &DeployServiceInput{}
	if err := proto.Unmarshal(b, msg); err != nil {
		return nil, err
	}
	return msg, nil
}

// Wait blocks until the run is terminal. A successful result carries the
// pipeline output; a failed run has none.
func (r DeployServiceRun) Wait(ctx context.Context) (DeployServiceResult, error) {
	res, err := r.run.Wait(ctx)
	if err != nil {
		return DeployServiceResult{}, err
	}
	out := DeployServiceResult{Result: res}
	if res.Succeeded() {
		b, err := r.run.OutputBytes(ctx)
		if err != nil {
			return DeployServiceResult{}, err
		}
		msg := &DeployServiceOutput{}
		if err := proto.Unmarshal(b, msg); err != nil {
			return DeployServiceResult{}, err
		}
		out.output = msg
	}
	return out, nil
}

// DeployServiceResult is the typed terminal result of a run.
type DeployServiceResult struct {
	engine.Result
	output *DeployServiceOutput
}

// Output returns the pipeline output. It is non-nil exactly when the run
// succeeded.
func (r DeployServiceResult) Output() *DeployServiceOutput { return r.output }
