// Code generated by protoc-gen-durable. DO NOT EDIT.
//
// source: legacy/v1/legacy.proto
// pipeline: deploy-service

package legacypb

import (
	context "context"
	durable "github.com/dangra/durable"
	engine "github.com/dangra/durable/engine"
	pipelinedef "github.com/dangra/durable/pipelinedef"
	proto "google.golang.org/protobuf/proto"
	sync "sync"
)

// DeployService_ProvisionEnvStep is the typed reference to the state-producing step "provision-env/v1".
var DeployService_ProvisionEnvStep = pipelinedef.StateStepRef("provision-env/v1", func() *DeployService_ProvisionEnv { return &DeployService_ProvisionEnv{} })

// DeployService_RunMigrationsStep is the typed reference to the state-producing step "run-migrations/v1".
var DeployService_RunMigrationsStep = pipelinedef.StateStepRef("run-migrations/v1", func() *DeployService_RunMigrations { return &DeployService_RunMigrations{} })

// DeployService_ShiftTrafficStep is the typed reference to the state-producing step "shift-traffic/v1".
var DeployService_ShiftTrafficStep = pipelinedef.StateStepRef("shift-traffic/v1", func() *DeployService_ShiftTraffic { return &DeployService_ShiftTraffic{} })

// DeployServiceInvocation is the invocation every DeployServiceHandlers method receives:
// durable.Invocation with the pipeline's Input typed.
type DeployServiceInvocation = durable.TypedInvocation[*DeployServiceInput]

// NewDeployServiceInvocation wraps core for calling a DeployServiceHandlers method directly,
// outside an engine: hand it durabletest.NewInvocation to unit-test a
// handler. The engine wraps its own invocations; application code never
// needs this at runtime.
func NewDeployServiceInvocation(core durable.Invocation) DeployServiceInvocation {
	return durable.Typed[*DeployServiceInput](core)
}

// DeployServiceHandlers implements the "deploy-service" pipeline: one method per
// step, named after the step, plus Unwind<Step> for each step that
// unwinds. A type implements every step or does not compile; a step
// added to the pipeline is a method the next build demands.
type DeployServiceHandlers interface {
	// ProvisionEnv runs step "provision-env/v1".
	ProvisionEnv(ctx context.Context, inv DeployServiceInvocation) (*DeployService_ProvisionEnv, error)
	// UnwindProvisionEnv compensates step "provision-env/v1" once it
	// succeeded and the run unwinds.
	UnwindProvisionEnv(ctx context.Context, inv DeployServiceInvocation) error
	// RunMigrations runs step "run-migrations/v1".
	RunMigrations(ctx context.Context, inv DeployServiceInvocation) (*DeployService_RunMigrations, error)
	// UnwindRunMigrations compensates step "run-migrations/v1" once it
	// succeeded and the run unwinds.
	UnwindRunMigrations(ctx context.Context, inv DeployServiceInvocation) error
	// ShiftTraffic runs step "shift-traffic/v1".
	ShiftTraffic(ctx context.Context, inv DeployServiceInvocation) (*DeployService_ShiftTraffic, error)
	// Reduce produces the pipeline output from the immutable input and
	// committed step states on success. It must be pure: deterministic,
	// side-effect free, synchronous, and non-failing.
	Reduce(*DeployService) *DeployServiceOutput
}

// ReduceDeployService folds view through h.Reduce: the marker the reducer
// receives reads its Input, States, and failures from view for the
// duration of the call.
func ReduceDeployService(h DeployServiceHandlers, view durable.ReduceView) *DeployServiceOutput {
	x := &DeployService{}
	deployServiceViews.Store(x, view)
	defer deployServiceViews.Delete(x)
	return h.Reduce(x)
}

var deployServiceViews sync.Map

func (x *DeployService) durableView() durable.ReduceView {
	v, ok := deployServiceViews.Load(x)
	if !ok {
		panic("legacypb: DeployService is only usable as a reducer view during reduction")
	}
	return v.(durable.ReduceView)
}

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (x *DeployService) Input() *DeployServiceInput {
	msg, _ := x.durableView().InputMessage().(*DeployServiceInput)
	return msg
}

// State returns the committed state of the referenced step for the run
// being reduced. ok is false when no committed state exists.
func (x *DeployService) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(x.durableView(), step)
}

// Failure is the run's failure when a failed run is being reduced, nil
// when a successful one is.
func (x *DeployService) Failure() *durable.Failure { return x.durableView().Failure() }

// UnwindFailure reports the permanent failure of the referenced step's
// unwind, if its compensation failed; ok is false when the step was not
// unwound or its unwind succeeded. Pair it with State to describe what a
// failed run left behind.
func (x *DeployService) UnwindFailure(step durable.StepIdentifier) (durable.Failure, bool) {
	return x.durableView().UnwindFailure(step.ID())
}

// DeployServiceDefinition is the unbound pipeline definition.
type DeployServiceDefinition struct {
	def *pipelinedef.Definition
}

// NewDeployService assembles the "deploy-service" pipeline definition
// from its handlers.
func NewDeployService(h DeployServiceHandlers) *DeployServiceDefinition {
	return &DeployServiceDefinition{def: pipelinedef.New(pipelinedef.Config{
		ID:       "deploy-service",
		NewInput: func() proto.Message { return &DeployServiceInput{} },
		Reduce: func(view durable.ReduceView) proto.Message {
			return ReduceDeployService(h, view)
		},
		Steps: []pipelinedef.Step{
			{
				ID:       "provision-env/v1",
				Unwind:   true,
				HasState: true,
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					state, err := h.ProvisionEnv(ctx, durable.Typed[*DeployServiceInput](core))
					if state == nil {
						return nil, err
					}
					return state, err
				},
				UnwindFunc: func(ctx context.Context, core durable.Invocation) error {
					return h.UnwindProvisionEnv(ctx, durable.Typed[*DeployServiceInput](core))
				},
			},
			{
				ID:       "run-migrations/v1",
				Unwind:   true,
				HasState: true,
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					state, err := h.RunMigrations(ctx, durable.Typed[*DeployServiceInput](core))
					if state == nil {
						return nil, err
					}
					return state, err
				},
				UnwindFunc: func(ctx context.Context, core durable.Invocation) error {
					return h.UnwindRunMigrations(ctx, durable.Typed[*DeployServiceInput](core))
				},
			},
			{
				ID:       "shift-traffic/v1",
				HasState: true,
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					state, err := h.ShiftTraffic(ctx, durable.Typed[*DeployServiceInput](core))
					if state == nil {
						return nil, err
					}
					return state, err
				},
			},
		},
	})}
}

// Bind registers the definition with an engine. It is allowed only before
// Engine.Start.
func (d *DeployServiceDefinition) Bind(e *engine.Engine) (*DeployServicePipeline, error) {
	p, err := e.Bind(d.def)
	if err != nil {
		return nil, err
	}
	return &DeployServicePipeline{pipeline: p}, nil
}

// DeployServicePipeline is the definition bound to an engine.
type DeployServicePipeline struct {
	pipeline *engine.Pipeline
}

// Schedule creates a run for the resource slot or returns the active one.
func (p *DeployServicePipeline) Schedule(ctx context.Context, resource durable.ResourceID, input *DeployServiceInput, opts ...durable.ScheduleOption) (DeployServiceRun, bool, error) {
	run, created, err := p.pipeline.Schedule(ctx, resource, input, opts...)
	if err != nil {
		return DeployServiceRun{}, created, err
	}
	return DeployServiceRun{run: run}, created, nil
}

// GetRun returns a handle to an existing run of this pipeline.
func (p *DeployServicePipeline) GetRun(ctx context.Context, id durable.RunID) (DeployServiceRun, error) {
	run, err := p.pipeline.GetRun(ctx, id)
	if err != nil {
		return DeployServiceRun{}, err
	}
	return DeployServiceRun{run: run}, nil
}

// GetActiveRun returns a handle to this pipeline's nonterminal run for a
// resource, if one exists — a read-only observation for wait/inspect
// flows; claiming the slot atomically remains Schedule's job.
func (p *DeployServicePipeline) GetActiveRun(ctx context.Context, resource durable.ResourceID) (DeployServiceRun, bool, error) {
	run, ok, err := p.pipeline.GetActiveRun(ctx, resource)
	if err != nil || !ok {
		return DeployServiceRun{}, ok, err
	}
	return DeployServiceRun{run: run}, true, nil
}

// DeployServiceRun is a typed handle to one run of the pipeline.
type DeployServiceRun struct {
	run engine.Run
}

func (r DeployServiceRun) ID() durable.RunID { return r.run.ID() }

func (r DeployServiceRun) Status(ctx context.Context) (engine.Status, error) {
	return r.run.Status(ctx)
}

// Cancel durably requests cancellation: the run stops selecting new
// forward work and unwinds successfully executed steps.
func (r DeployServiceRun) Cancel(ctx context.Context, cause string) error {
	return r.run.Cancel(ctx, cause)
}

// Input returns a defensive caller-owned copy of the run's immutable
// pipeline input. The input is released when the run reaches its
// terminal outcome; Input on a terminal run returns durable.ErrRunTerminal.
func (r DeployServiceRun) Input(ctx context.Context) (*DeployServiceInput, error) {
	b, err := r.run.InputBytes(ctx)
	if err != nil {
		return nil, err
	}
	msg := &DeployServiceInput{}
	if err := proto.Unmarshal(b, msg); err != nil {
		return nil, err
	}
	return msg, nil
}

// Wait blocks until the run is terminal. A successful result carries the
// pipeline output and a failed one the failure output, each when the
// pipeline declares it.
func (r DeployServiceRun) Wait(ctx context.Context) (DeployServiceResult, error) {
	res, err := r.run.Wait(ctx)
	if err != nil {
		return DeployServiceResult{}, err
	}
	out := DeployServiceResult{Result: res}
	if res.Succeeded() {
		b, err := r.run.OutputBytes(ctx)
		if err != nil {
			return DeployServiceResult{}, err
		}
		msg := &DeployServiceOutput{}
		if err := proto.Unmarshal(b, msg); err != nil {
			return DeployServiceResult{}, err
		}
		out.output = msg
	}
	return out, nil
}

// DeployServiceResult is the typed terminal result of a run.
type DeployServiceResult struct {
	engine.Result
	output *DeployServiceOutput
}

// Output returns the pipeline output. It is non-nil exactly when the run
// succeeded.
func (r DeployServiceResult) Output() *DeployServiceOutput { return r.output }
