// Today's build of the release platform: the deploy pipeline gained a
// canary-analysis step (compare legacyproto/, yesterday's build without
// it), and the release-train pipeline orchestrates per-service deploys.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: release/v1/release.proto

package releasepb

import (
	_ "github.com/dangra/durable/durablepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeployServiceInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployServiceInput) Reset() {
	*x = DeployServiceInput{}
	mi := &file_release_v1_release_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployServiceInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployServiceInput) ProtoMessage() {}

func (x *DeployServiceInput) ProtoReflect() protoreflect.Message {
	mi := &file_release_v1_release_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployServiceInput.ProtoReflect.Descriptor instead.
func (*DeployServiceInput) Descriptor() ([]byte, []int) {
	return file_release_v1_release_proto_rawDescGZIP(), []int{0}
}

func (x *DeployServiceInput) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *DeployServiceInput) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type DeployServiceOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployServiceOutput) Reset() {
	*x = DeployServiceOutput{}
	mi := &file_release_v1_release_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployServiceOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployServiceOutput) ProtoMessage() {}

func (x *DeployServiceOutput) ProtoReflect() protoreflect.Message {
	mi := &file_release_v1_release_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployServiceOutput.ProtoReflect.Descriptor instead.
func (*DeployServiceOutput) Descriptor() ([]byte, []int) {
	return file_release_v1_release_proto_rawDescGZIP(), []int{1}
}

func (x *DeployServiceOutput) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type DeployService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployService) Reset() {
	*x = DeployService{}
	mi := &file_release_v1_release_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployService) ProtoMessage() {}

func (x *DeployService) ProtoReflect() protoreflect.Message {
	mi := &file_release_v1_release_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployService.ProtoReflect.Descriptor instead.
func (*DeployService) Descriptor() ([]byte, []int) {
	return file_release_v1_release_proto_rawDescGZIP(), []int{2}
}

type ReleaseTrainInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageTag      string                 `protobuf:"bytes,1,opt,name=image_tag,json=imageTag,proto3" json:"image_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseTrainInput) Reset() {
	*x = ReleaseTrainInput{}
	mi := &file_release_v1_release_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseTrainInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseTrainInput) ProtoMessage() {}

func (x *ReleaseTrainInput) ProtoReflect() protoreflect.Message {
	mi := &file_release_v1_release_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseTrainInput.ProtoReflect.Descriptor instead.
func (*ReleaseTrainInput) Descriptor() ([]byte, []int) {
	return file_release_v1_release_proto_rawDescGZIP(), []int{3}
}

func (x *ReleaseTrainInput) GetImageTag() string {
	if x != nil {
		return x.ImageTag
	}
	return ""
}

type ReleaseTrain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseTrain) Reset() {
	*x = ReleaseTrain{}
	mi := &file_release_v1_release_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseTrain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseTrain) ProtoMessage() {}

func (x *ReleaseTrain) ProtoReflect() protoreflect.Message {
	mi := &file_release_v1_release_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseTrain.ProtoReflect.Descriptor instead.
func (*ReleaseTrain) Descriptor() ([]byte, []int) {
	return file_release_v1_release_proto_rawDescGZIP(), []int{4}
}

type DeployService_ProvisionEnv struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvId         string                 `protobuf:"bytes,1,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployService_ProvisionEnv) Reset() {
	*x = DeployService_ProvisionEnv{}
	mi := &file_release_v1_release_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployService_ProvisionEnv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployService_ProvisionEnv) ProtoMessage() {}

func (x *DeployService_ProvisionEnv) ProtoReflect() protoreflect.Message {
	mi := &file_release_v1_release_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployService_ProvisionEnv.ProtoReflect.Descriptor instead.
func (*DeployService_ProvisionEnv) Descriptor() ([]byte, []int) {
	return file_release_v1_release_proto_rawDescGZIP(), []int{2, 0}
}

func (x *DeployService_ProvisionEnv) GetEnvId() string {
	if x != nil {
		return x.EnvId
	}
	return ""
}

type DeployService_RunMigrations struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployService_RunMigrations) Reset() {
	*x = DeployService_RunMigrations{}
	mi := &file_release_v1_release_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployService_RunMigrations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployService_RunMigrations) ProtoMessage() {}

func (x *DeployService_RunMigrations) ProtoReflect() protoreflect.Message {
	mi := &file_release_v1_release_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployService_RunMigrations.ProtoReflect.Descriptor instead.
func (*DeployService_RunMigrations) Descriptor() ([]byte, []int) {
	return file_release_v1_release_proto_rawDescGZIP(), []int{2, 1}
}

func (x *DeployService_RunMigrations) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

type DeployService_CanaryAnalysis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         uint32                 `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployService_CanaryAnalysis) Reset() {
	*x = DeployService_CanaryAnalysis{}
	mi := &file_release_v1_release_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployService_CanaryAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployService_CanaryAnalysis) ProtoMessage() {}

func (x *DeployService_CanaryAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_release_v1_release_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployService_CanaryAnalysis.ProtoReflect.Descriptor instead.
func (*DeployService_CanaryAnalysis) Descriptor() ([]byte, []int) {
	return file_release_v1_release_proto_rawDescGZIP(), []int{2, 2}
}

func (x *DeployService_CanaryAnalysis) GetScore() uint32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type DeployService_ShiftTraffic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LbGeneration  string                 `protobuf:"bytes,1,opt,name=lb_generation,json=lbGeneration,proto3" json:"lb_generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployService_ShiftTraffic) Reset() {
	*x = DeployService_ShiftTraffic{}
	mi := &file_release_v1_release_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployService_ShiftTraffic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployService_ShiftTraffic) ProtoMessage() {}

func (x *DeployService_ShiftTraffic) ProtoReflect() protoreflect.Message {
	mi := &file_release_v1_release_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployService_ShiftTraffic.ProtoReflect.Descriptor instead.
func (*DeployService_ShiftTraffic) Descriptor() ([]byte, []int) {
	return file_release_v1_release_proto_rawDescGZIP(), []int{2, 3}
}

func (x *DeployService_ShiftTraffic) GetLbGeneration() string {
	if x != nil {
		return x.LbGeneration
	}
	return ""
}

type ReleaseTrain_PlanRelease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseTrain_PlanRelease) Reset() {
	*x = ReleaseTrain_PlanRelease{}
	mi := &file_release_v1_release_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseTrain_PlanRelease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseTrain_PlanRelease) ProtoMessage() {}

func (x *ReleaseTrain_PlanRelease) ProtoReflect() protoreflect.Message {
	mi := &file_release_v1_release_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseTrain_PlanRelease.ProtoReflect.Descriptor instead.
func (*ReleaseTrain_PlanRelease) Descriptor() ([]byte, []int) {
	return file_release_v1_release_proto_rawDescGZIP(), []int{4, 0}
}

type ReleaseTrain_ShipWeb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseTrain_ShipWeb) Reset() {
	*x = ReleaseTrain_ShipWeb{}
	mi := &file_release_v1_release_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseTrain_ShipWeb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseTrain_ShipWeb) ProtoMessage() {}

func (x *ReleaseTrain_ShipWeb) ProtoReflect() protoreflect.Message {
	mi := &file_release_v1_release_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseTrain_ShipWeb.ProtoReflect.Descriptor instead.
func (*ReleaseTrain_ShipWeb) Descriptor() ([]byte, []int) {
	return file_release_v1_release_proto_rawDescGZIP(), []int{4, 1}
}

type ReleaseTrain_ShipApi struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseTrain_ShipApi) Reset() {
	*x = ReleaseTrain_ShipApi{}
	mi := &file_release_v1_release_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseTrain_ShipApi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseTrain_ShipApi) ProtoMessage() {}

func (x *ReleaseTrain_ShipApi) ProtoReflect() protoreflect.Message {
	mi := &file_release_v1_release_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseTrain_ShipApi.ProtoReflect.Descriptor instead.
func (*ReleaseTrain_ShipApi) Descriptor() ([]byte, []int) {
	return file_release_v1_release_proto_rawDescGZIP(), []int{4, 2}
}

type ReleaseTrain_Announce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangelogUrl  string                 `protobuf:"bytes,1,opt,name=changelog_url,json=changelogUrl,proto3" json:"changelog_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseTrain_Announce) Reset() {
	*x = ReleaseTrain_Announce{}
	mi := &file_release_v1_release_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseTrain_Announce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseTrain_Announce) ProtoMessage() {}

func (x *ReleaseTrain_Announce) ProtoReflect() protoreflect.Message {
	mi := &file_release_v1_release_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseTrain_Announce.ProtoReflect.Descriptor instead.
func (*ReleaseTrain_Announce) Descriptor() ([]byte, []int) {
	return file_release_v1_release_proto_rawDescGZIP(), []int{4, 3}
}

func (x *ReleaseTrain_Announce) GetChangelogUrl() string {
	if x != nil {
		return x.ChangelogUrl
	}
	return ""
}

var File_release_v1_release_proto protoreflect.FileDescriptor

const file_release_v1_release_proto_rawDesc = "" +
	"\n" +
	"\x18release/v1/release.proto\x12\n" +
	"release.v1\x1a\x18durable/v1/options.proto\"D\n" +
	"\x12DeployServiceInput\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\"'\n" +
	"\x13DeployServiceOutput\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x89\x03\n" +
	"\rDeployService\x1a?\n" +
	"\fProvisionEnv\x12\x15\n" +
	"\x06env_id\x18\x01 \x01(\tR\x05envId:\x18\x8a\xa8\x19\x14\n" +
	"\x10provision-env/v1\x10\x01\x1aQ\n" +
	"\rRunMigrations\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion:\x19\x8a\xa8\x19\x15\n" +
	"\x11run-migrations/v1\x10\x01\x1a@\n" +
	"\x0eCanaryAnalysis\x12\x14\n" +
	"\x05score\x18\x01 \x01(\rR\x05score:\x18\x8a\xa8\x19\x14\n" +
	"\x12canary-analysis/v1\x1aK\n" +
	"\fShiftTraffic\x12#\n" +
	"\rlb_generation\x18\x01 \x01(\tR\flbGeneration:\x16\x8a\xa8\x19\x12\n" +
	"\x10shift-traffic/v1:U\x92\xa8\x19Q\n" +
	"\x0edeploy-service\x12\x1e.release.v1.DeployServiceInput\x1a\x1f.release.v1.DeployServiceOutput\"0\n" +
	"\x11ReleaseTrainInput\x12\x1b\n" +
	"\timage_tag\x18\x01 \x01(\tR\bimageTag\"\xe0\x01\n" +
	"\fReleaseTrain\x1a\x1c\n" +
	"\vPlanRelease:\r\x8a\xa8\x19\t\n" +
	"\aplan/v1\x1a\x1c\n" +
	"\aShipWeb:\x11\x8a\xa8\x19\r\n" +
	"\vship-web/v1\x1a\x1c\n" +
	"\aShipApi:\x11\x8a\xa8\x19\r\n" +
	"\vship-api/v1\x1aB\n" +
	"\bAnnounce\x12#\n" +
	"\rchangelog_url\x18\x01 \x01(\tR\fchangelogUrl:\x11\x8a\xa8\x19\r\n" +
	"\vannounce/v1:2\x92\xa8\x19.\n" +
	"\rrelease-train\x12\x1d.release.v1.ReleaseTrainInputB<Z:github.com/dangra/durable/examples/release-train/releasepbb\x06proto3"

var (
	file_release_v1_release_proto_rawDescOnce sync.Once
	file_release_v1_release_proto_rawDescData []byte
)

func file_release_v1_release_proto_rawDescGZIP() []byte {
	file_release_v1_release_proto_rawDescOnce.Do(func() {
		file_release_v1_release_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_release_v1_release_proto_rawDesc), len(file_release_v1_release_proto_rawDesc)))
	})
	return file_release_v1_release_proto_rawDescData
}

var file_release_v1_release_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_release_v1_release_proto_goTypes = []any{
	(*DeployServiceInput)(nil),           // 0: release.v1.DeployServiceInput
	(*DeployServiceOutput)(nil),          // 1: release.v1.DeployServiceOutput
	(*DeployService)(nil),                // 2: release.v1.DeployService
	(*ReleaseTrainInput)(nil),            // 3: release.v1.ReleaseTrainInput
	(*ReleaseTrain)(nil),                 // 4: release.v1.ReleaseTrain
	(*DeployService_ProvisionEnv)(nil),   // 5: release.v1.DeployService.ProvisionEnv
	(*DeployService_RunMigrations)(nil),  // 6: release.v1.DeployService.RunMigrations
	(*DeployService_CanaryAnalysis)(nil), // 7: release.v1.DeployService.CanaryAnalysis
	(*DeployService_ShiftTraffic)(nil),   // 8: release.v1.DeployService.ShiftTraffic
	(*ReleaseTrain_PlanRelease)(nil),     // 9: release.v1.ReleaseTrain.PlanRelease
	(*ReleaseTrain_ShipWeb)(nil),         // 10: release.v1.ReleaseTrain.ShipWeb
	(*ReleaseTrain_ShipApi)(nil),         // 11: release.v1.ReleaseTrain.ShipApi
	(*ReleaseTrain_Announce)(nil),        // 12: release.v1.ReleaseTrain.Announce
}
var file_release_v1_release_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_release_v1_release_proto_init() }
func file_release_v1_release_proto_init() {
	if File_release_v1_release_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_release_v1_release_proto_rawDesc), len(file_release_v1_release_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_release_v1_release_proto_goTypes,
		DependencyIndexes: file_release_v1_release_proto_depIdxs,
		MessageInfos:      file_release_v1_release_proto_msgTypes,
	}.Build()
	File_release_v1_release_proto = out.File
	file_release_v1_release_proto_goTypes = nil
	file_release_v1_release_proto_depIdxs = nil
}
