// Today's build of the release platform: the deploy pipeline gained a
// canary-analysis step (compare legacyproto/, yesterday's build without
// it), and the release-train pipeline orchestrates per-service deploys.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: release/v1/release.proto

package releasepb

import (
	_ "github.com/dangra/durable/durablepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProvisionEnv struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvId         string                 `protobuf:"bytes,1,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionEnv) Reset() {
	*x = ProvisionEnv{}
	mi := &file_release_v1_release_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionEnv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionEnv) ProtoMessage() {}

func (x *ProvisionEnv) ProtoReflect() protoreflect.Message {
	mi := &file_release_v1_release_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionEnv.ProtoReflect.Descriptor instead.
func (*ProvisionEnv) Descriptor() ([]byte, []int) {
	return file_release_v1_release_proto_rawDescGZIP(), []int{0}
}

func (x *ProvisionEnv) GetEnvId() string {
	if x != nil {
		return x.EnvId
	}
	return ""
}

type RunMigrations struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunMigrations) Reset() {
	*x = RunMigrations{}
	mi := &file_release_v1_release_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunMigrations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunMigrations) ProtoMessage() {}

func (x *RunMigrations) ProtoReflect() protoreflect.Message {
	mi := &file_release_v1_release_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunMigrations.ProtoReflect.Descriptor instead.
func (*RunMigrations) Descriptor() ([]byte, []int) {
	return file_release_v1_release_proto_rawDescGZIP(), []int{1}
}

func (x *RunMigrations) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

// CanaryAnalysis is the step added while runs were in flight: a run
// whose forward frontier is run-migrations executes it; a run already
// past shift-traffic never executes it retroactively.
type CanaryAnalysis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         uint32                 `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanaryAnalysis) Reset() {
	*x = CanaryAnalysis{}
	mi := &file_release_v1_release_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanaryAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanaryAnalysis) ProtoMessage() {}

func (x *CanaryAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_release_v1_release_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanaryAnalysis.ProtoReflect.Descriptor instead.
func (*CanaryAnalysis) Descriptor() ([]byte, []int) {
	return file_release_v1_release_proto_rawDescGZIP(), []int{2}
}

func (x *CanaryAnalysis) GetScore() uint32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type ShiftTraffic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LbGeneration  string                 `protobuf:"bytes,1,opt,name=lb_generation,json=lbGeneration,proto3" json:"lb_generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShiftTraffic) Reset() {
	*x = ShiftTraffic{}
	mi := &file_release_v1_release_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShiftTraffic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShiftTraffic) ProtoMessage() {}

func (x *ShiftTraffic) ProtoReflect() protoreflect.Message {
	mi := &file_release_v1_release_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShiftTraffic.ProtoReflect.Descriptor instead.
func (*ShiftTraffic) Descriptor() ([]byte, []int) {
	return file_release_v1_release_proto_rawDescGZIP(), []int{3}
}

func (x *ShiftTraffic) GetLbGeneration() string {
	if x != nil {
		return x.LbGeneration
	}
	return ""
}

type DeployServiceInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployServiceInput) Reset() {
	*x = DeployServiceInput{}
	mi := &file_release_v1_release_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployServiceInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployServiceInput) ProtoMessage() {}

func (x *DeployServiceInput) ProtoReflect() protoreflect.Message {
	mi := &file_release_v1_release_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployServiceInput.ProtoReflect.Descriptor instead.
func (*DeployServiceInput) Descriptor() ([]byte, []int) {
	return file_release_v1_release_proto_rawDescGZIP(), []int{4}
}

func (x *DeployServiceInput) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *DeployServiceInput) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type DeployServiceOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployServiceOutput) Reset() {
	*x = DeployServiceOutput{}
	mi := &file_release_v1_release_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployServiceOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployServiceOutput) ProtoMessage() {}

func (x *DeployServiceOutput) ProtoReflect() protoreflect.Message {
	mi := &file_release_v1_release_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployServiceOutput.ProtoReflect.Descriptor instead.
func (*DeployServiceOutput) Descriptor() ([]byte, []int) {
	return file_release_v1_release_proto_rawDescGZIP(), []int{5}
}

func (x *DeployServiceOutput) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type DeployService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployService) Reset() {
	*x = DeployService{}
	mi := &file_release_v1_release_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployService) ProtoMessage() {}

func (x *DeployService) ProtoReflect() protoreflect.Message {
	mi := &file_release_v1_release_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployService.ProtoReflect.Descriptor instead.
func (*DeployService) Descriptor() ([]byte, []int) {
	return file_release_v1_release_proto_rawDescGZIP(), []int{6}
}

type PlanRelease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanRelease) Reset() {
	*x = PlanRelease{}
	mi := &file_release_v1_release_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanRelease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanRelease) ProtoMessage() {}

func (x *PlanRelease) ProtoReflect() protoreflect.Message {
	mi := &file_release_v1_release_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanRelease.ProtoReflect.Descriptor instead.
func (*PlanRelease) Descriptor() ([]byte, []int) {
	return file_release_v1_release_proto_rawDescGZIP(), []int{7}
}

type ShipWeb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipWeb) Reset() {
	*x = ShipWeb{}
	mi := &file_release_v1_release_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipWeb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipWeb) ProtoMessage() {}

func (x *ShipWeb) ProtoReflect() protoreflect.Message {
	mi := &file_release_v1_release_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipWeb.ProtoReflect.Descriptor instead.
func (*ShipWeb) Descriptor() ([]byte, []int) {
	return file_release_v1_release_proto_rawDescGZIP(), []int{8}
}

type ShipApi struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipApi) Reset() {
	*x = ShipApi{}
	mi := &file_release_v1_release_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipApi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipApi) ProtoMessage() {}

func (x *ShipApi) ProtoReflect() protoreflect.Message {
	mi := &file_release_v1_release_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipApi.ProtoReflect.Descriptor instead.
func (*ShipApi) Descriptor() ([]byte, []int) {
	return file_release_v1_release_proto_rawDescGZIP(), []int{9}
}

// Announce wraps the release: publish the changelog and notify. In the
// demo it never executes — the train is frozen first, and a canceled
// run selects no new forward work.
type Announce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangelogUrl  string                 `protobuf:"bytes,1,opt,name=changelog_url,json=changelogUrl,proto3" json:"changelog_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Announce) Reset() {
	*x = Announce{}
	mi := &file_release_v1_release_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Announce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Announce) ProtoMessage() {}

func (x *Announce) ProtoReflect() protoreflect.Message {
	mi := &file_release_v1_release_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Announce.ProtoReflect.Descriptor instead.
func (*Announce) Descriptor() ([]byte, []int) {
	return file_release_v1_release_proto_rawDescGZIP(), []int{10}
}

func (x *Announce) GetChangelogUrl() string {
	if x != nil {
		return x.ChangelogUrl
	}
	return ""
}

type ReleaseTrainInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageTag      string                 `protobuf:"bytes,1,opt,name=image_tag,json=imageTag,proto3" json:"image_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseTrainInput) Reset() {
	*x = ReleaseTrainInput{}
	mi := &file_release_v1_release_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseTrainInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseTrainInput) ProtoMessage() {}

func (x *ReleaseTrainInput) ProtoReflect() protoreflect.Message {
	mi := &file_release_v1_release_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseTrainInput.ProtoReflect.Descriptor instead.
func (*ReleaseTrainInput) Descriptor() ([]byte, []int) {
	return file_release_v1_release_proto_rawDescGZIP(), []int{11}
}

func (x *ReleaseTrainInput) GetImageTag() string {
	if x != nil {
		return x.ImageTag
	}
	return ""
}

type ReleaseTrain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseTrain) Reset() {
	*x = ReleaseTrain{}
	mi := &file_release_v1_release_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseTrain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseTrain) ProtoMessage() {}

func (x *ReleaseTrain) ProtoReflect() protoreflect.Message {
	mi := &file_release_v1_release_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseTrain.ProtoReflect.Descriptor instead.
func (*ReleaseTrain) Descriptor() ([]byte, []int) {
	return file_release_v1_release_proto_rawDescGZIP(), []int{12}
}

var File_release_v1_release_proto protoreflect.FileDescriptor

const file_release_v1_release_proto_rawDesc = "" +
	"\n" +
	"\x18release/v1/release.proto\x12\n" +
	"release.v1\x1a\x18durable/v1/options.proto\"?\n" +
	"\fProvisionEnv\x12\x15\n" +
	"\x06env_id\x18\x01 \x01(\tR\x05envId:\x18\x8a\xa8\x19\x14\n" +
	"\x10provision-env/v1\x10\x01\"Q\n" +
	"\rRunMigrations\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion:\x19\x8a\xa8\x19\x15\n" +
	"\x11run-migrations/v1\x10\x01\"@\n" +
	"\x0eCanaryAnalysis\x12\x14\n" +
	"\x05score\x18\x01 \x01(\rR\x05score:\x18\x8a\xa8\x19\x14\n" +
	"\x12canary-analysis/v1\"K\n" +
	"\fShiftTraffic\x12#\n" +
	"\rlb_generation\x18\x01 \x01(\tR\flbGeneration:\x16\x8a\xa8\x19\x12\n" +
	"\x10shift-traffic/v1\"D\n" +
	"\x12DeployServiceInput\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\"'\n" +
	"\x13DeployServiceOutput\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\xd3\x01\n" +
	"\rDeployService:\xc1\x01\x92\xa8\x19\xbc\x01\n" +
	"\x0edeploy-service\x12\x1e.release.v1.DeployServiceInput\x1a\x1f.release.v1.DeployServiceOutput\"\x18.release.v1.ProvisionEnv\"\x19.release.v1.RunMigrations\"\x1a.release.v1.CanaryAnalysis\"\x18.release.v1.ShiftTraffic\"\x1c\n" +
	"\vPlanRelease:\r\x8a\xa8\x19\t\n" +
	"\aplan/v1\"\x1c\n" +
	"\aShipWeb:\x11\x8a\xa8\x19\r\n" +
	"\vship-web/v1\"\x1c\n" +
	"\aShipApi:\x11\x8a\xa8\x19\r\n" +
	"\vship-api/v1\"B\n" +
	"\bAnnounce\x12#\n" +
	"\rchangelog_url\x18\x01 \x01(\tR\fchangelogUrl:\x11\x8a\xa8\x19\r\n" +
	"\vannounce/v1\"0\n" +
	"\x11ReleaseTrainInput\x12\x1b\n" +
	"\timage_tag\x18\x01 \x01(\tR\bimageTag\"\x9d\x01\n" +
	"\fReleaseTrain:\x8c\x01\x92\xa8\x19\x87\x01\n" +
	"\rrelease-train\x12\x1d.release.v1.ReleaseTrainInput\"\x17.release.v1.PlanRelease\"\x13.release.v1.ShipWeb\"\x13.release.v1.ShipApi\"\x14.release.v1.AnnounceB<Z:github.com/dangra/durable/examples/release-train/releasepbb\x06proto3"

var (
	file_release_v1_release_proto_rawDescOnce sync.Once
	file_release_v1_release_proto_rawDescData []byte
)

func file_release_v1_release_proto_rawDescGZIP() []byte {
	file_release_v1_release_proto_rawDescOnce.Do(func() {
		file_release_v1_release_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_release_v1_release_proto_rawDesc), len(file_release_v1_release_proto_rawDesc)))
	})
	return file_release_v1_release_proto_rawDescData
}

var file_release_v1_release_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_release_v1_release_proto_goTypes = []any{
	(*ProvisionEnv)(nil),        // 0: release.v1.ProvisionEnv
	(*RunMigrations)(nil),       // 1: release.v1.RunMigrations
	(*CanaryAnalysis)(nil),      // 2: release.v1.CanaryAnalysis
	(*ShiftTraffic)(nil),        // 3: release.v1.ShiftTraffic
	(*DeployServiceInput)(nil),  // 4: release.v1.DeployServiceInput
	(*DeployServiceOutput)(nil), // 5: release.v1.DeployServiceOutput
	(*DeployService)(nil),       // 6: release.v1.DeployService
	(*PlanRelease)(nil),         // 7: release.v1.PlanRelease
	(*ShipWeb)(nil),             // 8: release.v1.ShipWeb
	(*ShipApi)(nil),             // 9: release.v1.ShipApi
	(*Announce)(nil),            // 10: release.v1.Announce
	(*ReleaseTrainInput)(nil),   // 11: release.v1.ReleaseTrainInput
	(*ReleaseTrain)(nil),        // 12: release.v1.ReleaseTrain
}
var file_release_v1_release_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_release_v1_release_proto_init() }
func file_release_v1_release_proto_init() {
	if File_release_v1_release_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_release_v1_release_proto_rawDesc), len(file_release_v1_release_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_release_v1_release_proto_goTypes,
		DependencyIndexes: file_release_v1_release_proto_depIdxs,
		MessageInfos:      file_release_v1_release_proto_msgTypes,
	}.Build()
	File_release_v1_release_proto = out.File
	file_release_v1_release_proto_goTypes = nil
	file_release_v1_release_proto_depIdxs = nil
}
