// Code generated by protoc-gen-durable. DO NOT EDIT.
//
// source: release/v1/release.proto
// pipeline: deploy-service
// pipeline: release-train

package releasepb

import (
	context "context"
	durable "github.com/dangra/durable"
	engine "github.com/dangra/durable/engine"
	proto "google.golang.org/protobuf/proto"
	sync "sync"
)

// ProvisionEnvStep is the typed reference to the state-producing step "provision-env/v1".
var ProvisionEnvStep = durable.NewStateStepRef("provision-env/v1", func() *ProvisionEnv { return &ProvisionEnv{} })

// RunMigrationsStep is the typed reference to the state-producing step "run-migrations/v1".
var RunMigrationsStep = durable.NewStateStepRef("run-migrations/v1", func() *RunMigrations { return &RunMigrations{} })

// CanaryAnalysisStep is the typed reference to the state-producing step "canary-analysis/v1".
var CanaryAnalysisStep = durable.NewStateStepRef("canary-analysis/v1", func() *CanaryAnalysis { return &CanaryAnalysis{} })

// ShiftTrafficStep is the typed reference to the state-producing step "shift-traffic/v1".
var ShiftTrafficStep = durable.NewStateStepRef("shift-traffic/v1", func() *ShiftTraffic { return &ShiftTraffic{} })

// ProvisionEnvInvocation is passed to ProvisionEnvHandler methods.
type ProvisionEnvInvocation struct {
	core durable.Invocation
}

func (inv ProvisionEnvInvocation) PipelineID() durable.PipelineID { return inv.core.PipelineID() }
func (inv ProvisionEnvInvocation) ResourceID() durable.ResourceID { return inv.core.ResourceID() }
func (inv ProvisionEnvInvocation) RunID() durable.RunID           { return inv.core.RunID() }
func (inv ProvisionEnvInvocation) StepID() durable.StepID         { return inv.core.StepID() }
func (inv ProvisionEnvInvocation) Attempt() uint64                { return inv.core.Attempt() }
func (inv ProvisionEnvInvocation) Phase() durable.Phase           { return inv.core.Phase() }

// CancelRequested reports whether a cancellation request was pending when
// this attempt was reserved.
func (inv ProvisionEnvInvocation) CancelRequested() bool { return inv.core.CancelRequested() }

// AwaitedRunID reports the run an earlier attempt of this operation parked
// on via durable.AwaitRun, once that park resolved. Multi-target parks
// are read through Awaited.
func (inv ProvisionEnvInvocation) AwaitedRunID() (durable.RunID, bool) {
	return inv.core.AwaitedRunID()
}

// Awaited reports the park an earlier attempt of this operation made, once
// it resolved; ok is false on a first execution.
func (inv ProvisionEnvInvocation) Awaited() (durable.Wake, bool) { return inv.core.Awaited() }

// Annotations returns a caller-owned copy of the run's immutable
// acceptance-time annotations (trace contexts, tenant tags).
func (inv ProvisionEnvInvocation) Annotations() map[string]string { return inv.core.Annotations() }

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (inv ProvisionEnvInvocation) Input() *DeployServiceInput {
	msg, _ := inv.core.InputMessage().(*DeployServiceInput)
	return msg
}

// State returns the committed state of the referenced step for this run.
// ok is false when no committed state exists.
func (inv ProvisionEnvInvocation) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(inv.core, step)
}

// ProvisionEnvHandler implements step "provision-env/v1".
type ProvisionEnvHandler interface {
	Run(context.Context, ProvisionEnvInvocation) (*ProvisionEnv, error)

	Unwind(context.Context, ProvisionEnvInvocation, durable.Failure) error
}

// ProvisionEnvFuncs adapts a pair of functions to ProvisionEnvHandler.
type ProvisionEnvFuncs struct {
	RunFunc    func(ctx context.Context, inv ProvisionEnvInvocation) (*ProvisionEnv, error)
	UnwindFunc func(context.Context, ProvisionEnvInvocation, durable.Failure) error
}

func (f ProvisionEnvFuncs) Run(ctx context.Context, inv ProvisionEnvInvocation) (*ProvisionEnv, error) {
	return f.RunFunc(ctx, inv)
}

func (f ProvisionEnvFuncs) Unwind(ctx context.Context, inv ProvisionEnvInvocation, failure durable.Failure) error {
	return f.UnwindFunc(ctx, inv, failure)
}

// RunMigrationsInvocation is passed to RunMigrationsHandler methods.
type RunMigrationsInvocation struct {
	core durable.Invocation
}

func (inv RunMigrationsInvocation) PipelineID() durable.PipelineID { return inv.core.PipelineID() }
func (inv RunMigrationsInvocation) ResourceID() durable.ResourceID { return inv.core.ResourceID() }
func (inv RunMigrationsInvocation) RunID() durable.RunID           { return inv.core.RunID() }
func (inv RunMigrationsInvocation) StepID() durable.StepID         { return inv.core.StepID() }
func (inv RunMigrationsInvocation) Attempt() uint64                { return inv.core.Attempt() }
func (inv RunMigrationsInvocation) Phase() durable.Phase           { return inv.core.Phase() }

// CancelRequested reports whether a cancellation request was pending when
// this attempt was reserved.
func (inv RunMigrationsInvocation) CancelRequested() bool { return inv.core.CancelRequested() }

// AwaitedRunID reports the run an earlier attempt of this operation parked
// on via durable.AwaitRun, once that park resolved. Multi-target parks
// are read through Awaited.
func (inv RunMigrationsInvocation) AwaitedRunID() (durable.RunID, bool) {
	return inv.core.AwaitedRunID()
}

// Awaited reports the park an earlier attempt of this operation made, once
// it resolved; ok is false on a first execution.
func (inv RunMigrationsInvocation) Awaited() (durable.Wake, bool) { return inv.core.Awaited() }

// Annotations returns a caller-owned copy of the run's immutable
// acceptance-time annotations (trace contexts, tenant tags).
func (inv RunMigrationsInvocation) Annotations() map[string]string { return inv.core.Annotations() }

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (inv RunMigrationsInvocation) Input() *DeployServiceInput {
	msg, _ := inv.core.InputMessage().(*DeployServiceInput)
	return msg
}

// State returns the committed state of the referenced step for this run.
// ok is false when no committed state exists.
func (inv RunMigrationsInvocation) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(inv.core, step)
}

// RunMigrationsHandler implements step "run-migrations/v1".
type RunMigrationsHandler interface {
	Run(context.Context, RunMigrationsInvocation) (*RunMigrations, error)

	Unwind(context.Context, RunMigrationsInvocation, durable.Failure) error
}

// RunMigrationsFuncs adapts a pair of functions to RunMigrationsHandler.
type RunMigrationsFuncs struct {
	RunFunc    func(ctx context.Context, inv RunMigrationsInvocation) (*RunMigrations, error)
	UnwindFunc func(context.Context, RunMigrationsInvocation, durable.Failure) error
}

func (f RunMigrationsFuncs) Run(ctx context.Context, inv RunMigrationsInvocation) (*RunMigrations, error) {
	return f.RunFunc(ctx, inv)
}

func (f RunMigrationsFuncs) Unwind(ctx context.Context, inv RunMigrationsInvocation, failure durable.Failure) error {
	return f.UnwindFunc(ctx, inv, failure)
}

// CanaryAnalysisInvocation is passed to CanaryAnalysisHandler methods.
type CanaryAnalysisInvocation struct {
	core durable.Invocation
}

func (inv CanaryAnalysisInvocation) PipelineID() durable.PipelineID { return inv.core.PipelineID() }
func (inv CanaryAnalysisInvocation) ResourceID() durable.ResourceID { return inv.core.ResourceID() }
func (inv CanaryAnalysisInvocation) RunID() durable.RunID           { return inv.core.RunID() }
func (inv CanaryAnalysisInvocation) StepID() durable.StepID         { return inv.core.StepID() }
func (inv CanaryAnalysisInvocation) Attempt() uint64                { return inv.core.Attempt() }
func (inv CanaryAnalysisInvocation) Phase() durable.Phase           { return inv.core.Phase() }

// CancelRequested reports whether a cancellation request was pending when
// this attempt was reserved.
func (inv CanaryAnalysisInvocation) CancelRequested() bool { return inv.core.CancelRequested() }

// AwaitedRunID reports the run an earlier attempt of this operation parked
// on via durable.AwaitRun, once that park resolved. Multi-target parks
// are read through Awaited.
func (inv CanaryAnalysisInvocation) AwaitedRunID() (durable.RunID, bool) {
	return inv.core.AwaitedRunID()
}

// Awaited reports the park an earlier attempt of this operation made, once
// it resolved; ok is false on a first execution.
func (inv CanaryAnalysisInvocation) Awaited() (durable.Wake, bool) { return inv.core.Awaited() }

// Annotations returns a caller-owned copy of the run's immutable
// acceptance-time annotations (trace contexts, tenant tags).
func (inv CanaryAnalysisInvocation) Annotations() map[string]string { return inv.core.Annotations() }

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (inv CanaryAnalysisInvocation) Input() *DeployServiceInput {
	msg, _ := inv.core.InputMessage().(*DeployServiceInput)
	return msg
}

// State returns the committed state of the referenced step for this run.
// ok is false when no committed state exists.
func (inv CanaryAnalysisInvocation) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(inv.core, step)
}

// CanaryAnalysisHandler implements step "canary-analysis/v1".
type CanaryAnalysisHandler interface {
	Run(context.Context, CanaryAnalysisInvocation) (*CanaryAnalysis, error)
}

// CanaryAnalysisFunc adapts a function to CanaryAnalysisHandler, in the style of
// http.HandlerFunc.
type CanaryAnalysisFunc func(ctx context.Context, inv CanaryAnalysisInvocation) (*CanaryAnalysis, error)

func (f CanaryAnalysisFunc) Run(ctx context.Context, inv CanaryAnalysisInvocation) (*CanaryAnalysis, error) {
	return f(ctx, inv)
}

// ShiftTrafficInvocation is passed to ShiftTrafficHandler methods.
type ShiftTrafficInvocation struct {
	core durable.Invocation
}

func (inv ShiftTrafficInvocation) PipelineID() durable.PipelineID { return inv.core.PipelineID() }
func (inv ShiftTrafficInvocation) ResourceID() durable.ResourceID { return inv.core.ResourceID() }
func (inv ShiftTrafficInvocation) RunID() durable.RunID           { return inv.core.RunID() }
func (inv ShiftTrafficInvocation) StepID() durable.StepID         { return inv.core.StepID() }
func (inv ShiftTrafficInvocation) Attempt() uint64                { return inv.core.Attempt() }
func (inv ShiftTrafficInvocation) Phase() durable.Phase           { return inv.core.Phase() }

// CancelRequested reports whether a cancellation request was pending when
// this attempt was reserved.
func (inv ShiftTrafficInvocation) CancelRequested() bool { return inv.core.CancelRequested() }

// AwaitedRunID reports the run an earlier attempt of this operation parked
// on via durable.AwaitRun, once that park resolved. Multi-target parks
// are read through Awaited.
func (inv ShiftTrafficInvocation) AwaitedRunID() (durable.RunID, bool) {
	return inv.core.AwaitedRunID()
}

// Awaited reports the park an earlier attempt of this operation made, once
// it resolved; ok is false on a first execution.
func (inv ShiftTrafficInvocation) Awaited() (durable.Wake, bool) { return inv.core.Awaited() }

// Annotations returns a caller-owned copy of the run's immutable
// acceptance-time annotations (trace contexts, tenant tags).
func (inv ShiftTrafficInvocation) Annotations() map[string]string { return inv.core.Annotations() }

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (inv ShiftTrafficInvocation) Input() *DeployServiceInput {
	msg, _ := inv.core.InputMessage().(*DeployServiceInput)
	return msg
}

// State returns the committed state of the referenced step for this run.
// ok is false when no committed state exists.
func (inv ShiftTrafficInvocation) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(inv.core, step)
}

// ShiftTrafficHandler implements step "shift-traffic/v1".
type ShiftTrafficHandler interface {
	Run(context.Context, ShiftTrafficInvocation) (*ShiftTraffic, error)
}

// ShiftTrafficFunc adapts a function to ShiftTrafficHandler, in the style of
// http.HandlerFunc.
type ShiftTrafficFunc func(ctx context.Context, inv ShiftTrafficInvocation) (*ShiftTraffic, error)

func (f ShiftTrafficFunc) Run(ctx context.Context, inv ShiftTrafficInvocation) (*ShiftTraffic, error) {
	return f(ctx, inv)
}

// DeployServiceReducer produces the pipeline output from the immutable input
// and committed step states. It must be pure: deterministic, side-effect
// free, synchronous, and non-failing.
type DeployServiceReducer func(*DeployService) *DeployServiceOutput

var deployServiceViews sync.Map

func (x *DeployService) durableView() durable.ReduceView {
	v, ok := deployServiceViews.Load(x)
	if !ok {
		panic("releasepb: DeployService is only usable as a reducer view during reduction")
	}
	return v.(durable.ReduceView)
}

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (x *DeployService) Input() *DeployServiceInput {
	msg, _ := x.durableView().InputMessage().(*DeployServiceInput)
	return msg
}

// State returns the committed state of the referenced step for the run
// being reduced. ok is false when no committed state exists.
func (x *DeployService) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(x.durableView(), step)
}

// DeployServiceDefinition is the unbound pipeline definition.
type DeployServiceDefinition struct {
	def *engine.Definition
}

// NewDeployService assembles the "deploy-service" pipeline definition
// from its step handlers and reducer.
func NewDeployService(
	provisionEnv ProvisionEnvHandler,
	runMigrations RunMigrationsHandler,
	canaryAnalysis CanaryAnalysisHandler,
	shiftTraffic ShiftTrafficHandler,
	reduce DeployServiceReducer,
) *DeployServiceDefinition {
	return &DeployServiceDefinition{def: engine.NewDefinition(engine.DefinitionConfig{
		ID:       "deploy-service",
		NewInput: func() proto.Message { return &DeployServiceInput{} },
		Reduce: func(view durable.ReduceView) proto.Message {
			x := &DeployService{}
			deployServiceViews.Store(x, view)
			defer deployServiceViews.Delete(x)
			return reduce(x)
		},
		Steps: []engine.StepConfig{
			{
				ID:       "provision-env/v1",
				Unwind:   true,
				HasState: true,
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					state, err := provisionEnv.Run(ctx, ProvisionEnvInvocation{core: core})
					if state == nil {
						return nil, err
					}
					return state, err
				},
				UnwindFunc: func(ctx context.Context, core durable.Invocation, failure durable.Failure) error {
					return provisionEnv.Unwind(ctx, ProvisionEnvInvocation{core: core}, failure)
				},
			},
			{
				ID:       "run-migrations/v1",
				Unwind:   true,
				HasState: true,
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					state, err := runMigrations.Run(ctx, RunMigrationsInvocation{core: core})
					if state == nil {
						return nil, err
					}
					return state, err
				},
				UnwindFunc: func(ctx context.Context, core durable.Invocation, failure durable.Failure) error {
					return runMigrations.Unwind(ctx, RunMigrationsInvocation{core: core}, failure)
				},
			},
			{
				ID:       "canary-analysis/v1",
				HasState: true,
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					state, err := canaryAnalysis.Run(ctx, CanaryAnalysisInvocation{core: core})
					if state == nil {
						return nil, err
					}
					return state, err
				},
			},
			{
				ID:       "shift-traffic/v1",
				HasState: true,
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					state, err := shiftTraffic.Run(ctx, ShiftTrafficInvocation{core: core})
					if state == nil {
						return nil, err
					}
					return state, err
				},
			},
		},
	})}
}

// Bind registers the definition with an engine. It is allowed only before
// Engine.Start.
func (d *DeployServiceDefinition) Bind(e *engine.Engine) (*DeployServicePipeline, error) {
	p, err := d.def.Bind(e)
	if err != nil {
		return nil, err
	}
	return &DeployServicePipeline{pipeline: p}, nil
}

// DeployServicePipeline is the definition bound to an engine.
type DeployServicePipeline struct {
	pipeline *engine.Pipeline
}

// Schedule creates a run for the resource slot or returns the active one.
func (p *DeployServicePipeline) Schedule(ctx context.Context, resource durable.ResourceID, input *DeployServiceInput, opts ...engine.ScheduleOption) (DeployServiceRun, bool, error) {
	run, created, err := p.pipeline.Schedule(ctx, resource, input, opts...)
	if err != nil {
		return DeployServiceRun{}, created, err
	}
	return DeployServiceRun{run: run}, created, nil
}

// Run returns a handle to an existing run of this pipeline.
func (p *DeployServicePipeline) Run(ctx context.Context, id durable.RunID) (DeployServiceRun, error) {
	run, err := p.pipeline.Run(ctx, id)
	if err != nil {
		return DeployServiceRun{}, err
	}
	return DeployServiceRun{run: run}, nil
}

// ActiveRun returns a handle to this pipeline's nonterminal run for a
// resource, if one exists — a read-only observation for wait/inspect
// flows; claiming the slot atomically remains Schedule's job.
func (p *DeployServicePipeline) ActiveRun(ctx context.Context, resource durable.ResourceID) (DeployServiceRun, bool, error) {
	run, ok, err := p.pipeline.ActiveRun(ctx, resource)
	if err != nil || !ok {
		return DeployServiceRun{}, ok, err
	}
	return DeployServiceRun{run: run}, true, nil
}

// Active returns handles for this pipeline's nonterminal runs.
func (p *DeployServicePipeline) Active(ctx context.Context) ([]DeployServiceRun, error) {
	runs, err := p.pipeline.Active(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]DeployServiceRun, 0, len(runs))
	for _, run := range runs {
		out = append(out, DeployServiceRun{run: run})
	}
	return out, nil
}

// Runs returns handles for all runs of this pipeline against a resource,
// oldest first.
func (p *DeployServicePipeline) Runs(ctx context.Context, resource durable.ResourceID) ([]DeployServiceRun, error) {
	runs, err := p.pipeline.Runs(ctx, resource)
	if err != nil {
		return nil, err
	}
	out := make([]DeployServiceRun, 0, len(runs))
	for _, run := range runs {
		out = append(out, DeployServiceRun{run: run})
	}
	return out, nil
}

// DeployServiceRun is a typed handle to one run of the pipeline.
type DeployServiceRun struct {
	run engine.Run
}

func (r DeployServiceRun) ID() durable.RunID { return r.run.ID() }

func (r DeployServiceRun) Status(ctx context.Context) (engine.Status, error) {
	return r.run.Status(ctx)
}

// Cancel durably requests cancellation: the run stops selecting new
// forward work and unwinds successfully executed steps.
func (r DeployServiceRun) Cancel(ctx context.Context, cause string) error {
	return r.run.Cancel(ctx, cause)
}

// Input returns a defensive caller-owned copy of the run's immutable
// pipeline input.
func (r DeployServiceRun) Input(ctx context.Context) (*DeployServiceInput, error) {
	b, err := r.run.InputBytes(ctx)
	if err != nil {
		return nil, err
	}
	msg := &DeployServiceInput{}
	if err := proto.Unmarshal(b, msg); err != nil {
		return nil, err
	}
	return msg, nil
}

// Wait blocks until the run is terminal. A successful result carries the
// pipeline output; a failed run has none.
func (r DeployServiceRun) Wait(ctx context.Context) (DeployServiceResult, error) {
	res, err := r.run.Wait(ctx)
	if err != nil {
		return DeployServiceResult{}, err
	}
	out := DeployServiceResult{Result: res}
	if res.Succeeded() {
		b, err := r.run.OutputBytes(ctx)
		if err != nil {
			return DeployServiceResult{}, err
		}
		msg := &DeployServiceOutput{}
		if err := proto.Unmarshal(b, msg); err != nil {
			return DeployServiceResult{}, err
		}
		out.output = msg
	}
	return out, nil
}

// DeployServiceResult is the typed terminal result of a run.
type DeployServiceResult struct {
	engine.Result
	output *DeployServiceOutput
}

// Output returns the pipeline output. It is non-nil exactly when the run
// succeeded.
func (r DeployServiceResult) Output() *DeployServiceOutput { return r.output }

// PlanReleaseStep is the reference to the stateless step "plan/v1".
// It is not accepted by State lookup.
var PlanReleaseStep = durable.NewStepRef("plan/v1")

// ShipWebStep is the reference to the stateless step "ship-web/v1".
// It is not accepted by State lookup.
var ShipWebStep = durable.NewStepRef("ship-web/v1")

// ShipApiStep is the reference to the stateless step "ship-api/v1".
// It is not accepted by State lookup.
var ShipApiStep = durable.NewStepRef("ship-api/v1")

// AnnounceStep is the typed reference to the state-producing step "announce/v1".
var AnnounceStep = durable.NewStateStepRef("announce/v1", func() *Announce { return &Announce{} })

// PlanReleaseInvocation is passed to PlanReleaseHandler methods.
type PlanReleaseInvocation struct {
	core durable.Invocation
}

func (inv PlanReleaseInvocation) PipelineID() durable.PipelineID { return inv.core.PipelineID() }
func (inv PlanReleaseInvocation) ResourceID() durable.ResourceID { return inv.core.ResourceID() }
func (inv PlanReleaseInvocation) RunID() durable.RunID           { return inv.core.RunID() }
func (inv PlanReleaseInvocation) StepID() durable.StepID         { return inv.core.StepID() }
func (inv PlanReleaseInvocation) Attempt() uint64                { return inv.core.Attempt() }
func (inv PlanReleaseInvocation) Phase() durable.Phase           { return inv.core.Phase() }

// CancelRequested reports whether a cancellation request was pending when
// this attempt was reserved.
func (inv PlanReleaseInvocation) CancelRequested() bool { return inv.core.CancelRequested() }

// AwaitedRunID reports the run an earlier attempt of this operation parked
// on via durable.AwaitRun, once that park resolved. Multi-target parks
// are read through Awaited.
func (inv PlanReleaseInvocation) AwaitedRunID() (durable.RunID, bool) { return inv.core.AwaitedRunID() }

// Awaited reports the park an earlier attempt of this operation made, once
// it resolved; ok is false on a first execution.
func (inv PlanReleaseInvocation) Awaited() (durable.Wake, bool) { return inv.core.Awaited() }

// Annotations returns a caller-owned copy of the run's immutable
// acceptance-time annotations (trace contexts, tenant tags).
func (inv PlanReleaseInvocation) Annotations() map[string]string { return inv.core.Annotations() }

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (inv PlanReleaseInvocation) Input() *ReleaseTrainInput {
	msg, _ := inv.core.InputMessage().(*ReleaseTrainInput)
	return msg
}

// State returns the committed state of the referenced step for this run.
// ok is false when no committed state exists.
func (inv PlanReleaseInvocation) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(inv.core, step)
}

// PlanReleaseHandler implements step "plan/v1".
type PlanReleaseHandler interface {
	Run(context.Context, PlanReleaseInvocation) error
}

// PlanReleaseFunc adapts a function to PlanReleaseHandler, in the style of
// http.HandlerFunc.
type PlanReleaseFunc func(ctx context.Context, inv PlanReleaseInvocation) error

func (f PlanReleaseFunc) Run(ctx context.Context, inv PlanReleaseInvocation) error {
	return f(ctx, inv)
}

// ShipWebInvocation is passed to ShipWebHandler methods.
type ShipWebInvocation struct {
	core durable.Invocation
}

func (inv ShipWebInvocation) PipelineID() durable.PipelineID { return inv.core.PipelineID() }
func (inv ShipWebInvocation) ResourceID() durable.ResourceID { return inv.core.ResourceID() }
func (inv ShipWebInvocation) RunID() durable.RunID           { return inv.core.RunID() }
func (inv ShipWebInvocation) StepID() durable.StepID         { return inv.core.StepID() }
func (inv ShipWebInvocation) Attempt() uint64                { return inv.core.Attempt() }
func (inv ShipWebInvocation) Phase() durable.Phase           { return inv.core.Phase() }

// CancelRequested reports whether a cancellation request was pending when
// this attempt was reserved.
func (inv ShipWebInvocation) CancelRequested() bool { return inv.core.CancelRequested() }

// AwaitedRunID reports the run an earlier attempt of this operation parked
// on via durable.AwaitRun, once that park resolved. Multi-target parks
// are read through Awaited.
func (inv ShipWebInvocation) AwaitedRunID() (durable.RunID, bool) { return inv.core.AwaitedRunID() }

// Awaited reports the park an earlier attempt of this operation made, once
// it resolved; ok is false on a first execution.
func (inv ShipWebInvocation) Awaited() (durable.Wake, bool) { return inv.core.Awaited() }

// Annotations returns a caller-owned copy of the run's immutable
// acceptance-time annotations (trace contexts, tenant tags).
func (inv ShipWebInvocation) Annotations() map[string]string { return inv.core.Annotations() }

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (inv ShipWebInvocation) Input() *ReleaseTrainInput {
	msg, _ := inv.core.InputMessage().(*ReleaseTrainInput)
	return msg
}

// State returns the committed state of the referenced step for this run.
// ok is false when no committed state exists.
func (inv ShipWebInvocation) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(inv.core, step)
}

// ShipWebHandler implements step "ship-web/v1".
type ShipWebHandler interface {
	Run(context.Context, ShipWebInvocation) error
}

// ShipWebFunc adapts a function to ShipWebHandler, in the style of
// http.HandlerFunc.
type ShipWebFunc func(ctx context.Context, inv ShipWebInvocation) error

func (f ShipWebFunc) Run(ctx context.Context, inv ShipWebInvocation) error { return f(ctx, inv) }

// ShipApiInvocation is passed to ShipApiHandler methods.
type ShipApiInvocation struct {
	core durable.Invocation
}

func (inv ShipApiInvocation) PipelineID() durable.PipelineID { return inv.core.PipelineID() }
func (inv ShipApiInvocation) ResourceID() durable.ResourceID { return inv.core.ResourceID() }
func (inv ShipApiInvocation) RunID() durable.RunID           { return inv.core.RunID() }
func (inv ShipApiInvocation) StepID() durable.StepID         { return inv.core.StepID() }
func (inv ShipApiInvocation) Attempt() uint64                { return inv.core.Attempt() }
func (inv ShipApiInvocation) Phase() durable.Phase           { return inv.core.Phase() }

// CancelRequested reports whether a cancellation request was pending when
// this attempt was reserved.
func (inv ShipApiInvocation) CancelRequested() bool { return inv.core.CancelRequested() }

// AwaitedRunID reports the run an earlier attempt of this operation parked
// on via durable.AwaitRun, once that park resolved. Multi-target parks
// are read through Awaited.
func (inv ShipApiInvocation) AwaitedRunID() (durable.RunID, bool) { return inv.core.AwaitedRunID() }

// Awaited reports the park an earlier attempt of this operation made, once
// it resolved; ok is false on a first execution.
func (inv ShipApiInvocation) Awaited() (durable.Wake, bool) { return inv.core.Awaited() }

// Annotations returns a caller-owned copy of the run's immutable
// acceptance-time annotations (trace contexts, tenant tags).
func (inv ShipApiInvocation) Annotations() map[string]string { return inv.core.Annotations() }

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (inv ShipApiInvocation) Input() *ReleaseTrainInput {
	msg, _ := inv.core.InputMessage().(*ReleaseTrainInput)
	return msg
}

// State returns the committed state of the referenced step for this run.
// ok is false when no committed state exists.
func (inv ShipApiInvocation) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(inv.core, step)
}

// ShipApiHandler implements step "ship-api/v1".
type ShipApiHandler interface {
	Run(context.Context, ShipApiInvocation) error
}

// ShipApiFunc adapts a function to ShipApiHandler, in the style of
// http.HandlerFunc.
type ShipApiFunc func(ctx context.Context, inv ShipApiInvocation) error

func (f ShipApiFunc) Run(ctx context.Context, inv ShipApiInvocation) error { return f(ctx, inv) }

// AnnounceInvocation is passed to AnnounceHandler methods.
type AnnounceInvocation struct {
	core durable.Invocation
}

func (inv AnnounceInvocation) PipelineID() durable.PipelineID { return inv.core.PipelineID() }
func (inv AnnounceInvocation) ResourceID() durable.ResourceID { return inv.core.ResourceID() }
func (inv AnnounceInvocation) RunID() durable.RunID           { return inv.core.RunID() }
func (inv AnnounceInvocation) StepID() durable.StepID         { return inv.core.StepID() }
func (inv AnnounceInvocation) Attempt() uint64                { return inv.core.Attempt() }
func (inv AnnounceInvocation) Phase() durable.Phase           { return inv.core.Phase() }

// CancelRequested reports whether a cancellation request was pending when
// this attempt was reserved.
func (inv AnnounceInvocation) CancelRequested() bool { return inv.core.CancelRequested() }

// AwaitedRunID reports the run an earlier attempt of this operation parked
// on via durable.AwaitRun, once that park resolved. Multi-target parks
// are read through Awaited.
func (inv AnnounceInvocation) AwaitedRunID() (durable.RunID, bool) { return inv.core.AwaitedRunID() }

// Awaited reports the park an earlier attempt of this operation made, once
// it resolved; ok is false on a first execution.
func (inv AnnounceInvocation) Awaited() (durable.Wake, bool) { return inv.core.Awaited() }

// Annotations returns a caller-owned copy of the run's immutable
// acceptance-time annotations (trace contexts, tenant tags).
func (inv AnnounceInvocation) Annotations() map[string]string { return inv.core.Annotations() }

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (inv AnnounceInvocation) Input() *ReleaseTrainInput {
	msg, _ := inv.core.InputMessage().(*ReleaseTrainInput)
	return msg
}

// State returns the committed state of the referenced step for this run.
// ok is false when no committed state exists.
func (inv AnnounceInvocation) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(inv.core, step)
}

// AnnounceHandler implements step "announce/v1".
type AnnounceHandler interface {
	Run(context.Context, AnnounceInvocation) (*Announce, error)
}

// AnnounceFunc adapts a function to AnnounceHandler, in the style of
// http.HandlerFunc.
type AnnounceFunc func(ctx context.Context, inv AnnounceInvocation) (*Announce, error)

func (f AnnounceFunc) Run(ctx context.Context, inv AnnounceInvocation) (*Announce, error) {
	return f(ctx, inv)
}

var releaseTrainViews sync.Map

func (x *ReleaseTrain) durableView() durable.ReduceView {
	v, ok := releaseTrainViews.Load(x)
	if !ok {
		panic("releasepb: ReleaseTrain is only usable as a reducer view during reduction")
	}
	return v.(durable.ReduceView)
}

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (x *ReleaseTrain) Input() *ReleaseTrainInput {
	msg, _ := x.durableView().InputMessage().(*ReleaseTrainInput)
	return msg
}

// State returns the committed state of the referenced step for the run
// being reduced. ok is false when no committed state exists.
func (x *ReleaseTrain) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(x.durableView(), step)
}

// ReleaseTrainDefinition is the unbound pipeline definition.
type ReleaseTrainDefinition struct {
	def *engine.Definition
}

// NewReleaseTrain assembles the "release-train" pipeline definition
// from its step handlers.
func NewReleaseTrain(
	planRelease PlanReleaseHandler,
	shipWeb ShipWebHandler,
	shipApi ShipApiHandler,
	announce AnnounceHandler,
) *ReleaseTrainDefinition {
	return &ReleaseTrainDefinition{def: engine.NewDefinition(engine.DefinitionConfig{
		ID:       "release-train",
		NewInput: func() proto.Message { return &ReleaseTrainInput{} },
		Steps: []engine.StepConfig{
			{
				ID: "plan/v1",
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					return nil, planRelease.Run(ctx, PlanReleaseInvocation{core: core})
				},
			},
			{
				ID: "ship-web/v1",
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					return nil, shipWeb.Run(ctx, ShipWebInvocation{core: core})
				},
			},
			{
				ID: "ship-api/v1",
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					return nil, shipApi.Run(ctx, ShipApiInvocation{core: core})
				},
			},
			{
				ID:       "announce/v1",
				HasState: true,
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					state, err := announce.Run(ctx, AnnounceInvocation{core: core})
					if state == nil {
						return nil, err
					}
					return state, err
				},
			},
		},
	})}
}

// Bind registers the definition with an engine. It is allowed only before
// Engine.Start.
func (d *ReleaseTrainDefinition) Bind(e *engine.Engine) (*ReleaseTrainPipeline, error) {
	p, err := d.def.Bind(e)
	if err != nil {
		return nil, err
	}
	return &ReleaseTrainPipeline{pipeline: p}, nil
}

// ReleaseTrainPipeline is the definition bound to an engine.
type ReleaseTrainPipeline struct {
	pipeline *engine.Pipeline
}

// Schedule creates a run for the resource slot or returns the active one.
func (p *ReleaseTrainPipeline) Schedule(ctx context.Context, resource durable.ResourceID, input *ReleaseTrainInput, opts ...engine.ScheduleOption) (ReleaseTrainRun, bool, error) {
	run, created, err := p.pipeline.Schedule(ctx, resource, input, opts...)
	if err != nil {
		return ReleaseTrainRun{}, created, err
	}
	return ReleaseTrainRun{run: run}, created, nil
}

// Run returns a handle to an existing run of this pipeline.
func (p *ReleaseTrainPipeline) Run(ctx context.Context, id durable.RunID) (ReleaseTrainRun, error) {
	run, err := p.pipeline.Run(ctx, id)
	if err != nil {
		return ReleaseTrainRun{}, err
	}
	return ReleaseTrainRun{run: run}, nil
}

// ActiveRun returns a handle to this pipeline's nonterminal run for a
// resource, if one exists — a read-only observation for wait/inspect
// flows; claiming the slot atomically remains Schedule's job.
func (p *ReleaseTrainPipeline) ActiveRun(ctx context.Context, resource durable.ResourceID) (ReleaseTrainRun, bool, error) {
	run, ok, err := p.pipeline.ActiveRun(ctx, resource)
	if err != nil || !ok {
		return ReleaseTrainRun{}, ok, err
	}
	return ReleaseTrainRun{run: run}, true, nil
}

// Active returns handles for this pipeline's nonterminal runs.
func (p *ReleaseTrainPipeline) Active(ctx context.Context) ([]ReleaseTrainRun, error) {
	runs, err := p.pipeline.Active(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]ReleaseTrainRun, 0, len(runs))
	for _, run := range runs {
		out = append(out, ReleaseTrainRun{run: run})
	}
	return out, nil
}

// Runs returns handles for all runs of this pipeline against a resource,
// oldest first.
func (p *ReleaseTrainPipeline) Runs(ctx context.Context, resource durable.ResourceID) ([]ReleaseTrainRun, error) {
	runs, err := p.pipeline.Runs(ctx, resource)
	if err != nil {
		return nil, err
	}
	out := make([]ReleaseTrainRun, 0, len(runs))
	for _, run := range runs {
		out = append(out, ReleaseTrainRun{run: run})
	}
	return out, nil
}

// ReleaseTrainRun is a typed handle to one run of the pipeline.
type ReleaseTrainRun struct {
	run engine.Run
}

func (r ReleaseTrainRun) ID() durable.RunID { return r.run.ID() }

func (r ReleaseTrainRun) Status(ctx context.Context) (engine.Status, error) {
	return r.run.Status(ctx)
}

// Cancel durably requests cancellation: the run stops selecting new
// forward work and unwinds successfully executed steps.
func (r ReleaseTrainRun) Cancel(ctx context.Context, cause string) error {
	return r.run.Cancel(ctx, cause)
}

// Input returns a defensive caller-owned copy of the run's immutable
// pipeline input.
func (r ReleaseTrainRun) Input(ctx context.Context) (*ReleaseTrainInput, error) {
	b, err := r.run.InputBytes(ctx)
	if err != nil {
		return nil, err
	}
	msg := &ReleaseTrainInput{}
	if err := proto.Unmarshal(b, msg); err != nil {
		return nil, err
	}
	return msg, nil
}

// Wait blocks until the run is terminal.
func (r ReleaseTrainRun) Wait(ctx context.Context) (engine.Result, error) {
	return r.run.Wait(ctx)
}
