// The snapshot example: a pipeline whose handlers are plain functions
// wired through the generated http.HandlerFunc-style adapters.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: snapshots/v1/snapshots.proto

package snapshotspb

import (
	_ "github.com/dangra/durable/durablepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSnapshotInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotInput) Reset() {
	*x = CreateSnapshotInput{}
	mi := &file_snapshots_v1_snapshots_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotInput) ProtoMessage() {}

func (x *CreateSnapshotInput) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_v1_snapshots_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotInput.ProtoReflect.Descriptor instead.
func (*CreateSnapshotInput) Descriptor() ([]byte, []int) {
	return file_snapshots_v1_snapshots_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSnapshotInput) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

type CreateSnapshotOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotOutput) Reset() {
	*x = CreateSnapshotOutput{}
	mi := &file_snapshots_v1_snapshots_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotOutput) ProtoMessage() {}

func (x *CreateSnapshotOutput) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_v1_snapshots_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotOutput.ProtoReflect.Descriptor instead.
func (*CreateSnapshotOutput) Descriptor() ([]byte, []int) {
	return file_snapshots_v1_snapshots_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSnapshotOutput) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *CreateSnapshotOutput) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

// FreezeVolume quiesces the volume so the upload reads a consistent
// image. Its unwind thaws; the ThawVolume step thaws on the happy path.
type FreezeVolume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FreezeToken   string                 `protobuf:"bytes,1,opt,name=freeze_token,json=freezeToken,proto3" json:"freeze_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreezeVolume) Reset() {
	*x = FreezeVolume{}
	mi := &file_snapshots_v1_snapshots_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreezeVolume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreezeVolume) ProtoMessage() {}

func (x *FreezeVolume) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_v1_snapshots_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreezeVolume.ProtoReflect.Descriptor instead.
func (*FreezeVolume) Descriptor() ([]byte, []int) {
	return file_snapshots_v1_snapshots_proto_rawDescGZIP(), []int{2}
}

func (x *FreezeVolume) GetFreezeToken() string {
	if x != nil {
		return x.FreezeToken
	}
	return ""
}

// UploadSnapshot copies the frozen image to object storage. Its unwind
// deletes the object so a failed run leaves no orphan behind.
type UploadSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey     string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Bytes         uint64                 `protobuf:"varint,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSnapshot) Reset() {
	*x = UploadSnapshot{}
	mi := &file_snapshots_v1_snapshots_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSnapshot) ProtoMessage() {}

func (x *UploadSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_v1_snapshots_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSnapshot.ProtoReflect.Descriptor instead.
func (*UploadSnapshot) Descriptor() ([]byte, []int) {
	return file_snapshots_v1_snapshots_proto_rawDescGZIP(), []int{3}
}

func (x *UploadSnapshot) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *UploadSnapshot) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

type ThawVolume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThawVolume) Reset() {
	*x = ThawVolume{}
	mi := &file_snapshots_v1_snapshots_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThawVolume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThawVolume) ProtoMessage() {}

func (x *ThawVolume) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_v1_snapshots_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThawVolume.ProtoReflect.Descriptor instead.
func (*ThawVolume) Descriptor() ([]byte, []int) {
	return file_snapshots_v1_snapshots_proto_rawDescGZIP(), []int{4}
}

type RegisterSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSnapshot) Reset() {
	*x = RegisterSnapshot{}
	mi := &file_snapshots_v1_snapshots_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSnapshot) ProtoMessage() {}

func (x *RegisterSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_v1_snapshots_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSnapshot.ProtoReflect.Descriptor instead.
func (*RegisterSnapshot) Descriptor() ([]byte, []int) {
	return file_snapshots_v1_snapshots_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterSnapshot) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type CreateSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshot) Reset() {
	*x = CreateSnapshot{}
	mi := &file_snapshots_v1_snapshots_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshot) ProtoMessage() {}

func (x *CreateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_snapshots_v1_snapshots_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshot.ProtoReflect.Descriptor instead.
func (*CreateSnapshot) Descriptor() ([]byte, []int) {
	return file_snapshots_v1_snapshots_proto_rawDescGZIP(), []int{6}
}

var File_snapshots_v1_snapshots_proto protoreflect.FileDescriptor

const file_snapshots_v1_snapshots_proto_rawDesc = "" +
	"\n" +
	"\x1csnapshots/v1/snapshots.proto\x12\fsnapshots.v1\x1a\x18durable/v1/options.proto\"-\n" +
	"\x13CreateSnapshotInput\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\"V\n" +
	"\x14CreateSnapshotOutput\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\"K\n" +
	"\fFreezeVolume\x12!\n" +
	"\ffreeze_token\x18\x01 \x01(\tR\vfreezeToken:\x18\x8a\xa8\x19\x14\n" +
	"\x10freeze-volume/v1\x10\x01\"a\n" +
	"\x0eUploadSnapshot\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\x12\x14\n" +
	"\x05bytes\x18\x02 \x01(\x04R\x05bytes:\x1a\x8a\xa8\x19\x16\n" +
	"\x12upload-snapshot/v1\x10\x01\"\"\n" +
	"\n" +
	"ThawVolume:\x14\x8a\xa8\x19\x10\n" +
	"\x0ethaw-volume/v1\"O\n" +
	"\x10RegisterSnapshot\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId:\x1a\x8a\xa8\x19\x16\n" +
	"\x14register-snapshot/v1\"\xe4\x01\n" +
	"\x0eCreateSnapshot:\xd1\x01\x92\xa8\x19\xcc\x01\n" +
	"\x0fcreate-snapshot\x12!.snapshots.v1.CreateSnapshotInput\x1a\".snapshots.v1.CreateSnapshotOutput\"\x1a.snapshots.v1.FreezeVolume\"\x1c.snapshots.v1.UploadSnapshot\"\x18.snapshots.v1.ThawVolume\"\x1e.snapshots.v1.RegisterSnapshotBFZDgithub.com/dangra/durable/examples/snapshots/snapshotspb;snapshotspbb\x06proto3"

var (
	file_snapshots_v1_snapshots_proto_rawDescOnce sync.Once
	file_snapshots_v1_snapshots_proto_rawDescData []byte
)

func file_snapshots_v1_snapshots_proto_rawDescGZIP() []byte {
	file_snapshots_v1_snapshots_proto_rawDescOnce.Do(func() {
		file_snapshots_v1_snapshots_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_snapshots_v1_snapshots_proto_rawDesc), len(file_snapshots_v1_snapshots_proto_rawDesc)))
	})
	return file_snapshots_v1_snapshots_proto_rawDescData
}

var file_snapshots_v1_snapshots_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_snapshots_v1_snapshots_proto_goTypes = []any{
	(*CreateSnapshotInput)(nil),  // 0: snapshots.v1.CreateSnapshotInput
	(*CreateSnapshotOutput)(nil), // 1: snapshots.v1.CreateSnapshotOutput
	(*FreezeVolume)(nil),         // 2: snapshots.v1.FreezeVolume
	(*UploadSnapshot)(nil),       // 3: snapshots.v1.UploadSnapshot
	(*ThawVolume)(nil),           // 4: snapshots.v1.ThawVolume
	(*RegisterSnapshot)(nil),     // 5: snapshots.v1.RegisterSnapshot
	(*CreateSnapshot)(nil),       // 6: snapshots.v1.CreateSnapshot
}
var file_snapshots_v1_snapshots_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_snapshots_v1_snapshots_proto_init() }
func file_snapshots_v1_snapshots_proto_init() {
	if File_snapshots_v1_snapshots_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_snapshots_v1_snapshots_proto_rawDesc), len(file_snapshots_v1_snapshots_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_snapshots_v1_snapshots_proto_goTypes,
		DependencyIndexes: file_snapshots_v1_snapshots_proto_depIdxs,
		MessageInfos:      file_snapshots_v1_snapshots_proto_msgTypes,
	}.Build()
	File_snapshots_v1_snapshots_proto = out.File
	file_snapshots_v1_snapshots_proto_goTypes = nil
	file_snapshots_v1_snapshots_proto_depIdxs = nil
}
