// Code generated by protoc-gen-durable. DO NOT EDIT.
//
// source: snapshots/v1/snapshots.proto
// pipeline: create-snapshot

package snapshotspb

import (
	context "context"
	durable "github.com/dangra/durable"
	engine "github.com/dangra/durable/engine"
	pipelinedef "github.com/dangra/durable/pipelinedef"
	proto "google.golang.org/protobuf/proto"
	sync "sync"
)

// Option configures a pipeline of this package at construction,
// NewXxx(h, opts...): the runtime knobs a proto cannot declare. It is
// pipelinedef.Option, so the two are interchangeable.
type Option = pipelinedef.Option

// WithMiddleware installs middleware on the constructed pipeline alone,
// wrapping its operations, forward and unwind alike, inside any
// engine-level middleware; the first listed is outermost. Repeated
// options append.
func WithMiddleware(mw ...durable.Middleware) Option {
	return pipelinedef.WithMiddleware(mw...)
}

// CreateSnapshot_FreezeVolumeStep is the typed reference to the state-producing step "freeze-volume/v1".
var CreateSnapshot_FreezeVolumeStep = pipelinedef.StateStepRef("freeze-volume/v1", func() *CreateSnapshot_FreezeVolume { return &CreateSnapshot_FreezeVolume{} })

// CreateSnapshot_UploadSnapshotStep is the typed reference to the state-producing step "upload-snapshot/v1".
var CreateSnapshot_UploadSnapshotStep = pipelinedef.StateStepRef("upload-snapshot/v1", func() *CreateSnapshot_UploadSnapshot { return &CreateSnapshot_UploadSnapshot{} })

// CreateSnapshot_ThawVolumeStep is the reference to the stateless step "thaw-volume/v1".
// It is not accepted by State lookup.
var CreateSnapshot_ThawVolumeStep = pipelinedef.StepRef("thaw-volume/v1")

// CreateSnapshot_RegisterSnapshotStep is the typed reference to the state-producing step "register-snapshot/v1".
var CreateSnapshot_RegisterSnapshotStep = pipelinedef.StateStepRef("register-snapshot/v1", func() *CreateSnapshot_RegisterSnapshot { return &CreateSnapshot_RegisterSnapshot{} })

// CreateSnapshotInvocation is the invocation every CreateSnapshotHandlers method receives:
// durable.Invocation with the pipeline's Input typed.
type CreateSnapshotInvocation = durable.TypedInvocation[*CreateSnapshotInput]

// NewCreateSnapshotInvocation wraps core for calling a CreateSnapshotHandlers method directly,
// outside an engine: hand it durabletest.NewInvocation to unit-test a
// handler. The engine wraps its own invocations; application code never
// needs this at runtime.
func NewCreateSnapshotInvocation(core durable.Invocation) CreateSnapshotInvocation {
	return durable.Typed[*CreateSnapshotInput](core)
}

// CreateSnapshotHandlers implements the "create-snapshot" pipeline: one method per
// step, named after the step, plus Unwind<Step> for each step that
// unwinds. A type implements every step or does not compile; a step
// added to the pipeline is a method the next build demands.
type CreateSnapshotHandlers interface {
	// FreezeVolume runs step "freeze-volume/v1".
	FreezeVolume(ctx context.Context, inv CreateSnapshotInvocation) (*CreateSnapshot_FreezeVolume, error)
	// UnwindFreezeVolume compensates step "freeze-volume/v1" once it
	// succeeded and the run unwinds.
	UnwindFreezeVolume(ctx context.Context, inv CreateSnapshotInvocation) error
	// UploadSnapshot runs step "upload-snapshot/v1".
	UploadSnapshot(ctx context.Context, inv CreateSnapshotInvocation) (*CreateSnapshot_UploadSnapshot, error)
	// UnwindUploadSnapshot compensates step "upload-snapshot/v1" once it
	// succeeded and the run unwinds.
	UnwindUploadSnapshot(ctx context.Context, inv CreateSnapshotInvocation) error
	// ThawVolume runs step "thaw-volume/v1".
	ThawVolume(ctx context.Context, inv CreateSnapshotInvocation) error
	// RegisterSnapshot runs step "register-snapshot/v1".
	RegisterSnapshot(ctx context.Context, inv CreateSnapshotInvocation) (*CreateSnapshot_RegisterSnapshot, error)
	// ReduceOutput produces the pipeline output from the immutable input and
	// committed step states on success. It must be pure: deterministic,
	// side-effect free, synchronous, and non-failing.
	ReduceOutput(*CreateSnapshot) *CreateSnapshotOutput
	// ReduceFailure produces the pipeline failure output from the immutable
	// input, the committed step states, the run's Failure, and the permanent
	// unwind failures once the unwind completes. It must be pure.
	ReduceFailure(*CreateSnapshot) *CreateSnapshotFailure
}

// ReduceCreateSnapshotOutput folds view through h.ReduceOutput: the marker the reducer
// receives reads its Input, States, and failures from view for the
// duration of the call.
func ReduceCreateSnapshotOutput(h CreateSnapshotHandlers, view durable.ReduceView) *CreateSnapshotOutput {
	x := &CreateSnapshot{}
	createSnapshotViews.Store(x, view)
	defer createSnapshotViews.Delete(x)
	return h.ReduceOutput(x)
}

// ReduceCreateSnapshotFailure folds view through h.ReduceFailure: the marker the reducer
// receives reads its Input, States, and failures from view for the
// duration of the call.
func ReduceCreateSnapshotFailure(h CreateSnapshotHandlers, view durable.ReduceView) *CreateSnapshotFailure {
	x := &CreateSnapshot{}
	createSnapshotViews.Store(x, view)
	defer createSnapshotViews.Delete(x)
	return h.ReduceFailure(x)
}

var createSnapshotViews sync.Map

func (x *CreateSnapshot) durableView() durable.ReduceView {
	v, ok := createSnapshotViews.Load(x)
	if !ok {
		panic("snapshotspb: CreateSnapshot is only usable as a reducer view during reduction")
	}
	return v.(durable.ReduceView)
}

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (x *CreateSnapshot) Input() *CreateSnapshotInput {
	msg, _ := x.durableView().InputMessage().(*CreateSnapshotInput)
	return msg
}

// State returns the committed state of the referenced step for the run
// being reduced. ok is false when no committed state exists.
func (x *CreateSnapshot) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(x.durableView(), step)
}

// Failure is the run's failure when a failed run is being reduced, nil
// when a successful one is.
func (x *CreateSnapshot) Failure() *durable.Failure { return x.durableView().Failure() }

// UnwindFailure reports the permanent failure of the referenced step's
// unwind, if its compensation failed; ok is false when the step was not
// unwound or its unwind succeeded. Pair it with State to describe what a
// failed run left behind.
func (x *CreateSnapshot) UnwindFailure(step durable.StepIdentifier) (durable.Failure, bool) {
	return x.durableView().UnwindFailure(step.ID())
}

// CreateSnapshotDefinition is the unbound pipeline definition.
type CreateSnapshotDefinition struct {
	def *pipelinedef.Definition
}

// NewCreateSnapshot assembles the "create-snapshot" pipeline definition
// from its handlers; opts (WithMiddleware) configure what the proto
// cannot declare.
func NewCreateSnapshot(h CreateSnapshotHandlers, opts ...Option) *CreateSnapshotDefinition {
	cfg := pipelinedef.Config{
		ID:       "create-snapshot",
		NewInput: func() proto.Message { return &CreateSnapshotInput{} },
		Reduce: func(view durable.ReduceView) proto.Message {
			return ReduceCreateSnapshotOutput(h, view)
		},
		ReduceFailure: func(view durable.ReduceView) proto.Message {
			return ReduceCreateSnapshotFailure(h, view)
		},
		Steps: []pipelinedef.Step{
			{
				ID:       "freeze-volume/v1",
				Unwind:   true,
				HasState: true,
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					state, err := h.FreezeVolume(ctx, durable.Typed[*CreateSnapshotInput](core))
					if state == nil {
						return nil, err
					}
					return state, err
				},
				UnwindFunc: func(ctx context.Context, core durable.Invocation) error {
					return h.UnwindFreezeVolume(ctx, durable.Typed[*CreateSnapshotInput](core))
				},
			},
			{
				ID:       "upload-snapshot/v1",
				Unwind:   true,
				HasState: true,
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					state, err := h.UploadSnapshot(ctx, durable.Typed[*CreateSnapshotInput](core))
					if state == nil {
						return nil, err
					}
					return state, err
				},
				UnwindFunc: func(ctx context.Context, core durable.Invocation) error {
					return h.UnwindUploadSnapshot(ctx, durable.Typed[*CreateSnapshotInput](core))
				},
			},
			{
				ID: "thaw-volume/v1",
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					return nil, h.ThawVolume(ctx, durable.Typed[*CreateSnapshotInput](core))
				},
			},
			{
				ID:       "register-snapshot/v1",
				HasState: true,
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					state, err := h.RegisterSnapshot(ctx, durable.Typed[*CreateSnapshotInput](core))
					if state == nil {
						return nil, err
					}
					return state, err
				},
			},
		},
	}
	for _, o := range opts {
		o(&cfg)
	}
	return &CreateSnapshotDefinition{def: pipelinedef.New(cfg)}
}

// Bind registers the definition with an engine. It is allowed only before
// Engine.Start.
func (d *CreateSnapshotDefinition) Bind(e *engine.Engine) (*CreateSnapshotPipeline, error) {
	p, err := e.Bind(d.def)
	if err != nil {
		return nil, err
	}
	return &CreateSnapshotPipeline{pipeline: p}, nil
}

// CreateSnapshotPipeline is the definition bound to an engine.
type CreateSnapshotPipeline struct {
	pipeline *engine.Pipeline
}

// Schedule creates a run for the resource slot or returns the active one.
func (p *CreateSnapshotPipeline) Schedule(ctx context.Context, resource durable.ResourceID, input *CreateSnapshotInput, opts ...durable.ScheduleOption) (CreateSnapshotRun, bool, error) {
	run, created, err := p.pipeline.Schedule(ctx, resource, input, opts...)
	if err != nil {
		return CreateSnapshotRun{}, created, err
	}
	return CreateSnapshotRun{run: run}, created, nil
}

// GetRun returns a handle to an existing run of this pipeline.
func (p *CreateSnapshotPipeline) GetRun(ctx context.Context, id durable.RunID) (CreateSnapshotRun, error) {
	run, err := p.pipeline.GetRun(ctx, id)
	if err != nil {
		return CreateSnapshotRun{}, err
	}
	return CreateSnapshotRun{run: run}, nil
}

// GetActiveRun returns a handle to this pipeline's nonterminal run for a
// resource, if one exists — a read-only observation for wait/inspect
// flows; claiming the slot atomically remains Schedule's job.
func (p *CreateSnapshotPipeline) GetActiveRun(ctx context.Context, resource durable.ResourceID) (CreateSnapshotRun, bool, error) {
	run, ok, err := p.pipeline.GetActiveRun(ctx, resource)
	if err != nil || !ok {
		return CreateSnapshotRun{}, ok, err
	}
	return CreateSnapshotRun{run: run}, true, nil
}

// CreateSnapshotRun is a typed handle to one run of the pipeline.
type CreateSnapshotRun struct {
	run engine.Run
}

func (r CreateSnapshotRun) ID() durable.RunID { return r.run.ID() }

func (r CreateSnapshotRun) Status(ctx context.Context) (engine.Status, error) {
	return r.run.Status(ctx)
}

// Cancel durably requests cancellation: the run stops selecting new
// forward work and unwinds successfully executed steps.
func (r CreateSnapshotRun) Cancel(ctx context.Context, cause string) error {
	return r.run.Cancel(ctx, cause)
}

// Input returns a defensive caller-owned copy of the run's immutable
// pipeline input. The input is released when the run reaches its
// terminal outcome; Input on a terminal run returns durable.ErrRunTerminal.
func (r CreateSnapshotRun) Input(ctx context.Context) (*CreateSnapshotInput, error) {
	b, err := r.run.InputBytes(ctx)
	if err != nil {
		return nil, err
	}
	msg := &CreateSnapshotInput{}
	if err := proto.Unmarshal(b, msg); err != nil {
		return nil, err
	}
	return msg, nil
}

// Wait blocks until the run is terminal. A successful result carries the
// pipeline output and a failed one the failure output, each when the
// pipeline declares it.
func (r CreateSnapshotRun) Wait(ctx context.Context) (CreateSnapshotResult, error) {
	res, err := r.run.Wait(ctx)
	if err != nil {
		return CreateSnapshotResult{}, err
	}
	out := CreateSnapshotResult{Result: res}
	if res.Succeeded() {
		b, err := r.run.OutputBytes(ctx)
		if err != nil {
			return CreateSnapshotResult{}, err
		}
		msg := &CreateSnapshotOutput{}
		if err := proto.Unmarshal(b, msg); err != nil {
			return CreateSnapshotResult{}, err
		}
		out.output = msg
	}
	if res.Failed() {
		b, err := r.run.OutputBytes(ctx)
		if err != nil {
			return CreateSnapshotResult{}, err
		}
		msg := &CreateSnapshotFailure{}
		if err := proto.Unmarshal(b, msg); err != nil {
			return CreateSnapshotResult{}, err
		}
		out.failureOutput = msg
	}
	return out, nil
}

// CreateSnapshotResult is the typed terminal result of a run.
type CreateSnapshotResult struct {
	engine.Result
	output        *CreateSnapshotOutput
	failureOutput *CreateSnapshotFailure
}

// Output returns the pipeline output. It is non-nil exactly when the run
// succeeded.
func (r CreateSnapshotResult) Output() *CreateSnapshotOutput { return r.output }

// FailureOutput returns the pipeline failure output, the failure
// reducer's account of the failed run. It is non-nil exactly when the
// run failed.
func (r CreateSnapshotResult) FailureOutput() *CreateSnapshotFailure { return r.failureOutput }
