// Code generated by protoc-gen-durable. DO NOT EDIT.
//
// source: snapshots/v1/snapshots.proto
// pipeline: create-snapshot

package snapshotspb

import (
	context "context"
	durable "github.com/dangra/durable"
	engine "github.com/dangra/durable/engine"
	pipelinedef "github.com/dangra/durable/pipelinedef"
	proto "google.golang.org/protobuf/proto"
	slog "log/slog"
	sync "sync"
)

// FreezeVolumeStep is the typed reference to the state-producing step "freeze-volume/v1".
var FreezeVolumeStep = pipelinedef.StateStepRef("freeze-volume/v1", func() *FreezeVolume { return &FreezeVolume{} })

// UploadSnapshotStep is the typed reference to the state-producing step "upload-snapshot/v1".
var UploadSnapshotStep = pipelinedef.StateStepRef("upload-snapshot/v1", func() *UploadSnapshot { return &UploadSnapshot{} })

// ThawVolumeStep is the reference to the stateless step "thaw-volume/v1".
// It is not accepted by State lookup.
var ThawVolumeStep = pipelinedef.StepRef("thaw-volume/v1")

// RegisterSnapshotStep is the typed reference to the state-producing step "register-snapshot/v1".
var RegisterSnapshotStep = pipelinedef.StateStepRef("register-snapshot/v1", func() *RegisterSnapshot { return &RegisterSnapshot{} })

// FreezeVolumeInvocation is passed to FreezeVolumeHandler methods.
type FreezeVolumeInvocation struct {
	core durable.Invocation
}

// NewFreezeVolumeInvocation wraps core for calling a FreezeVolumeHandler directly, outside
// an engine: hand it durabletest.NewInvocation to unit-test the handler.
// The engine wraps its own invocations; application code never needs
// this at runtime.
func NewFreezeVolumeInvocation(core durable.Invocation) FreezeVolumeInvocation {
	return FreezeVolumeInvocation{core: core}
}

func (inv FreezeVolumeInvocation) PipelineID() durable.PipelineID { return inv.core.PipelineID() }
func (inv FreezeVolumeInvocation) ResourceID() durable.ResourceID { return inv.core.ResourceID() }
func (inv FreezeVolumeInvocation) RunID() durable.RunID           { return inv.core.RunID() }
func (inv FreezeVolumeInvocation) StepID() durable.StepID         { return inv.core.StepID() }
func (inv FreezeVolumeInvocation) Attempt() uint64                { return inv.core.Attempt() }
func (inv FreezeVolumeInvocation) Phase() durable.Phase           { return inv.core.Phase() }

// CancelRequested reports whether a cancellation request was pending when
// this attempt was reserved.
func (inv FreezeVolumeInvocation) CancelRequested() bool { return inv.core.CancelRequested() }

// AwaitedRunID reports the run an earlier attempt of this operation parked
// on via durable.AwaitRun, once that park resolved. Multi-target parks
// are read through Awaited.
func (inv FreezeVolumeInvocation) AwaitedRunID() (durable.RunID, bool) {
	return inv.core.AwaitedRunID()
}

// Awaited reports the park an earlier attempt of this operation made, once
// it resolved; ok is false on a first execution.
func (inv FreezeVolumeInvocation) Awaited() (durable.Wake, bool) { return inv.core.Awaited() }

// Annotations returns a caller-owned copy of the run's immutable
// acceptance-time annotations (trace contexts, tenant tags).
func (inv FreezeVolumeInvocation) Annotations() map[string]string { return inv.core.Annotations() }

// Failure is the failure this run is unwinding: non-nil exactly in
// durable.PhaseUnwind, nil during forward attempts.
func (inv FreezeVolumeInvocation) Failure() *durable.Failure { return inv.core.Failure() }

// Logger returns a logger scoped to this invocation, with the canonical
// pipeline, resource, run, step, phase, and attempt keys attached.
func (inv FreezeVolumeInvocation) Logger() *slog.Logger { return inv.core.Logger() }

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (inv FreezeVolumeInvocation) Input() *CreateSnapshotInput {
	msg, _ := inv.core.InputMessage().(*CreateSnapshotInput)
	return msg
}

// State returns the committed state of the referenced step for this run.
// ok is false when no committed state exists.
func (inv FreezeVolumeInvocation) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(inv.core, step)
}

// FreezeVolumeHandler implements step "freeze-volume/v1".
type FreezeVolumeHandler interface {
	Run(context.Context, FreezeVolumeInvocation) (*FreezeVolume, error)

	Unwind(context.Context, FreezeVolumeInvocation) error
}

// FreezeVolumeFuncs adapts a pair of functions to FreezeVolumeHandler.
type FreezeVolumeFuncs struct {
	RunFunc    func(ctx context.Context, inv FreezeVolumeInvocation) (*FreezeVolume, error)
	UnwindFunc func(ctx context.Context, inv FreezeVolumeInvocation) error
}

func (f FreezeVolumeFuncs) Run(ctx context.Context, inv FreezeVolumeInvocation) (*FreezeVolume, error) {
	return f.RunFunc(ctx, inv)
}

func (f FreezeVolumeFuncs) Unwind(ctx context.Context, inv FreezeVolumeInvocation) error {
	return f.UnwindFunc(ctx, inv)
}

// UploadSnapshotInvocation is passed to UploadSnapshotHandler methods.
type UploadSnapshotInvocation struct {
	core durable.Invocation
}

// NewUploadSnapshotInvocation wraps core for calling a UploadSnapshotHandler directly, outside
// an engine: hand it durabletest.NewInvocation to unit-test the handler.
// The engine wraps its own invocations; application code never needs
// this at runtime.
func NewUploadSnapshotInvocation(core durable.Invocation) UploadSnapshotInvocation {
	return UploadSnapshotInvocation{core: core}
}

func (inv UploadSnapshotInvocation) PipelineID() durable.PipelineID { return inv.core.PipelineID() }
func (inv UploadSnapshotInvocation) ResourceID() durable.ResourceID { return inv.core.ResourceID() }
func (inv UploadSnapshotInvocation) RunID() durable.RunID           { return inv.core.RunID() }
func (inv UploadSnapshotInvocation) StepID() durable.StepID         { return inv.core.StepID() }
func (inv UploadSnapshotInvocation) Attempt() uint64                { return inv.core.Attempt() }
func (inv UploadSnapshotInvocation) Phase() durable.Phase           { return inv.core.Phase() }

// CancelRequested reports whether a cancellation request was pending when
// this attempt was reserved.
func (inv UploadSnapshotInvocation) CancelRequested() bool { return inv.core.CancelRequested() }

// AwaitedRunID reports the run an earlier attempt of this operation parked
// on via durable.AwaitRun, once that park resolved. Multi-target parks
// are read through Awaited.
func (inv UploadSnapshotInvocation) AwaitedRunID() (durable.RunID, bool) {
	return inv.core.AwaitedRunID()
}

// Awaited reports the park an earlier attempt of this operation made, once
// it resolved; ok is false on a first execution.
func (inv UploadSnapshotInvocation) Awaited() (durable.Wake, bool) { return inv.core.Awaited() }

// Annotations returns a caller-owned copy of the run's immutable
// acceptance-time annotations (trace contexts, tenant tags).
func (inv UploadSnapshotInvocation) Annotations() map[string]string { return inv.core.Annotations() }

// Failure is the failure this run is unwinding: non-nil exactly in
// durable.PhaseUnwind, nil during forward attempts.
func (inv UploadSnapshotInvocation) Failure() *durable.Failure { return inv.core.Failure() }

// Logger returns a logger scoped to this invocation, with the canonical
// pipeline, resource, run, step, phase, and attempt keys attached.
func (inv UploadSnapshotInvocation) Logger() *slog.Logger { return inv.core.Logger() }

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (inv UploadSnapshotInvocation) Input() *CreateSnapshotInput {
	msg, _ := inv.core.InputMessage().(*CreateSnapshotInput)
	return msg
}

// State returns the committed state of the referenced step for this run.
// ok is false when no committed state exists.
func (inv UploadSnapshotInvocation) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(inv.core, step)
}

// UploadSnapshotHandler implements step "upload-snapshot/v1".
type UploadSnapshotHandler interface {
	Run(context.Context, UploadSnapshotInvocation) (*UploadSnapshot, error)

	Unwind(context.Context, UploadSnapshotInvocation) error
}

// UploadSnapshotFuncs adapts a pair of functions to UploadSnapshotHandler.
type UploadSnapshotFuncs struct {
	RunFunc    func(ctx context.Context, inv UploadSnapshotInvocation) (*UploadSnapshot, error)
	UnwindFunc func(ctx context.Context, inv UploadSnapshotInvocation) error
}

func (f UploadSnapshotFuncs) Run(ctx context.Context, inv UploadSnapshotInvocation) (*UploadSnapshot, error) {
	return f.RunFunc(ctx, inv)
}

func (f UploadSnapshotFuncs) Unwind(ctx context.Context, inv UploadSnapshotInvocation) error {
	return f.UnwindFunc(ctx, inv)
}

// ThawVolumeInvocation is passed to ThawVolumeHandler methods.
type ThawVolumeInvocation struct {
	core durable.Invocation
}

// NewThawVolumeInvocation wraps core for calling a ThawVolumeHandler directly, outside
// an engine: hand it durabletest.NewInvocation to unit-test the handler.
// The engine wraps its own invocations; application code never needs
// this at runtime.
func NewThawVolumeInvocation(core durable.Invocation) ThawVolumeInvocation {
	return ThawVolumeInvocation{core: core}
}

func (inv ThawVolumeInvocation) PipelineID() durable.PipelineID { return inv.core.PipelineID() }
func (inv ThawVolumeInvocation) ResourceID() durable.ResourceID { return inv.core.ResourceID() }
func (inv ThawVolumeInvocation) RunID() durable.RunID           { return inv.core.RunID() }
func (inv ThawVolumeInvocation) StepID() durable.StepID         { return inv.core.StepID() }
func (inv ThawVolumeInvocation) Attempt() uint64                { return inv.core.Attempt() }
func (inv ThawVolumeInvocation) Phase() durable.Phase           { return inv.core.Phase() }

// CancelRequested reports whether a cancellation request was pending when
// this attempt was reserved.
func (inv ThawVolumeInvocation) CancelRequested() bool { return inv.core.CancelRequested() }

// AwaitedRunID reports the run an earlier attempt of this operation parked
// on via durable.AwaitRun, once that park resolved. Multi-target parks
// are read through Awaited.
func (inv ThawVolumeInvocation) AwaitedRunID() (durable.RunID, bool) { return inv.core.AwaitedRunID() }

// Awaited reports the park an earlier attempt of this operation made, once
// it resolved; ok is false on a first execution.
func (inv ThawVolumeInvocation) Awaited() (durable.Wake, bool) { return inv.core.Awaited() }

// Annotations returns a caller-owned copy of the run's immutable
// acceptance-time annotations (trace contexts, tenant tags).
func (inv ThawVolumeInvocation) Annotations() map[string]string { return inv.core.Annotations() }

// Failure is the failure this run is unwinding: non-nil exactly in
// durable.PhaseUnwind, nil during forward attempts.
func (inv ThawVolumeInvocation) Failure() *durable.Failure { return inv.core.Failure() }

// Logger returns a logger scoped to this invocation, with the canonical
// pipeline, resource, run, step, phase, and attempt keys attached.
func (inv ThawVolumeInvocation) Logger() *slog.Logger { return inv.core.Logger() }

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (inv ThawVolumeInvocation) Input() *CreateSnapshotInput {
	msg, _ := inv.core.InputMessage().(*CreateSnapshotInput)
	return msg
}

// State returns the committed state of the referenced step for this run.
// ok is false when no committed state exists.
func (inv ThawVolumeInvocation) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(inv.core, step)
}

// ThawVolumeHandler implements step "thaw-volume/v1".
type ThawVolumeHandler interface {
	Run(context.Context, ThawVolumeInvocation) error
}

// ThawVolumeFunc adapts a function to ThawVolumeHandler, in the style of
// http.HandlerFunc.
type ThawVolumeFunc func(ctx context.Context, inv ThawVolumeInvocation) error

func (f ThawVolumeFunc) Run(ctx context.Context, inv ThawVolumeInvocation) error { return f(ctx, inv) }

// RegisterSnapshotInvocation is passed to RegisterSnapshotHandler methods.
type RegisterSnapshotInvocation struct {
	core durable.Invocation
}

// NewRegisterSnapshotInvocation wraps core for calling a RegisterSnapshotHandler directly, outside
// an engine: hand it durabletest.NewInvocation to unit-test the handler.
// The engine wraps its own invocations; application code never needs
// this at runtime.
func NewRegisterSnapshotInvocation(core durable.Invocation) RegisterSnapshotInvocation {
	return RegisterSnapshotInvocation{core: core}
}

func (inv RegisterSnapshotInvocation) PipelineID() durable.PipelineID { return inv.core.PipelineID() }
func (inv RegisterSnapshotInvocation) ResourceID() durable.ResourceID { return inv.core.ResourceID() }
func (inv RegisterSnapshotInvocation) RunID() durable.RunID           { return inv.core.RunID() }
func (inv RegisterSnapshotInvocation) StepID() durable.StepID         { return inv.core.StepID() }
func (inv RegisterSnapshotInvocation) Attempt() uint64                { return inv.core.Attempt() }
func (inv RegisterSnapshotInvocation) Phase() durable.Phase           { return inv.core.Phase() }

// CancelRequested reports whether a cancellation request was pending when
// this attempt was reserved.
func (inv RegisterSnapshotInvocation) CancelRequested() bool { return inv.core.CancelRequested() }

// AwaitedRunID reports the run an earlier attempt of this operation parked
// on via durable.AwaitRun, once that park resolved. Multi-target parks
// are read through Awaited.
func (inv RegisterSnapshotInvocation) AwaitedRunID() (durable.RunID, bool) {
	return inv.core.AwaitedRunID()
}

// Awaited reports the park an earlier attempt of this operation made, once
// it resolved; ok is false on a first execution.
func (inv RegisterSnapshotInvocation) Awaited() (durable.Wake, bool) { return inv.core.Awaited() }

// Annotations returns a caller-owned copy of the run's immutable
// acceptance-time annotations (trace contexts, tenant tags).
func (inv RegisterSnapshotInvocation) Annotations() map[string]string { return inv.core.Annotations() }

// Failure is the failure this run is unwinding: non-nil exactly in
// durable.PhaseUnwind, nil during forward attempts.
func (inv RegisterSnapshotInvocation) Failure() *durable.Failure { return inv.core.Failure() }

// Logger returns a logger scoped to this invocation, with the canonical
// pipeline, resource, run, step, phase, and attempt keys attached.
func (inv RegisterSnapshotInvocation) Logger() *slog.Logger { return inv.core.Logger() }

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (inv RegisterSnapshotInvocation) Input() *CreateSnapshotInput {
	msg, _ := inv.core.InputMessage().(*CreateSnapshotInput)
	return msg
}

// State returns the committed state of the referenced step for this run.
// ok is false when no committed state exists.
func (inv RegisterSnapshotInvocation) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(inv.core, step)
}

// RegisterSnapshotHandler implements step "register-snapshot/v1".
type RegisterSnapshotHandler interface {
	Run(context.Context, RegisterSnapshotInvocation) (*RegisterSnapshot, error)
}

// RegisterSnapshotFunc adapts a function to RegisterSnapshotHandler, in the style of
// http.HandlerFunc.
type RegisterSnapshotFunc func(ctx context.Context, inv RegisterSnapshotInvocation) (*RegisterSnapshot, error)

func (f RegisterSnapshotFunc) Run(ctx context.Context, inv RegisterSnapshotInvocation) (*RegisterSnapshot, error) {
	return f(ctx, inv)
}

// CreateSnapshotReducer produces the pipeline output from the immutable input and committed step states on success.
// It must be pure: deterministic, side-effect free, synchronous, and
// non-failing.
type CreateSnapshotReducer func(*CreateSnapshot) *CreateSnapshotOutput

// Reduce folds view through r: the marker the reducer receives reads
// its Input, States, and failures from view for the duration of the
// call. The engine reduces through it; a unit test hands it
// durabletest.NewInvocation (which is also a durable.ReduceView) to
// exercise the reducer alone.
func (r CreateSnapshotReducer) Reduce(view durable.ReduceView) *CreateSnapshotOutput {
	x := &CreateSnapshot{}
	createSnapshotViews.Store(x, view)
	defer createSnapshotViews.Delete(x)
	return r(x)
}

// CreateSnapshotFailureReducer produces the pipeline failure output from the immutable input, the committed step states, the run's Failure, and the permanent unwind failures once the unwind completes.
// It must be pure: deterministic, side-effect free, synchronous, and
// non-failing.
type CreateSnapshotFailureReducer func(*CreateSnapshot) *CreateSnapshotFailure

// Reduce folds view through r: the marker the reducer receives reads
// its Input, States, and failures from view for the duration of the
// call. The engine reduces through it; a unit test hands it
// durabletest.NewInvocation (which is also a durable.ReduceView) to
// exercise the reducer alone.
func (r CreateSnapshotFailureReducer) Reduce(view durable.ReduceView) *CreateSnapshotFailure {
	x := &CreateSnapshot{}
	createSnapshotViews.Store(x, view)
	defer createSnapshotViews.Delete(x)
	return r(x)
}

var createSnapshotViews sync.Map

func (x *CreateSnapshot) durableView() durable.ReduceView {
	v, ok := createSnapshotViews.Load(x)
	if !ok {
		panic("snapshotspb: CreateSnapshot is only usable as a reducer view during reduction")
	}
	return v.(durable.ReduceView)
}

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (x *CreateSnapshot) Input() *CreateSnapshotInput {
	msg, _ := x.durableView().InputMessage().(*CreateSnapshotInput)
	return msg
}

// State returns the committed state of the referenced step for the run
// being reduced. ok is false when no committed state exists.
func (x *CreateSnapshot) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(x.durableView(), step)
}

// Failure is the run's failure when a failed run is being reduced, nil
// when a successful one is.
func (x *CreateSnapshot) Failure() *durable.Failure { return x.durableView().Failure() }

// UnwindFailure reports the permanent failure of the referenced step's
// unwind, if its compensation failed; ok is false when the step was not
// unwound or its unwind succeeded. Pair it with State to describe what a
// failed run left behind.
func (x *CreateSnapshot) UnwindFailure(step durable.StepIdentifier) (durable.Failure, bool) {
	return x.durableView().UnwindFailure(step.ID())
}

// CreateSnapshotDefinition is the unbound pipeline definition.
type CreateSnapshotDefinition struct {
	def *pipelinedef.Definition
}

// NewCreateSnapshot assembles the "create-snapshot" pipeline definition
// from its step handlers and reducers.
func NewCreateSnapshot(
	freezeVolume FreezeVolumeHandler,
	uploadSnapshot UploadSnapshotHandler,
	thawVolume ThawVolumeHandler,
	registerSnapshot RegisterSnapshotHandler,
	reduce CreateSnapshotReducer,
	reduceFailure CreateSnapshotFailureReducer,
) *CreateSnapshotDefinition {
	return &CreateSnapshotDefinition{def: pipelinedef.New(pipelinedef.Config{
		ID:       "create-snapshot",
		NewInput: func() proto.Message { return &CreateSnapshotInput{} },
		Reduce: func(view durable.ReduceView) proto.Message {
			return reduce.Reduce(view)
		},
		ReduceFailure: func(view durable.ReduceView) proto.Message {
			return reduceFailure.Reduce(view)
		},
		Steps: []pipelinedef.Step{
			{
				ID:       "freeze-volume/v1",
				Unwind:   true,
				HasState: true,
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					state, err := freezeVolume.Run(ctx, FreezeVolumeInvocation{core: core})
					if state == nil {
						return nil, err
					}
					return state, err
				},
				UnwindFunc: func(ctx context.Context, core durable.Invocation) error {
					return freezeVolume.Unwind(ctx, FreezeVolumeInvocation{core: core})
				},
			},
			{
				ID:       "upload-snapshot/v1",
				Unwind:   true,
				HasState: true,
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					state, err := uploadSnapshot.Run(ctx, UploadSnapshotInvocation{core: core})
					if state == nil {
						return nil, err
					}
					return state, err
				},
				UnwindFunc: func(ctx context.Context, core durable.Invocation) error {
					return uploadSnapshot.Unwind(ctx, UploadSnapshotInvocation{core: core})
				},
			},
			{
				ID: "thaw-volume/v1",
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					return nil, thawVolume.Run(ctx, ThawVolumeInvocation{core: core})
				},
			},
			{
				ID:       "register-snapshot/v1",
				HasState: true,
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					state, err := registerSnapshot.Run(ctx, RegisterSnapshotInvocation{core: core})
					if state == nil {
						return nil, err
					}
					return state, err
				},
			},
		},
	})}
}

// Bind registers the definition with an engine. It is allowed only before
// Engine.Start.
func (d *CreateSnapshotDefinition) Bind(e *engine.Engine) (*CreateSnapshotPipeline, error) {
	p, err := e.Bind(d.def)
	if err != nil {
		return nil, err
	}
	return &CreateSnapshotPipeline{pipeline: p}, nil
}

// CreateSnapshotPipeline is the definition bound to an engine.
type CreateSnapshotPipeline struct {
	pipeline *engine.Pipeline
}

// Schedule creates a run for the resource slot or returns the active one.
func (p *CreateSnapshotPipeline) Schedule(ctx context.Context, resource durable.ResourceID, input *CreateSnapshotInput, opts ...durable.ScheduleOption) (CreateSnapshotRun, bool, error) {
	run, created, err := p.pipeline.Schedule(ctx, resource, input, opts...)
	if err != nil {
		return CreateSnapshotRun{}, created, err
	}
	return CreateSnapshotRun{run: run}, created, nil
}

// GetRun returns a handle to an existing run of this pipeline.
func (p *CreateSnapshotPipeline) GetRun(ctx context.Context, id durable.RunID) (CreateSnapshotRun, error) {
	run, err := p.pipeline.GetRun(ctx, id)
	if err != nil {
		return CreateSnapshotRun{}, err
	}
	return CreateSnapshotRun{run: run}, nil
}

// GetActiveRun returns a handle to this pipeline's nonterminal run for a
// resource, if one exists — a read-only observation for wait/inspect
// flows; claiming the slot atomically remains Schedule's job.
func (p *CreateSnapshotPipeline) GetActiveRun(ctx context.Context, resource durable.ResourceID) (CreateSnapshotRun, bool, error) {
	run, ok, err := p.pipeline.GetActiveRun(ctx, resource)
	if err != nil || !ok {
		return CreateSnapshotRun{}, ok, err
	}
	return CreateSnapshotRun{run: run}, true, nil
}

// CreateSnapshotRun is a typed handle to one run of the pipeline.
type CreateSnapshotRun struct {
	run engine.Run
}

func (r CreateSnapshotRun) ID() durable.RunID { return r.run.ID() }

func (r CreateSnapshotRun) Status(ctx context.Context) (engine.Status, error) {
	return r.run.Status(ctx)
}

// Cancel durably requests cancellation: the run stops selecting new
// forward work and unwinds successfully executed steps.
func (r CreateSnapshotRun) Cancel(ctx context.Context, cause string) error {
	return r.run.Cancel(ctx, cause)
}

// Input returns a defensive caller-owned copy of the run's immutable
// pipeline input.
func (r CreateSnapshotRun) Input(ctx context.Context) (*CreateSnapshotInput, error) {
	b, err := r.run.InputBytes(ctx)
	if err != nil {
		return nil, err
	}
	msg := &CreateSnapshotInput{}
	if err := proto.Unmarshal(b, msg); err != nil {
		return nil, err
	}
	return msg, nil
}

// Wait blocks until the run is terminal. A successful result carries the
// pipeline output and a failed one the failure output, each when the
// pipeline declares it.
func (r CreateSnapshotRun) Wait(ctx context.Context) (CreateSnapshotResult, error) {
	res, err := r.run.Wait(ctx)
	if err != nil {
		return CreateSnapshotResult{}, err
	}
	out := CreateSnapshotResult{Result: res}
	if res.Succeeded() {
		b, err := r.run.OutputBytes(ctx)
		if err != nil {
			return CreateSnapshotResult{}, err
		}
		msg := &CreateSnapshotOutput{}
		if err := proto.Unmarshal(b, msg); err != nil {
			return CreateSnapshotResult{}, err
		}
		out.output = msg
	}
	if res.Failed() {
		b, err := r.run.OutputBytes(ctx)
		if err != nil {
			return CreateSnapshotResult{}, err
		}
		msg := &CreateSnapshotFailure{}
		if err := proto.Unmarshal(b, msg); err != nil {
			return CreateSnapshotResult{}, err
		}
		out.failureOutput = msg
	}
	return out, nil
}

// CreateSnapshotResult is the typed terminal result of a run.
type CreateSnapshotResult struct {
	engine.Result
	output        *CreateSnapshotOutput
	failureOutput *CreateSnapshotFailure
}

// Output returns the pipeline output. It is non-nil exactly when the run
// succeeded.
func (r CreateSnapshotResult) Output() *CreateSnapshotOutput { return r.output }

// FailureOutput returns the pipeline failure output, the failure
// reducer's account of the failed run. It is non-nil exactly when the
// run failed.
func (r CreateSnapshotResult) FailureOutput() *CreateSnapshotFailure { return r.failureOutput }
