// Code generated by protoc-gen-durable. DO NOT EDIT.
//
// source: orders/v1/orders.proto
// pipeline: fulfill-order

package orderspb

import (
	context "context"
	durable "github.com/dangra/durable"
	engine "github.com/dangra/durable/engine"
	pipelinedef "github.com/dangra/durable/pipelinedef"
	proto "google.golang.org/protobuf/proto"
	sync "sync"
)

// FulfillOrder_ReserveStockStep is the typed reference to the state-producing step "reserve-stock/v1".
var FulfillOrder_ReserveStockStep = pipelinedef.StateStepRef("reserve-stock/v1", func() *FulfillOrder_ReserveStock { return &FulfillOrder_ReserveStock{} })

// FulfillOrder_ChargePaymentStep is the typed reference to the state-producing step "charge-payment/v1".
var FulfillOrder_ChargePaymentStep = pipelinedef.StateStepRef("charge-payment/v1", func() *FulfillOrder_ChargePayment { return &FulfillOrder_ChargePayment{} })

// FulfillOrder_ShipStep is the typed reference to the state-producing step "ship/v1".
var FulfillOrder_ShipStep = pipelinedef.StateStepRef("ship/v1", func() *FulfillOrder_Ship { return &FulfillOrder_Ship{} })

// FulfillOrderInvocation is the invocation every FulfillOrderHandlers method receives:
// durable.Invocation with the pipeline's Input typed.
type FulfillOrderInvocation = durable.TypedInvocation[*FulfillOrderInput]

// NewFulfillOrderInvocation wraps core for calling a FulfillOrderHandlers method directly,
// outside an engine: hand it durabletest.NewInvocation to unit-test a
// handler. The engine wraps its own invocations; application code never
// needs this at runtime.
func NewFulfillOrderInvocation(core durable.Invocation) FulfillOrderInvocation {
	return durable.Typed[*FulfillOrderInput](core)
}

// FulfillOrderHandlers implements the "fulfill-order" pipeline: one method per
// step, named after the step, plus Unwind<Step> for each step that
// unwinds. A type implements every step or does not compile; a step
// added to the pipeline is a method the next build demands.
type FulfillOrderHandlers interface {
	// ReserveStock runs step "reserve-stock/v1".
	ReserveStock(ctx context.Context, inv FulfillOrderInvocation) (*FulfillOrder_ReserveStock, error)
	// UnwindReserveStock compensates step "reserve-stock/v1" once it
	// succeeded and the run unwinds.
	UnwindReserveStock(ctx context.Context, inv FulfillOrderInvocation) error
	// ChargePayment runs step "charge-payment/v1".
	ChargePayment(ctx context.Context, inv FulfillOrderInvocation) (*FulfillOrder_ChargePayment, error)
	// UnwindChargePayment compensates step "charge-payment/v1" once it
	// succeeded and the run unwinds.
	UnwindChargePayment(ctx context.Context, inv FulfillOrderInvocation) error
	// Ship runs step "ship/v1".
	Ship(ctx context.Context, inv FulfillOrderInvocation) (*FulfillOrder_Ship, error)
	// ReduceOutput produces the pipeline output from the immutable input and
	// committed step states on success. It must be pure: deterministic,
	// side-effect free, synchronous, and non-failing.
	ReduceOutput(*FulfillOrder) *FulfillOrderOutput
}

// ReduceFulfillOrderOutput folds view through h.ReduceOutput: the marker the reducer
// receives reads its Input, States, and failures from view for the
// duration of the call.
func ReduceFulfillOrderOutput(h FulfillOrderHandlers, view durable.ReduceView) *FulfillOrderOutput {
	x := &FulfillOrder{}
	fulfillOrderViews.Store(x, view)
	defer fulfillOrderViews.Delete(x)
	return h.ReduceOutput(x)
}

var fulfillOrderViews sync.Map

func (x *FulfillOrder) durableView() durable.ReduceView {
	v, ok := fulfillOrderViews.Load(x)
	if !ok {
		panic("orderspb: FulfillOrder is only usable as a reducer view during reduction")
	}
	return v.(durable.ReduceView)
}

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (x *FulfillOrder) Input() *FulfillOrderInput {
	msg, _ := x.durableView().InputMessage().(*FulfillOrderInput)
	return msg
}

// State returns the committed state of the referenced step for the run
// being reduced. ok is false when no committed state exists.
func (x *FulfillOrder) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(x.durableView(), step)
}

// Failure is the run's failure when a failed run is being reduced, nil
// when a successful one is.
func (x *FulfillOrder) Failure() *durable.Failure { return x.durableView().Failure() }

// UnwindFailure reports the permanent failure of the referenced step's
// unwind, if its compensation failed; ok is false when the step was not
// unwound or its unwind succeeded. Pair it with State to describe what a
// failed run left behind.
func (x *FulfillOrder) UnwindFailure(step durable.StepIdentifier) (durable.Failure, bool) {
	return x.durableView().UnwindFailure(step.ID())
}

// FulfillOrderDefinition is the unbound pipeline definition.
type FulfillOrderDefinition struct {
	def *pipelinedef.Definition
}

// NewFulfillOrder assembles the "fulfill-order" pipeline definition
// from its handlers.
func NewFulfillOrder(h FulfillOrderHandlers) *FulfillOrderDefinition {
	return &FulfillOrderDefinition{def: pipelinedef.New(pipelinedef.Config{
		ID:       "fulfill-order",
		NewInput: func() proto.Message { return &FulfillOrderInput{} },
		Reduce: func(view durable.ReduceView) proto.Message {
			return ReduceFulfillOrderOutput(h, view)
		},
		Steps: []pipelinedef.Step{
			{
				ID:       "reserve-stock/v1",
				Unwind:   true,
				HasState: true,
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					state, err := h.ReserveStock(ctx, durable.Typed[*FulfillOrderInput](core))
					if state == nil {
						return nil, err
					}
					return state, err
				},
				UnwindFunc: func(ctx context.Context, core durable.Invocation) error {
					return h.UnwindReserveStock(ctx, durable.Typed[*FulfillOrderInput](core))
				},
			},
			{
				ID:       "charge-payment/v1",
				Unwind:   true,
				HasState: true,
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					state, err := h.ChargePayment(ctx, durable.Typed[*FulfillOrderInput](core))
					if state == nil {
						return nil, err
					}
					return state, err
				},
				UnwindFunc: func(ctx context.Context, core durable.Invocation) error {
					return h.UnwindChargePayment(ctx, durable.Typed[*FulfillOrderInput](core))
				},
			},
			{
				ID:       "ship/v1",
				HasState: true,
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					state, err := h.Ship(ctx, durable.Typed[*FulfillOrderInput](core))
					if state == nil {
						return nil, err
					}
					return state, err
				},
			},
		},
	})}
}

// Bind registers the definition with an engine. It is allowed only before
// Engine.Start.
func (d *FulfillOrderDefinition) Bind(e *engine.Engine) (*FulfillOrderPipeline, error) {
	p, err := e.Bind(d.def)
	if err != nil {
		return nil, err
	}
	return &FulfillOrderPipeline{pipeline: p}, nil
}

// FulfillOrderPipeline is the definition bound to an engine.
type FulfillOrderPipeline struct {
	pipeline *engine.Pipeline
}

// Schedule creates a run for the resource slot or returns the active one.
func (p *FulfillOrderPipeline) Schedule(ctx context.Context, resource durable.ResourceID, input *FulfillOrderInput, opts ...durable.ScheduleOption) (FulfillOrderRun, bool, error) {
	run, created, err := p.pipeline.Schedule(ctx, resource, input, opts...)
	if err != nil {
		return FulfillOrderRun{}, created, err
	}
	return FulfillOrderRun{run: run}, created, nil
}

// GetRun returns a handle to an existing run of this pipeline.
func (p *FulfillOrderPipeline) GetRun(ctx context.Context, id durable.RunID) (FulfillOrderRun, error) {
	run, err := p.pipeline.GetRun(ctx, id)
	if err != nil {
		return FulfillOrderRun{}, err
	}
	return FulfillOrderRun{run: run}, nil
}

// GetActiveRun returns a handle to this pipeline's nonterminal run for a
// resource, if one exists — a read-only observation for wait/inspect
// flows; claiming the slot atomically remains Schedule's job.
func (p *FulfillOrderPipeline) GetActiveRun(ctx context.Context, resource durable.ResourceID) (FulfillOrderRun, bool, error) {
	run, ok, err := p.pipeline.GetActiveRun(ctx, resource)
	if err != nil || !ok {
		return FulfillOrderRun{}, ok, err
	}
	return FulfillOrderRun{run: run}, true, nil
}

// FulfillOrderRun is a typed handle to one run of the pipeline.
type FulfillOrderRun struct {
	run engine.Run
}

func (r FulfillOrderRun) ID() durable.RunID { return r.run.ID() }

func (r FulfillOrderRun) Status(ctx context.Context) (engine.Status, error) {
	return r.run.Status(ctx)
}

// Cancel durably requests cancellation: the run stops selecting new
// forward work and unwinds successfully executed steps.
func (r FulfillOrderRun) Cancel(ctx context.Context, cause string) error {
	return r.run.Cancel(ctx, cause)
}

// Input returns a defensive caller-owned copy of the run's immutable
// pipeline input. The input is released when the run reaches its
// terminal outcome; Input on a terminal run returns durable.ErrRunTerminal.
func (r FulfillOrderRun) Input(ctx context.Context) (*FulfillOrderInput, error) {
	b, err := r.run.InputBytes(ctx)
	if err != nil {
		return nil, err
	}
	msg := &FulfillOrderInput{}
	if err := proto.Unmarshal(b, msg); err != nil {
		return nil, err
	}
	return msg, nil
}

// Wait blocks until the run is terminal. A successful result carries the
// pipeline output and a failed one the failure output, each when the
// pipeline declares it.
func (r FulfillOrderRun) Wait(ctx context.Context) (FulfillOrderResult, error) {
	res, err := r.run.Wait(ctx)
	if err != nil {
		return FulfillOrderResult{}, err
	}
	out := FulfillOrderResult{Result: res}
	if res.Succeeded() {
		b, err := r.run.OutputBytes(ctx)
		if err != nil {
			return FulfillOrderResult{}, err
		}
		msg := &FulfillOrderOutput{}
		if err := proto.Unmarshal(b, msg); err != nil {
			return FulfillOrderResult{}, err
		}
		out.output = msg
	}
	return out, nil
}

// FulfillOrderResult is the typed terminal result of a run.
type FulfillOrderResult struct {
	engine.Result
	output *FulfillOrderOutput
}

// Output returns the pipeline output. It is non-nil exactly when the run
// succeeded.
func (r FulfillOrderResult) Output() *FulfillOrderOutput { return r.output }
