// Code generated by protoc-gen-durable. DO NOT EDIT.
//
// source: orders/v1/orders.proto
// pipeline: fulfill-order

package orderspb

import (
	context "context"
	durable "github.com/dangra/durable"
	engine "github.com/dangra/durable/engine"
	pipelinedef "github.com/dangra/durable/pipelinedef"
	proto "google.golang.org/protobuf/proto"
	slog "log/slog"
	sync "sync"
)

// ReserveStockStep is the typed reference to the state-producing step "reserve-stock/v1".
var ReserveStockStep = pipelinedef.StateStepRef("reserve-stock/v1", func() *ReserveStock { return &ReserveStock{} })

// ChargePaymentStep is the typed reference to the state-producing step "charge-payment/v1".
var ChargePaymentStep = pipelinedef.StateStepRef("charge-payment/v1", func() *ChargePayment { return &ChargePayment{} })

// ShipStep is the typed reference to the state-producing step "ship/v1".
var ShipStep = pipelinedef.StateStepRef("ship/v1", func() *Ship { return &Ship{} })

// ReserveStockInvocation is passed to ReserveStockHandler methods.
type ReserveStockInvocation struct {
	core durable.Invocation
}

// NewReserveStockInvocation wraps core for calling a ReserveStockHandler directly, outside
// an engine: hand it durabletest.NewInvocation to unit-test the handler.
// The engine wraps its own invocations; application code never needs
// this at runtime.
func NewReserveStockInvocation(core durable.Invocation) ReserveStockInvocation {
	return ReserveStockInvocation{core: core}
}

func (inv ReserveStockInvocation) PipelineID() durable.PipelineID { return inv.core.PipelineID() }
func (inv ReserveStockInvocation) ResourceID() durable.ResourceID { return inv.core.ResourceID() }
func (inv ReserveStockInvocation) RunID() durable.RunID           { return inv.core.RunID() }
func (inv ReserveStockInvocation) StepID() durable.StepID         { return inv.core.StepID() }
func (inv ReserveStockInvocation) Attempt() uint64                { return inv.core.Attempt() }
func (inv ReserveStockInvocation) Phase() durable.Phase           { return inv.core.Phase() }

// CancelRequested reports whether a cancellation request was pending when
// this attempt was reserved.
func (inv ReserveStockInvocation) CancelRequested() bool { return inv.core.CancelRequested() }

// AwaitedRunID reports the run an earlier attempt of this operation parked
// on via durable.AwaitRun, once that park resolved. Multi-target parks
// are read through Awaited.
func (inv ReserveStockInvocation) AwaitedRunID() (durable.RunID, bool) {
	return inv.core.AwaitedRunID()
}

// Awaited reports the park an earlier attempt of this operation made, once
// it resolved; ok is false on a first execution.
func (inv ReserveStockInvocation) Awaited() (durable.Wake, bool) { return inv.core.Awaited() }

// Annotations returns a caller-owned copy of the run's immutable
// acceptance-time annotations (trace contexts, tenant tags).
func (inv ReserveStockInvocation) Annotations() map[string]string { return inv.core.Annotations() }

// Failure is the failure this run is unwinding: non-nil exactly in
// durable.PhaseUnwind, nil during forward attempts.
func (inv ReserveStockInvocation) Failure() *durable.Failure { return inv.core.Failure() }

// Logger returns a logger scoped to this invocation, with the canonical
// pipeline, resource, run, step, phase, and attempt keys attached.
func (inv ReserveStockInvocation) Logger() *slog.Logger { return inv.core.Logger() }

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (inv ReserveStockInvocation) Input() *FulfillOrderInput {
	msg, _ := inv.core.InputMessage().(*FulfillOrderInput)
	return msg
}

// State returns the committed state of the referenced step for this run.
// ok is false when no committed state exists.
func (inv ReserveStockInvocation) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(inv.core, step)
}

// ReserveStockHandler implements step "reserve-stock/v1".
type ReserveStockHandler interface {
	Run(context.Context, ReserveStockInvocation) (*ReserveStock, error)

	Unwind(context.Context, ReserveStockInvocation) error
}

// ReserveStockFuncs adapts a pair of functions to ReserveStockHandler.
type ReserveStockFuncs struct {
	RunFunc    func(ctx context.Context, inv ReserveStockInvocation) (*ReserveStock, error)
	UnwindFunc func(ctx context.Context, inv ReserveStockInvocation) error
}

func (f ReserveStockFuncs) Run(ctx context.Context, inv ReserveStockInvocation) (*ReserveStock, error) {
	return f.RunFunc(ctx, inv)
}

func (f ReserveStockFuncs) Unwind(ctx context.Context, inv ReserveStockInvocation) error {
	return f.UnwindFunc(ctx, inv)
}

// ChargePaymentInvocation is passed to ChargePaymentHandler methods.
type ChargePaymentInvocation struct {
	core durable.Invocation
}

// NewChargePaymentInvocation wraps core for calling a ChargePaymentHandler directly, outside
// an engine: hand it durabletest.NewInvocation to unit-test the handler.
// The engine wraps its own invocations; application code never needs
// this at runtime.
func NewChargePaymentInvocation(core durable.Invocation) ChargePaymentInvocation {
	return ChargePaymentInvocation{core: core}
}

func (inv ChargePaymentInvocation) PipelineID() durable.PipelineID { return inv.core.PipelineID() }
func (inv ChargePaymentInvocation) ResourceID() durable.ResourceID { return inv.core.ResourceID() }
func (inv ChargePaymentInvocation) RunID() durable.RunID           { return inv.core.RunID() }
func (inv ChargePaymentInvocation) StepID() durable.StepID         { return inv.core.StepID() }
func (inv ChargePaymentInvocation) Attempt() uint64                { return inv.core.Attempt() }
func (inv ChargePaymentInvocation) Phase() durable.Phase           { return inv.core.Phase() }

// CancelRequested reports whether a cancellation request was pending when
// this attempt was reserved.
func (inv ChargePaymentInvocation) CancelRequested() bool { return inv.core.CancelRequested() }

// AwaitedRunID reports the run an earlier attempt of this operation parked
// on via durable.AwaitRun, once that park resolved. Multi-target parks
// are read through Awaited.
func (inv ChargePaymentInvocation) AwaitedRunID() (durable.RunID, bool) {
	return inv.core.AwaitedRunID()
}

// Awaited reports the park an earlier attempt of this operation made, once
// it resolved; ok is false on a first execution.
func (inv ChargePaymentInvocation) Awaited() (durable.Wake, bool) { return inv.core.Awaited() }

// Annotations returns a caller-owned copy of the run's immutable
// acceptance-time annotations (trace contexts, tenant tags).
func (inv ChargePaymentInvocation) Annotations() map[string]string { return inv.core.Annotations() }

// Failure is the failure this run is unwinding: non-nil exactly in
// durable.PhaseUnwind, nil during forward attempts.
func (inv ChargePaymentInvocation) Failure() *durable.Failure { return inv.core.Failure() }

// Logger returns a logger scoped to this invocation, with the canonical
// pipeline, resource, run, step, phase, and attempt keys attached.
func (inv ChargePaymentInvocation) Logger() *slog.Logger { return inv.core.Logger() }

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (inv ChargePaymentInvocation) Input() *FulfillOrderInput {
	msg, _ := inv.core.InputMessage().(*FulfillOrderInput)
	return msg
}

// State returns the committed state of the referenced step for this run.
// ok is false when no committed state exists.
func (inv ChargePaymentInvocation) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(inv.core, step)
}

// ChargePaymentHandler implements step "charge-payment/v1".
type ChargePaymentHandler interface {
	Run(context.Context, ChargePaymentInvocation) (*ChargePayment, error)

	Unwind(context.Context, ChargePaymentInvocation) error
}

// ChargePaymentFuncs adapts a pair of functions to ChargePaymentHandler.
type ChargePaymentFuncs struct {
	RunFunc    func(ctx context.Context, inv ChargePaymentInvocation) (*ChargePayment, error)
	UnwindFunc func(ctx context.Context, inv ChargePaymentInvocation) error
}

func (f ChargePaymentFuncs) Run(ctx context.Context, inv ChargePaymentInvocation) (*ChargePayment, error) {
	return f.RunFunc(ctx, inv)
}

func (f ChargePaymentFuncs) Unwind(ctx context.Context, inv ChargePaymentInvocation) error {
	return f.UnwindFunc(ctx, inv)
}

// ShipInvocation is passed to ShipHandler methods.
type ShipInvocation struct {
	core durable.Invocation
}

// NewShipInvocation wraps core for calling a ShipHandler directly, outside
// an engine: hand it durabletest.NewInvocation to unit-test the handler.
// The engine wraps its own invocations; application code never needs
// this at runtime.
func NewShipInvocation(core durable.Invocation) ShipInvocation { return ShipInvocation{core: core} }

func (inv ShipInvocation) PipelineID() durable.PipelineID { return inv.core.PipelineID() }
func (inv ShipInvocation) ResourceID() durable.ResourceID { return inv.core.ResourceID() }
func (inv ShipInvocation) RunID() durable.RunID           { return inv.core.RunID() }
func (inv ShipInvocation) StepID() durable.StepID         { return inv.core.StepID() }
func (inv ShipInvocation) Attempt() uint64                { return inv.core.Attempt() }
func (inv ShipInvocation) Phase() durable.Phase           { return inv.core.Phase() }

// CancelRequested reports whether a cancellation request was pending when
// this attempt was reserved.
func (inv ShipInvocation) CancelRequested() bool { return inv.core.CancelRequested() }

// AwaitedRunID reports the run an earlier attempt of this operation parked
// on via durable.AwaitRun, once that park resolved. Multi-target parks
// are read through Awaited.
func (inv ShipInvocation) AwaitedRunID() (durable.RunID, bool) { return inv.core.AwaitedRunID() }

// Awaited reports the park an earlier attempt of this operation made, once
// it resolved; ok is false on a first execution.
func (inv ShipInvocation) Awaited() (durable.Wake, bool) { return inv.core.Awaited() }

// Annotations returns a caller-owned copy of the run's immutable
// acceptance-time annotations (trace contexts, tenant tags).
func (inv ShipInvocation) Annotations() map[string]string { return inv.core.Annotations() }

// Failure is the failure this run is unwinding: non-nil exactly in
// durable.PhaseUnwind, nil during forward attempts.
func (inv ShipInvocation) Failure() *durable.Failure { return inv.core.Failure() }

// Logger returns a logger scoped to this invocation, with the canonical
// pipeline, resource, run, step, phase, and attempt keys attached.
func (inv ShipInvocation) Logger() *slog.Logger { return inv.core.Logger() }

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (inv ShipInvocation) Input() *FulfillOrderInput {
	msg, _ := inv.core.InputMessage().(*FulfillOrderInput)
	return msg
}

// State returns the committed state of the referenced step for this run.
// ok is false when no committed state exists.
func (inv ShipInvocation) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(inv.core, step)
}

// ShipHandler implements step "ship/v1".
type ShipHandler interface {
	Run(context.Context, ShipInvocation) (*Ship, error)
}

// ShipFunc adapts a function to ShipHandler, in the style of
// http.HandlerFunc.
type ShipFunc func(ctx context.Context, inv ShipInvocation) (*Ship, error)

func (f ShipFunc) Run(ctx context.Context, inv ShipInvocation) (*Ship, error) { return f(ctx, inv) }

// FulfillOrderReducer produces the pipeline output from the immutable input and committed step states on success.
// It must be pure: deterministic, side-effect free, synchronous, and
// non-failing.
type FulfillOrderReducer func(*FulfillOrder) *FulfillOrderOutput

// Reduce folds view through r: the marker the reducer receives reads
// its Input, States, and failures from view for the duration of the
// call. The engine reduces through it; a unit test hands it
// durabletest.NewInvocation (which is also a durable.ReduceView) to
// exercise the reducer alone.
func (r FulfillOrderReducer) Reduce(view durable.ReduceView) *FulfillOrderOutput {
	x := &FulfillOrder{}
	fulfillOrderViews.Store(x, view)
	defer fulfillOrderViews.Delete(x)
	return r(x)
}

var fulfillOrderViews sync.Map

func (x *FulfillOrder) durableView() durable.ReduceView {
	v, ok := fulfillOrderViews.Load(x)
	if !ok {
		panic("orderspb: FulfillOrder is only usable as a reducer view during reduction")
	}
	return v.(durable.ReduceView)
}

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (x *FulfillOrder) Input() *FulfillOrderInput {
	msg, _ := x.durableView().InputMessage().(*FulfillOrderInput)
	return msg
}

// State returns the committed state of the referenced step for the run
// being reduced. ok is false when no committed state exists.
func (x *FulfillOrder) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(x.durableView(), step)
}

// Failure is the run's failure when a failed run is being reduced, nil
// when a successful one is.
func (x *FulfillOrder) Failure() *durable.Failure { return x.durableView().Failure() }

// UnwindFailure reports the permanent failure of the referenced step's
// unwind, if its compensation failed; ok is false when the step was not
// unwound or its unwind succeeded. Pair it with State to describe what a
// failed run left behind.
func (x *FulfillOrder) UnwindFailure(step durable.StepIdentifier) (durable.Failure, bool) {
	return x.durableView().UnwindFailure(step.ID())
}

// FulfillOrderDefinition is the unbound pipeline definition.
type FulfillOrderDefinition struct {
	def *pipelinedef.Definition
}

// NewFulfillOrder assembles the "fulfill-order" pipeline definition
// from its step handlers and reducer.
func NewFulfillOrder(
	reserveStock ReserveStockHandler,
	chargePayment ChargePaymentHandler,
	ship ShipHandler,
	reduce FulfillOrderReducer,
) *FulfillOrderDefinition {
	return &FulfillOrderDefinition{def: pipelinedef.New(pipelinedef.Config{
		ID:       "fulfill-order",
		NewInput: func() proto.Message { return &FulfillOrderInput{} },
		Reduce: func(view durable.ReduceView) proto.Message {
			return reduce.Reduce(view)
		},
		Steps: []pipelinedef.Step{
			{
				ID:       "reserve-stock/v1",
				Unwind:   true,
				HasState: true,
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					state, err := reserveStock.Run(ctx, ReserveStockInvocation{core: core})
					if state == nil {
						return nil, err
					}
					return state, err
				},
				UnwindFunc: func(ctx context.Context, core durable.Invocation) error {
					return reserveStock.Unwind(ctx, ReserveStockInvocation{core: core})
				},
			},
			{
				ID:       "charge-payment/v1",
				Unwind:   true,
				HasState: true,
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					state, err := chargePayment.Run(ctx, ChargePaymentInvocation{core: core})
					if state == nil {
						return nil, err
					}
					return state, err
				},
				UnwindFunc: func(ctx context.Context, core durable.Invocation) error {
					return chargePayment.Unwind(ctx, ChargePaymentInvocation{core: core})
				},
			},
			{
				ID:       "ship/v1",
				HasState: true,
				Run: func(ctx context.Context, core durable.Invocation) (proto.Message, error) {
					state, err := ship.Run(ctx, ShipInvocation{core: core})
					if state == nil {
						return nil, err
					}
					return state, err
				},
			},
		},
	})}
}

// Bind registers the definition with an engine. It is allowed only before
// Engine.Start.
func (d *FulfillOrderDefinition) Bind(e *engine.Engine) (*FulfillOrderPipeline, error) {
	p, err := e.Bind(d.def)
	if err != nil {
		return nil, err
	}
	return &FulfillOrderPipeline{pipeline: p}, nil
}

// FulfillOrderPipeline is the definition bound to an engine.
type FulfillOrderPipeline struct {
	pipeline *engine.Pipeline
}

// Schedule creates a run for the resource slot or returns the active one.
func (p *FulfillOrderPipeline) Schedule(ctx context.Context, resource durable.ResourceID, input *FulfillOrderInput, opts ...durable.ScheduleOption) (FulfillOrderRun, bool, error) {
	run, created, err := p.pipeline.Schedule(ctx, resource, input, opts...)
	if err != nil {
		return FulfillOrderRun{}, created, err
	}
	return FulfillOrderRun{run: run}, created, nil
}

// GetRun returns a handle to an existing run of this pipeline.
func (p *FulfillOrderPipeline) GetRun(ctx context.Context, id durable.RunID) (FulfillOrderRun, error) {
	run, err := p.pipeline.GetRun(ctx, id)
	if err != nil {
		return FulfillOrderRun{}, err
	}
	return FulfillOrderRun{run: run}, nil
}

// GetActiveRun returns a handle to this pipeline's nonterminal run for a
// resource, if one exists — a read-only observation for wait/inspect
// flows; claiming the slot atomically remains Schedule's job.
func (p *FulfillOrderPipeline) GetActiveRun(ctx context.Context, resource durable.ResourceID) (FulfillOrderRun, bool, error) {
	run, ok, err := p.pipeline.GetActiveRun(ctx, resource)
	if err != nil || !ok {
		return FulfillOrderRun{}, ok, err
	}
	return FulfillOrderRun{run: run}, true, nil
}

// FulfillOrderRun is a typed handle to one run of the pipeline.
type FulfillOrderRun struct {
	run engine.Run
}

func (r FulfillOrderRun) ID() durable.RunID { return r.run.ID() }

func (r FulfillOrderRun) Status(ctx context.Context) (engine.Status, error) {
	return r.run.Status(ctx)
}

// Cancel durably requests cancellation: the run stops selecting new
// forward work and unwinds successfully executed steps.
func (r FulfillOrderRun) Cancel(ctx context.Context, cause string) error {
	return r.run.Cancel(ctx, cause)
}

// Input returns a defensive caller-owned copy of the run's immutable
// pipeline input.
func (r FulfillOrderRun) Input(ctx context.Context) (*FulfillOrderInput, error) {
	b, err := r.run.InputBytes(ctx)
	if err != nil {
		return nil, err
	}
	msg := &FulfillOrderInput{}
	if err := proto.Unmarshal(b, msg); err != nil {
		return nil, err
	}
	return msg, nil
}

// Wait blocks until the run is terminal. A successful result carries the
// pipeline output and a failed one the failure output, each when the
// pipeline declares it.
func (r FulfillOrderRun) Wait(ctx context.Context) (FulfillOrderResult, error) {
	res, err := r.run.Wait(ctx)
	if err != nil {
		return FulfillOrderResult{}, err
	}
	out := FulfillOrderResult{Result: res}
	if res.Succeeded() {
		b, err := r.run.OutputBytes(ctx)
		if err != nil {
			return FulfillOrderResult{}, err
		}
		msg := &FulfillOrderOutput{}
		if err := proto.Unmarshal(b, msg); err != nil {
			return FulfillOrderResult{}, err
		}
		out.output = msg
	}
	return out, nil
}

// FulfillOrderResult is the typed terminal result of a run.
type FulfillOrderResult struct {
	engine.Result
	output *FulfillOrderOutput
}

// Output returns the pipeline output. It is non-nil exactly when the run
// succeeded.
func (r FulfillOrderResult) Output() *FulfillOrderOutput { return r.output }
