// Code generated by protoc-gen-durable. DO NOT EDIT.
//
// source: orders/v1/orders.proto
// pipeline: fulfill-order

package orderspb

import (
	context "context"
	durable "github.com/dangra/durable"
	proto "google.golang.org/protobuf/proto"
	sync "sync"
)

// ReserveStockStep is the typed reference to the state-producing step "reserve-stock/v1".
var ReserveStockStep = durable.NewStateStepRef("reserve-stock/v1", func() *ReserveStock { return &ReserveStock{} })

// ChargePaymentStep is the typed reference to the state-producing step "charge-payment/v1".
var ChargePaymentStep = durable.NewStateStepRef("charge-payment/v1", func() *ChargePayment { return &ChargePayment{} })

// ShipStep is the typed reference to the state-producing step "ship/v1".
var ShipStep = durable.NewStateStepRef("ship/v1", func() *Ship { return &Ship{} })

// ReserveStockInvocation is passed to ReserveStockHandler methods.
type ReserveStockInvocation struct {
	core *durable.Invocation
}

func (inv ReserveStockInvocation) PipelineID() durable.PipelineID { return inv.core.PipelineID() }
func (inv ReserveStockInvocation) ResourceID() durable.ResourceID { return inv.core.ResourceID() }
func (inv ReserveStockInvocation) RunID() durable.RunID           { return inv.core.RunID() }
func (inv ReserveStockInvocation) StepID() durable.StepID         { return inv.core.StepID() }
func (inv ReserveStockInvocation) Attempt() uint64                { return inv.core.Attempt() }
func (inv ReserveStockInvocation) Phase() durable.Phase           { return inv.core.Phase() }

// CancelRequested reports whether a cancellation request was pending when
// this attempt was reserved.
func (inv ReserveStockInvocation) CancelRequested() bool { return inv.core.CancelRequested() }

// AwaitedRunID reports the run the previous attempt parked on via
// durable.AwaitRun, once it reached terminality.
func (inv ReserveStockInvocation) AwaitedRunID() (durable.RunID, bool) {
	return inv.core.AwaitedRunID()
}

// Annotations returns a caller-owned copy of the run's immutable
// acceptance-time annotations (trace contexts, tenant tags).
func (inv ReserveStockInvocation) Annotations() map[string]string { return inv.core.Annotations() }

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (inv ReserveStockInvocation) Input() *FulfillOrderInput {
	msg, _ := inv.core.InputMessage().(*FulfillOrderInput)
	return msg
}

// State returns the committed state of the referenced step for this run.
// ok is false when no committed state exists.
func (inv ReserveStockInvocation) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(inv.core, step)
}

// ReserveStockHandler implements step "reserve-stock/v1".
type ReserveStockHandler interface {
	Run(context.Context, ReserveStockInvocation) (*ReserveStock, error)

	Unwind(context.Context, ReserveStockInvocation, durable.Failure) error
}

// ReserveStockFuncs adapts a pair of functions to ReserveStockHandler.
type ReserveStockFuncs struct {
	RunFunc    func(ctx context.Context, inv ReserveStockInvocation) (*ReserveStock, error)
	UnwindFunc func(context.Context, ReserveStockInvocation, durable.Failure) error
}

func (f ReserveStockFuncs) Run(ctx context.Context, inv ReserveStockInvocation) (*ReserveStock, error) {
	return f.RunFunc(ctx, inv)
}

func (f ReserveStockFuncs) Unwind(ctx context.Context, inv ReserveStockInvocation, failure durable.Failure) error {
	return f.UnwindFunc(ctx, inv, failure)
}

// ChargePaymentInvocation is passed to ChargePaymentHandler methods.
type ChargePaymentInvocation struct {
	core *durable.Invocation
}

func (inv ChargePaymentInvocation) PipelineID() durable.PipelineID { return inv.core.PipelineID() }
func (inv ChargePaymentInvocation) ResourceID() durable.ResourceID { return inv.core.ResourceID() }
func (inv ChargePaymentInvocation) RunID() durable.RunID           { return inv.core.RunID() }
func (inv ChargePaymentInvocation) StepID() durable.StepID         { return inv.core.StepID() }
func (inv ChargePaymentInvocation) Attempt() uint64                { return inv.core.Attempt() }
func (inv ChargePaymentInvocation) Phase() durable.Phase           { return inv.core.Phase() }

// CancelRequested reports whether a cancellation request was pending when
// this attempt was reserved.
func (inv ChargePaymentInvocation) CancelRequested() bool { return inv.core.CancelRequested() }

// AwaitedRunID reports the run the previous attempt parked on via
// durable.AwaitRun, once it reached terminality.
func (inv ChargePaymentInvocation) AwaitedRunID() (durable.RunID, bool) {
	return inv.core.AwaitedRunID()
}

// Annotations returns a caller-owned copy of the run's immutable
// acceptance-time annotations (trace contexts, tenant tags).
func (inv ChargePaymentInvocation) Annotations() map[string]string { return inv.core.Annotations() }

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (inv ChargePaymentInvocation) Input() *FulfillOrderInput {
	msg, _ := inv.core.InputMessage().(*FulfillOrderInput)
	return msg
}

// State returns the committed state of the referenced step for this run.
// ok is false when no committed state exists.
func (inv ChargePaymentInvocation) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(inv.core, step)
}

// ChargePaymentHandler implements step "charge-payment/v1".
type ChargePaymentHandler interface {
	Run(context.Context, ChargePaymentInvocation) (*ChargePayment, error)

	Unwind(context.Context, ChargePaymentInvocation, durable.Failure) error
}

// ChargePaymentFuncs adapts a pair of functions to ChargePaymentHandler.
type ChargePaymentFuncs struct {
	RunFunc    func(ctx context.Context, inv ChargePaymentInvocation) (*ChargePayment, error)
	UnwindFunc func(context.Context, ChargePaymentInvocation, durable.Failure) error
}

func (f ChargePaymentFuncs) Run(ctx context.Context, inv ChargePaymentInvocation) (*ChargePayment, error) {
	return f.RunFunc(ctx, inv)
}

func (f ChargePaymentFuncs) Unwind(ctx context.Context, inv ChargePaymentInvocation, failure durable.Failure) error {
	return f.UnwindFunc(ctx, inv, failure)
}

// ShipInvocation is passed to ShipHandler methods.
type ShipInvocation struct {
	core *durable.Invocation
}

func (inv ShipInvocation) PipelineID() durable.PipelineID { return inv.core.PipelineID() }
func (inv ShipInvocation) ResourceID() durable.ResourceID { return inv.core.ResourceID() }
func (inv ShipInvocation) RunID() durable.RunID           { return inv.core.RunID() }
func (inv ShipInvocation) StepID() durable.StepID         { return inv.core.StepID() }
func (inv ShipInvocation) Attempt() uint64                { return inv.core.Attempt() }
func (inv ShipInvocation) Phase() durable.Phase           { return inv.core.Phase() }

// CancelRequested reports whether a cancellation request was pending when
// this attempt was reserved.
func (inv ShipInvocation) CancelRequested() bool { return inv.core.CancelRequested() }

// AwaitedRunID reports the run the previous attempt parked on via
// durable.AwaitRun, once it reached terminality.
func (inv ShipInvocation) AwaitedRunID() (durable.RunID, bool) { return inv.core.AwaitedRunID() }

// Annotations returns a caller-owned copy of the run's immutable
// acceptance-time annotations (trace contexts, tenant tags).
func (inv ShipInvocation) Annotations() map[string]string { return inv.core.Annotations() }

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (inv ShipInvocation) Input() *FulfillOrderInput {
	msg, _ := inv.core.InputMessage().(*FulfillOrderInput)
	return msg
}

// State returns the committed state of the referenced step for this run.
// ok is false when no committed state exists.
func (inv ShipInvocation) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(inv.core, step)
}

// ShipHandler implements step "ship/v1".
type ShipHandler interface {
	Run(context.Context, ShipInvocation) (*Ship, error)
}

// ShipFunc adapts a function to ShipHandler, in the style of
// http.HandlerFunc.
type ShipFunc func(ctx context.Context, inv ShipInvocation) (*Ship, error)

func (f ShipFunc) Run(ctx context.Context, inv ShipInvocation) (*Ship, error) { return f(ctx, inv) }

// FulfillOrderReducer produces the pipeline output from the immutable input
// and committed step states. It must be pure: deterministic, side-effect
// free, synchronous, and non-failing.
type FulfillOrderReducer func(*FulfillOrder) *FulfillOrderOutput

var fulfillOrderViews sync.Map

func (x *FulfillOrder) durableView() *durable.ReduceView {
	v, ok := fulfillOrderViews.Load(x)
	if !ok {
		panic("orderspb: FulfillOrder is only usable as a reducer view during reduction")
	}
	return v.(*durable.ReduceView)
}

// Input returns a defensive caller-owned copy of the immutable pipeline input.
func (x *FulfillOrder) Input() *FulfillOrderInput {
	msg, _ := x.durableView().InputMessage().(*FulfillOrderInput)
	return msg
}

// State returns the committed state of the referenced step for the run
// being reduced. ok is false when no committed state exists.
func (x *FulfillOrder) State[T proto.Message](step durable.StateStepRef[T]) (T, bool) {
	return durable.LookupState(x.durableView(), step)
}

// FulfillOrderDefinition is the unbound pipeline definition.
type FulfillOrderDefinition struct {
	def *durable.Definition
}

// NewFulfillOrder assembles the "fulfill-order" pipeline definition
// from its step handlers and reducer.
func NewFulfillOrder(
	reserveStock ReserveStockHandler,
	chargePayment ChargePaymentHandler,
	ship ShipHandler,
	reduce FulfillOrderReducer,
) *FulfillOrderDefinition {
	return &FulfillOrderDefinition{def: durable.NewDefinition(durable.DefinitionConfig{
		ID:       "fulfill-order",
		NewInput: func() proto.Message { return &FulfillOrderInput{} },
		Reduce: func(view *durable.ReduceView) proto.Message {
			x := &FulfillOrder{}
			fulfillOrderViews.Store(x, view)
			defer fulfillOrderViews.Delete(x)
			return reduce(x)
		},
		Steps: []durable.StepConfig{
			{
				ID:       "reserve-stock/v1",
				Unwind:   true,
				HasState: true,
				Run: func(ctx context.Context, core *durable.Invocation) (proto.Message, error) {
					state, err := reserveStock.Run(ctx, ReserveStockInvocation{core: core})
					if state == nil {
						return nil, err
					}
					return state, err
				},
				UnwindFunc: func(ctx context.Context, core *durable.Invocation, failure durable.Failure) error {
					return reserveStock.Unwind(ctx, ReserveStockInvocation{core: core}, failure)
				},
			},
			{
				ID:       "charge-payment/v1",
				Unwind:   true,
				HasState: true,
				Run: func(ctx context.Context, core *durable.Invocation) (proto.Message, error) {
					state, err := chargePayment.Run(ctx, ChargePaymentInvocation{core: core})
					if state == nil {
						return nil, err
					}
					return state, err
				},
				UnwindFunc: func(ctx context.Context, core *durable.Invocation, failure durable.Failure) error {
					return chargePayment.Unwind(ctx, ChargePaymentInvocation{core: core}, failure)
				},
			},
			{
				ID:       "ship/v1",
				HasState: true,
				Run: func(ctx context.Context, core *durable.Invocation) (proto.Message, error) {
					state, err := ship.Run(ctx, ShipInvocation{core: core})
					if state == nil {
						return nil, err
					}
					return state, err
				},
			},
		},
	})}
}

// Bind registers the definition with an engine. It is allowed only before
// Engine.Start.
func (d *FulfillOrderDefinition) Bind(e *durable.Engine) (*FulfillOrderPipeline, error) {
	p, err := d.def.Bind(e)
	if err != nil {
		return nil, err
	}
	return &FulfillOrderPipeline{pipeline: p}, nil
}

// FulfillOrderPipeline is the definition bound to an engine.
type FulfillOrderPipeline struct {
	pipeline *durable.Pipeline
}

// Schedule creates a run for the resource slot or returns the active one.
func (p *FulfillOrderPipeline) Schedule(ctx context.Context, resource durable.ResourceID, input *FulfillOrderInput, opts ...durable.ScheduleOption) (FulfillOrderRun, bool, error) {
	run, created, err := p.pipeline.Schedule(ctx, resource, input, opts...)
	if err != nil {
		return FulfillOrderRun{}, created, err
	}
	return FulfillOrderRun{run: run}, created, nil
}

// Run returns a handle to an existing run of this pipeline.
func (p *FulfillOrderPipeline) Run(ctx context.Context, id durable.RunID) (FulfillOrderRun, error) {
	run, err := p.pipeline.Run(ctx, id)
	if err != nil {
		return FulfillOrderRun{}, err
	}
	return FulfillOrderRun{run: run}, nil
}

// ActiveRun returns a handle to this pipeline's nonterminal run for a
// resource, if one exists — a read-only observation for wait/inspect
// flows; claiming the slot atomically remains Schedule's job.
func (p *FulfillOrderPipeline) ActiveRun(ctx context.Context, resource durable.ResourceID) (FulfillOrderRun, bool, error) {
	run, ok, err := p.pipeline.ActiveRun(ctx, resource)
	if err != nil || !ok {
		return FulfillOrderRun{}, ok, err
	}
	return FulfillOrderRun{run: run}, true, nil
}

// Active returns handles for this pipeline's nonterminal runs.
func (p *FulfillOrderPipeline) Active(ctx context.Context) ([]FulfillOrderRun, error) {
	runs, err := p.pipeline.Active(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]FulfillOrderRun, 0, len(runs))
	for _, run := range runs {
		out = append(out, FulfillOrderRun{run: run})
	}
	return out, nil
}

// Runs returns handles for all runs of this pipeline against a resource,
// oldest first.
func (p *FulfillOrderPipeline) Runs(ctx context.Context, resource durable.ResourceID) ([]FulfillOrderRun, error) {
	runs, err := p.pipeline.Runs(ctx, resource)
	if err != nil {
		return nil, err
	}
	out := make([]FulfillOrderRun, 0, len(runs))
	for _, run := range runs {
		out = append(out, FulfillOrderRun{run: run})
	}
	return out, nil
}

// FulfillOrderRun is a typed handle to one run of the pipeline.
type FulfillOrderRun struct {
	run durable.Run
}

func (r FulfillOrderRun) ID() durable.RunID { return r.run.ID() }

func (r FulfillOrderRun) Status(ctx context.Context) (durable.Status, error) {
	return r.run.Status(ctx)
}

// Cancel durably requests cancellation: the run stops selecting new
// forward work and unwinds successfully executed steps.
func (r FulfillOrderRun) Cancel(ctx context.Context, cause string) error {
	return r.run.Cancel(ctx, cause)
}

// Input returns a defensive caller-owned copy of the run's immutable
// pipeline input.
func (r FulfillOrderRun) Input(ctx context.Context) (*FulfillOrderInput, error) {
	b, err := r.run.InputBytes(ctx)
	if err != nil {
		return nil, err
	}
	msg := &FulfillOrderInput{}
	if err := proto.Unmarshal(b, msg); err != nil {
		return nil, err
	}
	return msg, nil
}

// Wait blocks until the run is terminal. A successful result carries the
// pipeline output; a failed run has none.
func (r FulfillOrderRun) Wait(ctx context.Context) (FulfillOrderResult, error) {
	res, err := r.run.Wait(ctx)
	if err != nil {
		return FulfillOrderResult{}, err
	}
	out := FulfillOrderResult{Result: res}
	if res.Succeeded() {
		b, err := r.run.OutputBytes(ctx)
		if err != nil {
			return FulfillOrderResult{}, err
		}
		msg := &FulfillOrderOutput{}
		if err := proto.Unmarshal(b, msg); err != nil {
			return FulfillOrderResult{}, err
		}
		out.output = msg
	}
	return out, nil
}

// FulfillOrderResult is the typed terminal result of a run.
type FulfillOrderResult struct {
	durable.Result
	output *FulfillOrderOutput
}

// Output returns the pipeline output. It is non-nil exactly when the run
// succeeded.
func (r FulfillOrderResult) Output() *FulfillOrderOutput { return r.output }
