// The fulfill-order pipeline: a classic order-fulfillment saga used by
// the OpenTelemetry tracing example. Stock is reserved and payment
// charged with unwind compensation (release, refund); shipping failure
// unwinds both.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: orders/v1/orders.proto

package orderspb

import (
	_ "github.com/dangra/durable/durablepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FulfillOrderInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity      uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	AmountCents   uint64                 `protobuf:"varint,3,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	ShipTo        string                 `protobuf:"bytes,4,opt,name=ship_to,json=shipTo,proto3" json:"ship_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FulfillOrderInput) Reset() {
	*x = FulfillOrderInput{}
	mi := &file_orders_v1_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FulfillOrderInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FulfillOrderInput) ProtoMessage() {}

func (x *FulfillOrderInput) ProtoReflect() protoreflect.Message {
	mi := &file_orders_v1_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FulfillOrderInput.ProtoReflect.Descriptor instead.
func (*FulfillOrderInput) Descriptor() ([]byte, []int) {
	return file_orders_v1_orders_proto_rawDescGZIP(), []int{0}
}

func (x *FulfillOrderInput) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *FulfillOrderInput) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *FulfillOrderInput) GetAmountCents() uint64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *FulfillOrderInput) GetShipTo() string {
	if x != nil {
		return x.ShipTo
	}
	return ""
}

type FulfillOrderOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId    string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FulfillOrderOutput) Reset() {
	*x = FulfillOrderOutput{}
	mi := &file_orders_v1_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FulfillOrderOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FulfillOrderOutput) ProtoMessage() {}

func (x *FulfillOrderOutput) ProtoReflect() protoreflect.Message {
	mi := &file_orders_v1_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FulfillOrderOutput.ProtoReflect.Descriptor instead.
func (*FulfillOrderOutput) Descriptor() ([]byte, []int) {
	return file_orders_v1_orders_proto_rawDescGZIP(), []int{1}
}

func (x *FulfillOrderOutput) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

type ReserveStock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveStock) Reset() {
	*x = ReserveStock{}
	mi := &file_orders_v1_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStock) ProtoMessage() {}

func (x *ReserveStock) ProtoReflect() protoreflect.Message {
	mi := &file_orders_v1_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStock.ProtoReflect.Descriptor instead.
func (*ReserveStock) Descriptor() ([]byte, []int) {
	return file_orders_v1_orders_proto_rawDescGZIP(), []int{2}
}

func (x *ReserveStock) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type ChargePayment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChargeId      string                 `protobuf:"bytes,1,opt,name=charge_id,json=chargeId,proto3" json:"charge_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChargePayment) Reset() {
	*x = ChargePayment{}
	mi := &file_orders_v1_orders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChargePayment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargePayment) ProtoMessage() {}

func (x *ChargePayment) ProtoReflect() protoreflect.Message {
	mi := &file_orders_v1_orders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargePayment.ProtoReflect.Descriptor instead.
func (*ChargePayment) Descriptor() ([]byte, []int) {
	return file_orders_v1_orders_proto_rawDescGZIP(), []int{3}
}

func (x *ChargePayment) GetChargeId() string {
	if x != nil {
		return x.ChargeId
	}
	return ""
}

type Ship struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId    string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ship) Reset() {
	*x = Ship{}
	mi := &file_orders_v1_orders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ship) ProtoMessage() {}

func (x *Ship) ProtoReflect() protoreflect.Message {
	mi := &file_orders_v1_orders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ship.ProtoReflect.Descriptor instead.
func (*Ship) Descriptor() ([]byte, []int) {
	return file_orders_v1_orders_proto_rawDescGZIP(), []int{4}
}

func (x *Ship) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

type FulfillOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FulfillOrder) Reset() {
	*x = FulfillOrder{}
	mi := &file_orders_v1_orders_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FulfillOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FulfillOrder) ProtoMessage() {}

func (x *FulfillOrder) ProtoReflect() protoreflect.Message {
	mi := &file_orders_v1_orders_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FulfillOrder.ProtoReflect.Descriptor instead.
func (*FulfillOrder) Descriptor() ([]byte, []int) {
	return file_orders_v1_orders_proto_rawDescGZIP(), []int{5}
}

var File_orders_v1_orders_proto protoreflect.FileDescriptor

const file_orders_v1_orders_proto_rawDesc = "" +
	"\n" +
	"\x16orders/v1/orders.proto\x12\torders.v1\x1a\x18durable/v1/options.proto\"}\n" +
	"\x11FulfillOrderInput\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\rR\bquantity\x12!\n" +
	"\famount_cents\x18\x03 \x01(\x04R\vamountCents\x12\x17\n" +
	"\aship_to\x18\x04 \x01(\tR\x06shipTo\"5\n" +
	"\x12FulfillOrderOutput\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\"O\n" +
	"\fReserveStock\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId:\x18\x8a\xa8\x19\x14\n" +
	"\x10reserve-stock/v1\x10\x01\"G\n" +
	"\rChargePayment\x12\x1b\n" +
	"\tcharge_id\x18\x01 \x01(\tR\bchargeId:\x19\x8a\xa8\x19\x15\n" +
	"\x11charge-payment/v1\x10\x01\"6\n" +
	"\x04Ship\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId:\r\x8a\xa8\x19\t\n" +
	"\aship/v1\"\xa6\x01\n" +
	"\fFulfillOrder:\x95\x01\x92\xa8\x19\x90\x01\n" +
	"\rfulfill-order\x12\x1c.orders.v1.FulfillOrderInput\x1a\x1d.orders.v1.FulfillOrderOutput\"\x17.orders.v1.ReserveStock\"\x18.orders.v1.ChargePayment\"\x0f.orders.v1.ShipBCZAgithub.com/dangra/durable/examples/tracing-otel/orderspb;orderspbb\x06proto3"

var (
	file_orders_v1_orders_proto_rawDescOnce sync.Once
	file_orders_v1_orders_proto_rawDescData []byte
)

func file_orders_v1_orders_proto_rawDescGZIP() []byte {
	file_orders_v1_orders_proto_rawDescOnce.Do(func() {
		file_orders_v1_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orders_v1_orders_proto_rawDesc), len(file_orders_v1_orders_proto_rawDesc)))
	})
	return file_orders_v1_orders_proto_rawDescData
}

var file_orders_v1_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_orders_v1_orders_proto_goTypes = []any{
	(*FulfillOrderInput)(nil),  // 0: orders.v1.FulfillOrderInput
	(*FulfillOrderOutput)(nil), // 1: orders.v1.FulfillOrderOutput
	(*ReserveStock)(nil),       // 2: orders.v1.ReserveStock
	(*ChargePayment)(nil),      // 3: orders.v1.ChargePayment
	(*Ship)(nil),               // 4: orders.v1.Ship
	(*FulfillOrder)(nil),       // 5: orders.v1.FulfillOrder
}
var file_orders_v1_orders_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_orders_v1_orders_proto_init() }
func file_orders_v1_orders_proto_init() {
	if File_orders_v1_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orders_v1_orders_proto_rawDesc), len(file_orders_v1_orders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orders_v1_orders_proto_goTypes,
		DependencyIndexes: file_orders_v1_orders_proto_depIdxs,
		MessageInfos:      file_orders_v1_orders_proto_msgTypes,
	}.Build()
	File_orders_v1_orders_proto = out.File
	file_orders_v1_orders_proto_goTypes = nil
	file_orders_v1_orders_proto_depIdxs = nil
}
